<a href="https://colab.research.google.com/github/Baelfyre/A3101-ml-linear-algebra-project-Team-3/blob/main/Week3_Preprocessing_Submission/ml_preprocessing_workflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FinMark Corporation: ML Solution Dataset Preprocessing
**Course:** MO-IT162 - Math for Machine Learning: Linear Algebra  
**Section:** A3101  
**Team:** Team 3  

## Team Members
- Ghaylord Benedict Lugod
- James Lynelle Ongo
- Kaselyn Cates Ponteres
- Mark Anthony Goyon

## Project Context

FinMark Corporation aims to improve its ability to analyze customer data,
identify meaningful patterns, and generate useful business insights through
a machine learning solution.

The project is completed through three major stages:

1. **Milestone 1: ML Solution EDA**  
   Explore the collected customer transaction, demographic, and social media
   datasets to understand their structure, identify patterns, detect anomalies,
   and assess data quality.

2. **Milestone 2: ML Solution DataViz**  
   Develop visualizations that reveal relationships, trends, and patterns
   related to customer behavior and market activity.

3. **Terminal Assessment: ML Solution Presentation**  
   Present the analytical process, visualizations, challenges, findings,
   and the proposed machine learning solution.

This notebook focuses on preprocessing the FinMark datasets in preparation
for Milestone 1.

## Business Problem

FinMark Corporation collects customer-related information from multiple
sources, including customer demographics, transaction records, and social
media interactions.

However, incomplete, inconsistent, incorrectly formatted, or invalid data
can reduce the reliability of later analysis and machine learning results.

Before meaningful exploratory data analysis can be performed, the datasets
must first be verified and cleaned to ensure that the information used for
analysis is sufficiently consistent, accurate, and usable.

## Current Activity Scope

This notebook focuses on preparing the FinMark datasets for exploratory
data analysis.

The preprocessing activity includes:

- collecting and loading the required datasets;
- verifying dataset structure and contents;
- identifying missing values;
- checking duplicate records;
- validating data types;
- identifying inconsistent categorical values;
- checking numeric and date values;
- reviewing relationships between dataset identifiers;
- applying justified cleaning procedures;
- validating the cleaned datasets; and
- saving the finalized preprocessed datasets.

Machine learning model development, model training, and final data
visualization are outside the scope of this preprocessing notebook.

## Preprocessing Principles

The following principles will guide the preprocessing process:

1. The original FinMark datasets will remain unchanged.
2. Data-quality issues will be identified and documented before cleaning.
3. Separate cleaned DataFrames will be created for preprocessing.
4. Records containing missing values will be omitted rather than filled
   with unsupported estimated values.
5. Valid information will be standardized when differences are caused only
   by formatting, capitalization, spacing, or naming conventions.
6. Duplicate records will only be removed after they are verified.
7. Invalid or questionable values will be reviewed before deciding whether
   a record should be removed.
8. CustomerID, TransactionID, and InteractionID will be retained in the
   cleaned master datasets because they support record identification,
   relationships, duplicate checking, and data integrity.
9. Identifier fields will not be treated as machine learning features or
   ordinary analytical variables.
10. The effect of preprocessing will be measured by comparing the raw and
    cleaned datasets.

## Dataset Roles

The FinMark project uses three datasets.

### Customer Demographics

Contains customer-level information that may help describe customer
characteristics and support customer segmentation and behavioral analysis.

### Customer Transactions

Contains records of customer purchasing activity that may help examine
spending behavior, product preferences, and transaction patterns.

### Social Media Interactions

Contains records of customer social media activity that may help examine
engagement patterns, interaction types, and customer sentiment.

The datasets provide different but complementary perspectives on FinMark
customers.

CustomerID serves as the common customer identifier that can later be used
to relate records across the datasets.

## Data Collection

The datasets used in this activity were obtained from the official FinMark
MFML project resources provided for the course.

The following files are used:

- `customer_demographics_contaminated.csv`
- `customer_transactions_contaminated.csv`
- `social_media_interactions_contaminated.csv`

The datasets were downloaded and stored in the MO-IT162 project folder in
Google Drive before being accessed through Google Colab.

No external dataset is introduced during this preprocessing activity.
The analysis is limited to the data supplied for the FinMark project.

## Environment Setup

Google Colab is used as the working environment for this activity.

The FinMark files are stored in Google Drive so that the original datasets
and generated preprocessing outputs remain available even after the Colab
runtime ends.

The required Python libraries and project paths are initialized below.

In [ ]:
# ENVIRONMENT AND PROJECT PATH SETUP
# Google Drive is mounted and the FinMark project folders are defined.
# Raw contaminated datasets are kept separately from generated preprocessing
# outputs so the original source files remain unchanged.

from google.colab import drive
from pathlib import Path

import pandas as pd
import numpy as np

# Mount Google Drive
drive.mount('/content/drive')

# Main MO-IT162 project folder
BASE_PATH = Path(
    "/content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA"
)

# Milestone 1 folder
MS1_PATH = BASE_PATH / "MS1"

# Raw source datasets
RAW_PATH = MS1_PATH / "contaminated_datasets"

# Working/output folders
PROCESSED_PATH = MS1_PATH / "processed"
OUTPUT_PATH = MS1_PATH / "outputs"

# Final Week 3 submission package
WEEK3_OUTPUT_PATH = MS1_PATH / "Week3_Preprocessing_Submission"

# Create generated-output folders if they do not already exist
PROCESSED_PATH.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
WEEK3_OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

print("Project path:", BASE_PATH)
print("Milestone 1 path:", MS1_PATH)
print("Raw dataset path:", RAW_PATH)
print("Processed data path:", PROCESSED_PATH)
print("Output path:", OUTPUT_PATH)
print("Week 3 submission path:", WEEK3_OUTPUT_PATH)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Project path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA
Milestone 1 path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1
Raw dataset path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/contaminated_datasets
Processed data path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/processed
Output path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/outputs
Week 3 submission path: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/Week3_Preprocessing_Submission

### Project File Verification

Before loading the datasets, the contents of the raw dataset directory are
listed to confirm that Google Colab is connected to the correct folder and
that the required FinMark source files are available.

In [ ]:
# VERIFY RAW DATASET FILES
# This checks the dedicated contaminated_datasets folder before loading
# the FinMark source files.

for file in RAW_PATH.iterdir():
    print(file.name)

customer_demographics_contaminated.csv
customer_transactions_contaminated.csv
social_media_interactions_contaminated.csv

## Data Loading

The three FinMark CSV files are loaded into separate Pandas DataFrames.

The `_raw` suffix is used to identify the original imported datasets.
These DataFrames will remain unchanged throughout preprocessing so that
the original data can always be compared with the cleaned outputs.

In [ ]:
# LOAD ORIGINAL FINMARK DATASETS
# The three contaminated CSV files are loaded from the dedicated raw-data
# folder. The _raw suffix identifies the original imported DataFrames,
# which remain unchanged throughout preprocessing.

demographics_raw = pd.read_csv(
    RAW_PATH / "customer_demographics_contaminated.csv"
)

transactions_raw = pd.read_csv(
    RAW_PATH / "customer_transactions_contaminated.csv"
)

social_raw = pd.read_csv(
    RAW_PATH / "social_media_interactions_contaminated.csv"
)

print("Raw datasets loaded successfully.")

Raw datasets loaded successfully.

### Raw Dataset Dimensions

The number of rows and columns in each dataset is recorded before
preprocessing.

These dimensions provide the baseline that will later be compared with
the cleaned datasets to determine how many records were affected by the
preprocessing process.

In [ ]:
print("Customer Demographics")
print("Rows:", demographics_raw.shape[0])
print("Columns:", demographics_raw.shape[1])

print("\nCustomer Transactions")
print("Rows:", transactions_raw.shape[0])
print("Columns:", transactions_raw.shape[1])

print("\nSocial Media Interactions")
print("Rows:", social_raw.shape[0])
print("Columns:", social_raw.shape[1])

Customer Demographics
Rows: 3200
Columns: 6

Customer Transactions
Rows: 3200
Columns: 6

Social Media Interactions
Rows: 3200
Columns: 6

### Dataset Baseline Summary

A baseline summary is created to document the original dimensions of all
three datasets in one table.

This summary will later be used for before-and-after comparison following
data cleaning.

In [ ]:
baseline_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Rows": [
        demographics_raw.shape[0],
        transactions_raw.shape[0],
        social_raw.shape[0]
    ],
    "Columns": [
        demographics_raw.shape[1],
        transactions_raw.shape[1],
        social_raw.shape[1]
    ]
})

display(baseline_summary)

                     Dataset  Rows  Columns
0      Customer Demographics  3200        6
1      Customer Transactions  3200        6
2  Social Media Interactions  3200        6

### Preview Raw Dataset Records

The first five records from each dataset are displayed to verify that the
CSV files were parsed correctly and that the expected columns and values
appear in a usable tabular structure.

This preview is only an initial visual inspection. No values are modified
at this stage.

In [ ]:
print("Customer Demographics")
display(demographics_raw.head())

print("\nCustomer Transactions")
display(transactions_raw.head())

print("\nSocial Media Interactions")
display(social_raw.head())

Customer Demographics

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
0,9207fa75-5758-48d1-94ad-19c041e0520f,51.0,Female,Jensenberg,Low,2022-11-17
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
3,50118139-7264-428f-81cc-a25fddc5d6dd,44.0,Male,Port Carl,Medium,2024-06-10
4,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50.0,Female,Jessebury,High,2023-08-24

Customer Transactions

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

Social Media Interactions

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
2,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN

### Dataset Structure and Data Types

The structure of each dataset is reviewed using the `info()` method.

This provides the:

- number of records;
- column names;
- number of non-null values; and
- Pandas data type currently assigned to each column.

The results help identify potential missing values and fields whose
current data types may not match their intended analytical meaning.

In [ ]:
print("CUSTOMER DEMOGRAPHICS")
demographics_raw.info()

print("\nCUSTOMER TRANSACTIONS")
transactions_raw.info()

print("\nSOCIAL MEDIA INTERACTIONS")
social_raw.info()

CUSTOMER DEMOGRAPHICS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   3200 non-null   object
 1   Age          2909 non-null   object
 2   Gender       3200 non-null   object
 3   Location     3200 non-null   object
 4   IncomeLevel  2897 non-null   object
 5   SignupDate   3200 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

CUSTOMER TRANSACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   object
 1   TransactionID    3200 non-null   object
 2   TransactionDate  3200 non-null   object
 3   Amount           2896 non-null   object
 4   ProductCategory  2901 non-null   object
 5   PaymentMethod    3200 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

SOCIAL MEDIA INTERACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       3200 non-null   object
 1   InteractionID    3200 non-null   object
 2   InteractionDate  3200 non-null   object
 3   Platform         2889 non-null   object
 4   InteractionType  3200 non-null   object
 5   Sentiment        2871 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

### Initial Structural Observation

All three datasets contain 3,200 records and 6 columns.

The initial structure review also shows missing values in several fields:

- Customer Demographics:
  - `Age`
  - `IncomeLevel`

- Customer Transactions:
  - `Amount`
  - `ProductCategory`

- Social Media Interactions:
  - `Platform`
  - `Sentiment`

All columns are currently imported as `object` data types.

This does not immediately mean that every column has an incorrect data
type. However, fields that logically represent numeric values or dates
will require further validation before conversion.

No cleaning is applied at this stage because the identified issues must
first be examined and documented.

### Column Verification

The column names of each dataset are reviewed to confirm the available
variables and identify the fields that will be examined during
preprocessing.

The original column names are preserved at this stage. Any naming
normalization will only be performed later during the cleaning phase.

In [ ]:
print("Customer Demographics:")
print(demographics_raw.columns.tolist())

print("\nCustomer Transactions:")
print(transactions_raw.columns.tolist())

print("\nSocial Media Interactions:")
print(social_raw.columns.tolist())

Customer Demographics:
['CustomerID', 'Age', 'Gender', 'Location', 'IncomeLevel', 'SignupDate']

Customer Transactions:
['CustomerID', 'TransactionID', 'TransactionDate', 'Amount', 'ProductCategory', 'PaymentMethod']

Social Media Interactions:
['CustomerID', 'InteractionID', 'InteractionDate', 'Platform', 'InteractionType', 'Sentiment']

## Data Quality Verification

### Missing-Value Verification

Missing values are checked before any cleaning is applied.

The purpose of this step is to identify which variables contain incomplete
records, determine how many values are missing, and measure the percentage
of missing data in each column.

No rows are removed during this verification step.

In [ ]:
def missing_summary(df):
    return pd.DataFrame({
        "Missing Count": df.isnull().sum(),
        "Missing Percent": (df.isnull().mean() * 100).round(2)
    })

print("Customer Demographics")
display(missing_summary(demographics_raw))

print("\nCustomer Transactions")
display(missing_summary(transactions_raw))

print("\nSocial Media Interactions")
display(missing_summary(social_raw))

Customer Demographics

             Missing Count  Missing Percent
CustomerID               0             0.00
Age                    291             9.09
Gender                   0             0.00
Location                 0             0.00
IncomeLevel            303             9.47
SignupDate               0             0.00

Customer Transactions

                 Missing Count  Missing Percent
CustomerID                   0             0.00
TransactionID                0             0.00
TransactionDate              0             0.00
Amount                     304             9.50
ProductCategory            299             9.34
PaymentMethod                0             0.00

Social Media Interactions

                 Missing Count  Missing Percent
CustomerID                   0             0.00
InteractionID                0             0.00
InteractionDate              0             0.00
Platform                   311             9.72
InteractionType              0             0.00
Sentiment                  329            10.28

### Missing-Data Observation

The missing-value review identified incomplete records in the following
variables:

- **Customer Demographics**
  - `Age`
  - `IncomeLevel`

- **Customer Transactions**
  - `Amount`
  - `ProductCategory`

- **Social Media Interactions**
  - `Platform`
  - `Sentiment`

The remaining variables do not contain null values based on the current
verification results.

These missing values represent unavailable information in the supplied
FinMark datasets. No cleaning action is applied yet because the affected
records must first be documented before row removal is performed.

### Missing-Data Disclaimer

The missing information occurs in variables that contribute to customer,
transaction, and social media analysis.

Because the original values cannot be reliably reconstructed from the
available FinMark datasets, missing values will not be replaced with
estimated or assumed values.

During the cleaning phase, records containing null values will be omitted
from the cleaned datasets.

This approach may reduce the number of available observations and may
affect the representation of some customer groups or behaviors. The number
and percentage of removed rows will therefore be measured and documented
after cleaning.

### Review Records Containing Missing Values

Rows containing one or more null values are displayed before cleaning.

This allows the incomplete records to be reviewed directly and confirms
which observations would be affected by the planned row-removal process.

In [ ]:
print("Customer Demographics with Missing Values")
display(
    demographics_raw[
        demographics_raw.isnull().any(axis=1)
    ].head(20)
)

print("\nCustomer Transactions with Missing Values")
display(
    transactions_raw[
        transactions_raw.isnull().any(axis=1)
    ].head(20)
)

print("\nSocial Media Interactions with Missing Values")
display(
    social_raw[
        social_raw.isnull().any(axis=1)
    ].head(20)
)

Customer Demographics with Missing Values

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
1,5fb09cd8-a473-46f7-80bd-6e49cf509078,NaN,Female,Castilloport,High,2020-07-21
2,c139496e-cc89-498a-bd90-1fb4627b6cff,37.0,Male,Lake Jennifertown,NaN,2021-01-01
6,89f7de44-e592-43c6-b033-bcbcf24088ba,NaN,Female,South Derekbury,High,2019-12-08
7,9f2128cd-2f2b-4f71-987c-29fd045021f0,NaN,Female,Lake Erin,Medium,2022-04-26
8,fbcd7128-ce04-4799-8c1c-722330507b96,NaN,Female,New Reginabury,NaN,2022-04-17
9,40f5a5dd-a46f-4a5e-8c0f-fe04389ddec8,NaN,Female,Mariaberg,High,2024-02-18
11,7f87735e-2345-4e9f-84e9-149fc0f168f7,NaN,Female,Sheilabury,High,2022-08-12
12,aae60ad7-5553-4d10-a637-93d5dcc98e4a,NaN,Male,Brownfort,Low,2021-12-02
14,dc7f151c-dd0b-44b7-9ea2-ab684e50d463,NaN,Male,East Alexandra,Low,2019-08-05
23,fd63f236-3ec3-401d-9fa1-53bda0bd7c0e,NaN,Male,Thomasbury,Low,2021-05-29
32,88c11bb5-495a-4fa4-9dca-ba16c044b52f,29.0,Male,Cruzville,NaN,2022-01-03
33,249a52ef-4f20-4035-ade0-4855537d75a2,25.0,Female,Port Dillonstad,NaN,2021-08-11
34,fceafdf4-01c9-44dc-9978-b601bd35de86,NaN,Male,West Andrea,High,2022-12-29
42,a800ccba-e1ca-4f52-ad9f-14f3432699c9,NaN,Male,Randyton,NaN,2022-10-16
61,3961c9cd-9e5c-45b4-9d85-7614fd1b8323,NaN,Female,Port Juliaburgh,High,2019-10-25
64,52303d17-9d24-4c20-89e3-7bcfa92140c9,150,Male,Spencermouth,NaN,2022-06-25
65,5bd86a09-03ee-4de7-bb87-7411f34e19cb,22.0,Male,Jeanville,NaN,2023-10-23
66,f381038c-b3ed-4561-84b1-0f60d4afb6c9,39.0,Male,New Diana,NaN,2023-05-12
70,c38e6ca5-eac5-4f80-8f80-ef7f21fad135,NaN,Female,North Ryanfort,High,2023-04-09
83,ce641770-fe31-4320-a990-6727108bc6fe,NaN,Female,Garrettmouth,Medium,2023-03-16

Customer Transactions with Missing Values

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,2024-04-07,Free,NaN,Credit Card
6,7fbc5847-a652-4fc8-a7d8-5e85d846e91b,591f1ea2-c97d-44dd-9539-71ac89b94ff3,2024-01-12,NaN,Automotive,PayPal
27,9ed2792c-bffb-472f-9c11-61bb7203b01f,f70e7ab7-43b4-402b-9627-76ec2e1c341d,2023-03-08,84.72,NaN,Bank Transfer
37,328e739a-ddac-4661-97aa-76b8ee47e373,fd9a76ef-656b-490b-b390-fb38e5d0af51,2023-05-29,843.37,NaN,Debit Card
42,1d4e578b-738c-4913-84f4-b008488eab48,1e562ead-eac1-4013-87e2-2449249e49dd,2022-10-31,NaN,Electronics,Bank Transfer
48,6ce19d4b-8794-4a6a-b479-6b46b786836b,fde080f4-b08d-4920-b29e-b7223c2aa907,2022-09-08,NaN,Health & Beauty,Bank Transfer
50,2d71443b-57dd-4422-89b1-57ade9d5002d,ccae9190-d56d-48d4-8b6d-af77f88f40dc,2023-07-08,434.75,NaN,Debit Card
52,31a64c59-e32d-4d9c-ba9c-f308acd78daf,3db167d5-18aa-4073-a3fe-fb8971d83c6a,2023-08-20,NaN,NaN,Bank Transfer
57,ab0ff3f2-c413-41cd-a69d-9ec090b6739b,8cc19044-7a8a-4423-85c0-194588f148f5,2022-07-19,568.0,NaN,Bank Transfer
60,a64fcda9-e8fa-4568-b514-58b2664a906d,da7bfa64-3e05-4fe0-9505-1dee627bdb3d,2022-11-30,NaN,Health & Beauty,Credit Card
61,0156ef90-c829-4e9e-8fec-8634e8ff3c54,1ca5bb66-ab5f-4832-8f31-885cd5a161a8,2024-06-09,NaN,Clothing,Credit Card
76,399b2052-77c7-499f-950b-80f20d4ad109,6f3a078b-f043-4552-9805-23bcb9083321,2023-04-20,NaN,Health & Beauty,Credit Card
77,1c188e21-9a0a-420e-a39f-e17691fe17a6,890c8b92-5b0c-444f-b1ee-8f32cc8650b1,2023-01-22,NaN,Health & Beauty,Credit Card
83,e556be3f-49dd-47c3-9bd1-6f2fb1b79d52,1148f4f7-a824-4634-9b7d-9daeaedf6c17,2024-06-21,NaN,Home & Garden,Bank Transfer
91,47d03d6f-cb4d-4984-9aa6-96d20353bd91,c6585e31-fa59-4ade-89b8-e849b4048191,2023-01-10,120.07,NaN,PayPal
106,13c73f2c-056e-40c6-a61f-97d5790c504a,22da76bb-b240-4e90-8efe-de5e07061c51,26/10/2022,NaN,Home & Garden,Bank Transfer
115,cbd36938-08b9-41e6-9de5-a781a121d9fa,3b457c65-d12e-4866-af29-f7d0f9b8f3d9,2024-01-03,942.79,NaN,PayPal
119,279f267c-0ce8-4bc5-9cdd-d62c39547afa,94fa7157-ecc8-435b-8e97-f62c17a17aee,2024-06-06,203.7,NaN,Bank Transfer
120,d24275e1-2bd3-49f8-9596-9f962be5127c,523497aa-0b28-45b9-9b77-3211eb35d3e9,2024-03-26,NaN,Automotive,PayPal
128,d3493edf-9847-46ef-b400-7063b54bcf63,96bba17f-18b1-4717-9c8d-7aeae1e3ea05,2023-09-22,547.89,NaN,Debit Card

Social Media Interactions with Missing Values

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
0,2dcb9523-356b-40b2-a67b-1f27797de261,e5d15761-d0a7-4329-89e3-79a892c56097,2023-07-11,NaN,Comment,NaN
1,e12c37b3-7d4d-472f-9fd8-0df2cb3001aa,02f9f376-70ae-4fcd-9070-1db977939948,2023-07-06,Twitter,Share,NaN
4,ca1e90f6-0e5f-492e-ab92-252ff540da18,d9d1c6f8-5e15-4738-b52b-13c2982420cc,2023-07-08,Instagram,Like,NaN
7,7d83304d-2501-4c9f-ba63-a1a14343e51f,bcfc43e7-c5aa-4dbd-9961-0e108784b199,2024-03-29,Instagram,Comment,NaN
8,bd90f5cb-05a7-40f4-acb1-eedf48b58ffa,d2a06664-703d-4bc1-9401-a06f8c43fda5,2024-05-02,NaN,Like,Neutral
9,63ee220c-19ae-4113-b45c-276b22b068e1,67cdfb0b-3da6-46b8-a1f4-03b2abc81f58,2023-11-18,NaN,Comment,Positive
13,f0c55dc8-d7f6-481d-8992-af3ce9453a51,753ff148-793b-4db5-a3e1-16f6e470dd0a,2023-08-27,NaN,Comment,NaN
18,616e2347-91b4-4a50-8a15-4c65aff20788,7cdba85b-17cc-4d72-b4aa-14f718a50be6,2024-03-28,Instagram,Comment,NaN
22,348c5ab5-992d-4780-ba71-d1a5e3818191,a3b06362-9ff0-433b-be2f-477c452259c2,2023-08-29,Twitter,Share,NaN
32,cb92abec-3e14-4c2d-b8a7-265082126081,d1c446d7-ff9e-48f4-8b9f-03a2683a03d1,2024-04-01,NaN,Share,NaN
37,9f6b9ab6-1055-4a20-912e-23adb444695c,c3f47766-8472-44e0-b1af-fafee0015a8a,2023-09-18,NaN,Like,NaN
42,d18cda69-56ba-45a8-b3fe-ff52f040377a,8371e3a6-cbd5-4a07-9a7f-b334d046644e,2023-08-20,Instagram,Share,NaN
45,d1994e4a-365b-49fc-8a99-3bd92ff155e4,c63c466f-8945-42bc-9e35-fa52284f5227,2024-04-16,NaN,Comment,Neutral
46,be43e8db-0b64-425e-b11d-c15f19659bc2,de2ac7e5-2efd-4fd1-b38f-fb29078743ec,2023-09-07,NaN,Share,Negative
59,348c5ab5-992d-4780-ba71-d1a5e3818191,0265861e-f3f1-4218-bf5a-af624138d56b,2023-11-12,Instagram,Share,NaN
63,56f11a95-76f1-4a97-b38f-db1dc95da1ed,68c6b07a-4fe2-40ad-9a89-4cff4dda4903,2023-10-19,Facebook,Like,NaN
67,896a48cf-7ab6-41a8-ac94-9d7f6c211c01,cfa69d95-849b-4130-8ef8-c6842a15f08c,2024-03-17,Twitter,Like,NaN
72,54a1bbb2-9523-41a7-b8b5-9acd08f46da4,86844e2d-c646-42ae-a169-6e8b4718e9eb,2023-09-26,Instagram,Share,NaN
75,14a794f8-2099-4aee-97e4-bdd3899994c6,dcc6b868-950f-4c82-bb57-6981a47dfa6b,2023-09-26,Facebook,Like,NaN
78,7544489f-ec7e-48af-bec6-b6eab94a6e5c,fae8001a-955d-488d-a241-0fb507f300ed,12/08/2023,NaN,Share,Neutral

### Rows Affected by Missing Values

The number of rows containing at least one missing value is calculated
separately from the total number of missing cells.

This provides the actual number of observations that would be removed if
the row-omission cleaning policy is applied.

In [ ]:
missing_rows_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Rows with Missing Values": [
        demographics_raw.isnull().any(axis=1).sum(),
        transactions_raw.isnull().any(axis=1).sum(),
        social_raw.isnull().any(axis=1).sum()
    ],
    "Total Rows": [
        len(demographics_raw),
        len(transactions_raw),
        len(social_raw)
    ]
})

missing_rows_summary["Percent of Rows Affected"] = (
    missing_rows_summary["Rows with Missing Values"]
    / missing_rows_summary["Total Rows"]
    * 100
).round(2)

display(missing_rows_summary)

,Dataset,Rows with Missing Values,Total Rows,Percent of Rows Affected
0,Customer Demographics,562,3200,17.56
1,Customer Transactions,576,3200,18.00
2,Social Media Interactions,612,3200,19.12

### Duplicate Verification

Duplicate records are checked before cleaning because repeated rows may
artificially increase the representation of the same observation.

Two types of duplication are reviewed:

1. **Exact duplicate rows**  
   Rows where all column values are identical.

2. **Duplicate identifiers**  
   Records that share the same identifier, such as CustomerID,
   TransactionID, or InteractionID.

Duplicate identifiers are not automatically considered errors. For example,
a customer may legitimately appear in multiple transaction or interaction
records. The records must therefore be reviewed before any removal decision
is made.

In [ ]:
duplicate_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Exact Duplicate Rows": [
        demographics_raw.duplicated().sum(),
        transactions_raw.duplicated().sum(),
        social_raw.duplicated().sum()
    ]
})

display(duplicate_summary)

                     Dataset  Exact Duplicate Rows
0      Customer Demographics                   177
1      Customer Transactions                   185
2  Social Media Interactions                   180

### Review Exact Duplicate Records

If exact duplicate rows are detected, the affected records are displayed
for inspection before any cleaning action is applied.

Only confirmed duplicate observations should be removed during the cleaning
phase.

In [ ]:
print("Customer Demographics Exact Duplicates")
display(
    demographics_raw[
        demographics_raw.duplicated(keep=False)
    ].head(20)
)

print("\nCustomer Transactions Exact Duplicates")
display(
    transactions_raw[
        transactions_raw.duplicated(keep=False)
    ].head(20)
)

print("\nSocial Media Interactions Exact Duplicates")
display(
    social_raw[
        social_raw.duplicated(keep=False)
    ].head(20)
)

Customer Demographics Exact Duplicates

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
9,40f5a5dd-a46f-4a5e-8c0f-fe04389ddec8,NaN,Female,Mariaberg,High,2024-02-18
18,8de7560f-370d-4cfd-8135-20a3de237264,31.0,Female,Colemanstad,Low,2020-12-01
23,fd63f236-3ec3-401d-9fa1-53bda0bd7c0e,NaN,Male,Thomasbury,Low,2021-05-29
54,c9f831b4-43cf-4ed9-9b47-09542e239c70,53.0,Female,East Ryanbury,Medium,2023-10-12
56,348c5ab5-992d-4780-ba71-d1a5e3818191,46.0,Female,New Jesseside,Low,2023-09-24
91,ec42fc84-51a4-4f32-971a-132852d4fe36,NaN,Male,Michaelborough,Low,2022-04-23
106,74335a51-6283-4262-b8a5-c72d988f3007,56.0,Female,East Zacharyville,Low,2019-09-17
114,409d7d69-e0b1-4493-8b23-100fb9518966,64.0,Female,Bradleyborough,Low,2023-03-11
122,fd35b6b4-ad1c-49cc-9c34-8c2d696f38e2,42.0,Male,Karenbury,Low,2024-04-14
159,1c4c3ec8-256e-4c2c-bed6-cf5e97e076de,NaN,Male,New Amber,Low,2023-04-10
165,fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f,59.0,Female,East Nathantown,High,2022-04-14
206,1e2be761-bca8-4962-a270-7fc433d2179e,68.0,Female,East Ericmouth,Low,2023-11-26
265,e84f46dc-1d0e-4031-a4f6-2a6f46514fa6,49.0,Male,Samuelshire,Medium,2023-09-02
266,acf47c33-118a-4844-84f5-6c5834568e66,64.0,Male,Lake Victoria,High,2019-07-22
267,7fa1d4e1-e465-4d23-82c8-c096f58fb5ed,32.0,Male,Port William,Low,2024-01-29
268,ed46f0b3-870a-41c4-b2c2-6a47937d394e,34.0,Male,West Billy,High,2020-06-23
315,3330dbb6-1b22-4fe5-a4b5-0e5ce39d8591,50.0,Male,Stevensonview,Low,2020-08-21
317,68b5a27d-980f-409d-9b64-acc242c86f8e,48.0,Male,West Annstad,High,2023-12-23
344,587f0de4-1254-4ad6-9567-af6745c960b6,21.0,Female,Dawsonstad,High,2020-01-10
364,f447245d-7239-4808-974c-7fd358f61c2c,NaN,Male,North Tammyshire,Low,2023-11-12

Customer Transactions Exact Duplicates

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
9,474f9233-0616-431b-b3e9-a6feabe68abb,f8bde21a-7a6b-41f6-ac39-eeb77640fa9b,2023-06-15,149.39,Clothing,Debit Card
16,54b3556e-e480-41a2-9dcd-7da1d91655aa,c181a599-fcc7-4f9b-b618-783684e0fd24,2023-03-06,861.39,Clothing,Bank Transfer
36,9560ed71-7a04-4cd9-a576-b622c5690487,ad529898-c1b5-4fe7-b30b-a9f19c666386,2024-05-31,833.48,Automotive,Bank Transfer
45,d3493edf-9847-46ef-b400-7063b54bcf63,6fa36483-8ac7-4af8-9cc7-e0607673f331,2022-07-15,119.65,Clothing,PayPal
65,a0db86bf-0c2d-4c9e-8d3b-f5b33ac37cee,1048e98c-90fd-4cef-ba62-eb4b16816596,2023-09-08,596.73,Clothing,Credit Card
84,978c4300-e302-4677-b7f0-7b4a8e2a87b8,9af33eb6-952d-4f50-b8af-cf570b517d83,2023-07-20,80.69,Health & Beauty,PayPal
136,262adfc3-44ae-442d-a213-2d3eb9e668a3,966703bc-1ed1-44f3-a868-d2f09973e857,2022-08-31,NaN,Home & Garden,Bank Transfer
151,8f61e984-4fa5-4941-95ee-e42c92758e02,957d522b-3074-415c-ad64-6fd800ddc286,2024-02-22,334.96,Electronics,PayPal
162,e6f38640-260c-4c82-bb98-1a5ad730365e,c496b5ff-a157-45ad-95c8-4935b0e1b4b8,2022-11-05,359.4,Automotive,Debit Card
178,e8a5fdb8-fcd9-450c-9635-e376266c8bcf,208e7d1b-e7da-46f8-b6b8-678eef27699e,2023-06-21,645.53,Automotive,PayPal
218,9e5a62bf-b2cc-4743-b266-252c16a36f83,97f0f226-6531-4acb-b5fc-a3bbcb591c17,2023-01-06,NaN,Health & Beauty,PayPal
236,83b8546f-50a6-4b60-8dfc-78004cc0076c,6a76ae87-3484-430f-9372-01c8f1498959,2024-01-06,168.66,Health & Beauty,Debit Card
244,8a1b714a-0592-42f9-bdc0-e7d67163f3f1,ab88e4c7-3bc3-4dd4-879c-db75b263171d,2024-01-31,978.11,Electronics,PayPal
278,6bc3aaad-57cc-4fae-b57f-18faa88ce95b,191af024-d4d3-4144-86f7-11e09e4e9df8,2023-02-14,185.97,NaN,Debit Card
282,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
295,79fc606a-c02c-4c39-b065-3e88a59b366c,604d5342-6293-4870-997d-deeef832c557,2023-10-09,442.99,Home & Garden,PayPal
301,0865a620-9ff4-46ec-9f14-7efdd071a041,206e70f6-6775-4945-8e6e-cad206fe2a5f,2022-12-02,24.94,Clothing,Credit Card
305,634b25ce-d205-4a1e-b277-b70efc033fc6,ded7963e-87b2-45c2-ad06-359212a961e6,2024-01-25,726.69,Home & Garden,Credit Card
364,3d8408ab-60f2-465f-a112-d6b7747c4a4a,bfdef222-6989-42a9-8689-c43d017e9b55,2024-05-15,954.97,Automotive,PayPal

Social Media Interactions Exact Duplicates

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
3,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
30,eb8bb3ce-e182-4a9c-8084-c55c738815e1,ee2c3d14-248c-48b0-aa80-4ea97e449bf8,2023-12-22,Instagram,Comment,Negative
64,58ced86b-155c-45b1-96c4-92e39af3751e,7d7f1f20-150c-491c-9dc3-fe2922a19836,2023-10-10,Instagram,Comment,Negative
71,a7b667f7-d6c7-4fc6-b6d9-bcdeea32297c,39622755-9e00-4107-8ee1-5defd5a5dbab,2023-10-06,Twitter,Like,Neutral
91,47bf3bc6-17a6-4b21-82b5-90f78af4c25c,4eac4bf7-b0ff-4eb9-af31-69b5413a99af,2023-10-19,Instagram,Like,Positive
100,5dcc04f0-2300-4707-b737-82abb839b428,24bc4157-e0e9-47d4-a415-1bf0f63c4a42,2023-07-10,Facebook,Share,Positive
121,8f440758-f8ac-44ee-9f83-51d9bde6d101,1e83e078-67f9-4336-a4b3-49c2337f683b,2024-01-22,Facebook,Share,Positive
132,7a2c7c71-1f0d-4e00-b1e7-821708ec5194,5a302518-07f2-41ce-a2dc-ce83a00060a5,2024-01-26,Twitter,Share,Positive
134,9cb537a8-07c4-4bff-82ec-f3eed82e8917,2fff00c5-0627-4cf0-ad72-18e3505957cd,2023-08-22,NaN,Comment,Positive
137,37d18605-6890-4f11-bb14-23b460734df2,8d1937be-b8f2-437c-8b7a-3e0451fa09a1,2024-04-12,Instagram,Comment,Negative
138,fe4eace1-a485-45b5-827f-d8a3dfe9d92d,03be50b0-ca8f-4e86-8c12-eb8b184ef3db,2023-08-24,Instagram,Like,Positive
166,ca6727ab-9c8c-4fb7-8b7a-d6f0adf8dfa1,dcb6e295-b4ac-4121-9c1f-6abb46b5574b,2023-10-02,Instagram,Comment,Positive
187,c2c93273-8204-4385-8dd5-a277dc51989f,5e48a056-c6e1-480b-9afe-4a90ac1f687b,2023-11-02,Twitter,Comment,Neutral
193,885582df-3468-44c9-b92d-ea9d8396b962,433aeba5-746b-4ccd-8bae-42eb80203955,2023-07-11,Facebook,Share,NaN
205,999ad741-dfd2-46fe-afcb-7d1a3347c5c1,f23b6e7a-69c4-456a-9fec-2d8ecc97a655,2024-03-16,Twitter,Comment,Negative
229,52aafd4c-f409-4dac-a4d3-92d3d40b2f06,8c80b1c4-379e-4491-8c32-85f55dc0193e,2023-07-22,Facebook,Share,NaN
274,f95546c1-e96f-486a-ab84-ebb048198b4e,fbefe509-2379-4b99-89e4-5fc1f4fdafb9,2024-01-30,Instagram,Like,Negative
280,12dc6fed-c847-4040-93a1-dd00eb7ccbc0,9c56ffce-209f-48fc-b3ac-1c3840c83029,2023-09-18,Facebook,Share,Negative
287,87b396df-5a80-447a-8bb5-4dbcec4f9a07,284f6b6e-5b18-4171-bb04-6e316a99efdc,2023-08-13,Facebook,Share,Positive
319,14ae708b-187e-4848-8371-b452194722af,aad82a8f-9068-4a02-af7d-cbf94ac9bb11,2024-01-07,Instagram,Share,Negative

### Identifier Duplicate Verification

Identifier fields are reviewed separately from exact duplicate rows.

`CustomerID` may legitimately appear multiple times in the transaction and
social media datasets because one customer can have multiple transactions
or interactions.

`TransactionID` and `InteractionID` are expected to identify individual
records. Repeated values in these fields therefore require closer
inspection.

In [ ]:
# Check identifier duplicates

print(
    "Duplicate CustomerID values in Customer Demographics:",
    demographics_raw["CustomerID"].duplicated().sum()
)

print(
    "Duplicate TransactionID values:",
    transactions_raw["TransactionID"].duplicated().sum()
)

print(
    "Duplicate InteractionID values:",
    social_raw["InteractionID"].duplicated().sum()
)

Duplicate CustomerID values in Customer Demographics: 200
Duplicate TransactionID values: 200
Duplicate InteractionID values: 200

In [ ]:
print("Duplicate CustomerID Records in Demographics")
display(
    demographics_raw[
        demographics_raw["CustomerID"].duplicated(keep=False)
    ].sort_values("CustomerID").head(50)
)

print("\nDuplicate TransactionID Records")
display(
    transactions_raw[
        transactions_raw["TransactionID"].duplicated(keep=False)
    ].sort_values("TransactionID").head(50)
)

print("\nDuplicate InteractionID Records")
display(
    social_raw[
        social_raw["InteractionID"].duplicated(keep=False)
    ].sort_values("InteractionID").head(50)
)

Duplicate CustomerID Records in Demographics

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
3039,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
2559,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
1511,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
3169,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
3061,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
1105,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
2409,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09
3024,08995799-8d0f-40d6-986b-452074709b5f,61.0,Male,New Lukeville,Medium,2020-03-28
1536,08995799-8d0f-40d6-986b-452074709b5f,61.0,Male,New Lukeville,Medium,15/11/2019
886,09c0c7b1-2af9-4485-a602-d49c6cdcf2d0,31.0,Female,New Patricktown,Low,2023-06-20
3088,09c0c7b1-2af9-4485-a602-d49c6cdcf2d0,31.0,Female,New Patricktown,Low,2023-06-20
3107,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
2906,0ab0e741-f4ad-4d82-92c4-b5055b5c5549,26.0,Male,South Robertberg,NaN,2019-07-14
3001,0b5275cc-0b6c-4451-ac40-469e74c35f00,33.0,Female,Port Aliceton,High,2024-05-09
1318,0b5275cc-0b6c-4451-ac40-469e74c35f00,33.0,Female,Port Aliceton,High,2024-05-09
3109,0b78455d-7ecd-41c3-953b-4c883ce336f1,26.0,Male,Lake Crystal,Medium,2022-09-11
2075,0b78455d-7ecd-41c3-953b-4c883ce336f1,26.0,Male,Lake Crystal,Medium,2022-09-11
1693,0c68dabb-b818-43bf-96de-e0b384ace943,54.0,Male,North Samuelborough,High,2024-01-08
3125,0c68dabb-b818-43bf-96de-e0b384ace943,54.0,Male,North Samuelborough,High,2024-01-08
381,0d1d1b53-3a9d-4be9-9857-371dc98aba1e,57.0,Female,New Tylerfurt,Low,2024-06-12
3056,0d1d1b53-3a9d-4be9-9857-371dc98aba1e,57.0,Female,New Tylerfurt,Low,2024-06-12
3184,0d27aeb2-f8d0-4221-a74f-17f02a290943,22.0,Male,Gibbsmouth,High,2021-12-31
513,0d27aeb2-f8d0-4221-a74f-17f02a290943,22.0,Male,Gibbsmouth,High,2021-12-31
2889,0d2cf4cd-88a9-4d71-8ed7-0f70b450e4d2,NaN,Female,Paulside,Medium,2024-03-31
3179,0d2cf4cd-88a9-4d71-8ed7-0f70b450e4d2,NaN,Female,Paulside,Medium,2024-03-31
3071,0e663785-6555-49a9-ac34-ea04406b1ba5,65.0,Male,Lake Kristen,Low,2021-02-23
1916,0e663785-6555-49a9-ac34-ea04406b1ba5,65.0,Male,Lake Kristen,Low,2021-02-23
3151,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,60.0,Male,Port Tyler,High,2023-02-05
1608,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,60.0,Male,Port Tyler,High,2023-02-05
3197,0ede97d1-bb46-452d-893e-b63f37da4fa8,NaN,Female,North Christinaport,High,2021-10-16
2360,0ede97d1-bb46-452d-893e-b63f37da4fa8,NaN,Female,North Christinaport,High,2021-10-16
2321,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3196,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3038,1044f1f4-cce8-4bcb-9615-150b05a3cf5e,57.0,Male,Hallburgh,Medium,2020-02-10
2076,1044f1f4-cce8-4bcb-9615-150b05a3cf5e,57.0,Male,Hallburgh,Medium,2020-02-10
1550,1a5115af-2fa7-4198-b838-be2cdeccb768,68.0,Female,Taylorberg,High,2021-09-01
3114,1a5115af-2fa7-4198-b838-be2cdeccb768,68.0,Female,Taylorberg,High,2021-09-01
3108,1c4c3ec8-256e-4c2c-bed6-cf5e97e076de,NaN,Male,New Amber,Low,2023-04-10
159,1c4c3ec8-256e-4c2c-bed6-cf5e97e076de,NaN,Male,New Amber,Low,2023-04-10
3191,1d26a8ed-88ca-4806-9ec1-7db7ee6a748f,32.0,Female,East Cindy,NaN,2020-01-25
2644,1d26a8ed-88ca-4806-9ec1-7db7ee6a748f,32.0,Female,East Cindy,NaN,2020-01-25
3160,1d29565d-2123-4b85-b499-92a928a5fd2e,26.0,Male,East Stephanieton,High,2019-07-27
2485,1d29565d-2123-4b85-b499-92a928a5fd2e,26.0,Male,East Stephanieton,High,2019-07-27
206,1e2be761-bca8-4962-a270-7fc433d2179e,68.0,Female,East Ericmouth,Low,2023-11-26
3040,1e2be761-bca8-4962-a270-7fc433d2179e,68.0,Female,East Ericmouth,Low,2023-11-26
3042,1e659a88-5f9d-4c17-9739-1b3d30470928,68.0,Male,New Amberberg,High,2021-07-15
467,1e659a88-5f9d-4c17-9739-1b3d30470928,68.0,Male,New Amberberg,High,2021-07-15
304,1e9e7dcb-e612-46d3-bae6-0c2f47fa0220,44.0,Female,Brianmouth,Medium,2022-07-28
3085,1e9e7dcb-e612-46d3-bae6-0c2f47fa0220,44.0,Female,Brianmouth,Medium,07/11/2019

Duplicate TransactionID Records

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
3010,42d3c5b0-ec77-4567-b66c-449783077049,02221793-d5ba-4064-99d8-33c1b6722278,2023-10-03,911.51,Electronics,Credit Card
1347,42d3c5b0-ec77-4567-b66c-449783077049,02221793-d5ba-4064-99d8-33c1b6722278,2023-10-03,911.51,Electronics,Credit Card
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3131,9ecddfde-5bba-42c0-b4a4-8eb1b8f87c17,02747865-0adb-4e26-be16-078b8e38dcde,2022-08-30,627.83,NaN,Credit Card
2360,9ecddfde-5bba-42c0-b4a4-8eb1b8f87c17,02747865-0adb-4e26-be16-078b8e38dcde,2022-08-30,627.83,NaN,Credit Card
282,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
3127,b10dbfea-ac81-4cdf-be3c-62248bbd5838,02a36fd6-8d10-4179-8b84-f011e8551a64,2024-06-02,NaN,Health & Beauty,Debit Card
3015,4090ba85-b111-4f75-a792-c777965f5255,04edc4fc-1565-4a82-af75-5b5caacaa9c4,2024-06-27,138.72,Home & Garden,Bank Transfer
767,4090ba85-b111-4f75-a792-c777965f5255,04edc4fc-1565-4a82-af75-5b5caacaa9c4,2024-06-27,138.72,Home & Garden,Bank Transfer
3036,e7c7f991-9b89-485f-b2e1-216ac5c661a0,06c3e20f-8aec-446a-9153-cd00a88ac1e2,2022-12-23,NaN,Clothing,Bank Transfer
671,e7c7f991-9b89-485f-b2e1-216ac5c661a0,06c3e20f-8aec-446a-9153-cd00a88ac1e2,2022-12-23,NaN,Clothing,Bank Transfer
3082,14845984-5bef-45d5-9c6a-daf55f287206,07e0737c-4e9f-4dc2-b22f-ed313498618e,2022-12-02,921.15,Home & Garden,Bank Transfer
2384,14845984-5bef-45d5-9c6a-daf55f287206,07e0737c-4e9f-4dc2-b22f-ed313498618e,2022-12-02,921.15,Home & Garden,Bank Transfer
3183,a8f82019-5586-46dc-87b2-3660e80ecd7d,09c6ac4d-2da0-4d56-8765-8c5cb8861997,2024-01-16,678.55,Clothing,Debit Card
672,a8f82019-5586-46dc-87b2-3660e80ecd7d,09c6ac4d-2da0-4d56-8765-8c5cb8861997,2024-01-16,678.55,Clothing,Debit Card
553,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,0ab4fdfb-03fe-4872-a26e-3835ed0638b7,2023-03-23,832.45,Electronics,Credit Card
3143,49f06ea9-4ae5-4ce5-98ce-d2c2f6f15cbd,0ab4fdfb-03fe-4872-a26e-3835ed0638b7,2023-03-23,832.45,Electronics,Credit Card
3085,473f3b1f-2e0e-40a6-8917-b3aac5296a01,0b6aeade-745e-4ea7-bf67-d611199d2de8,2023-07-03,NaN,Health & Beauty,Credit Card
568,473f3b1f-2e0e-40a6-8917-b3aac5296a01,0b6aeade-745e-4ea7-bf67-d611199d2de8,2023-07-03,NaN,Health & Beauty,Credit Card
3112,6712eba4-a966-46a5-8f52-26f53054787d,0bf31263-c0df-48bf-8b75-8f9c06ef76c9,2022-10-31,12.67,Health & Beauty,PayPal
2537,6712eba4-a966-46a5-8f52-26f53054787d,0bf31263-c0df-48bf-8b75-8f9c06ef76c9,2022-10-31,12.67,Health & Beauty,PayPal
3031,6cc1eaef-8496-4485-af7a-9812ccdac060,0e20b19b-3dce-4e1e-86ec-2d1b6494d3fb,2023-01-19,480.72,Home & Garden,PayPal
1547,6cc1eaef-8496-4485-af7a-9812ccdac060,0e20b19b-3dce-4e1e-86ec-2d1b6494d3fb,2023-01-19,480.72,Home & Garden,PayPal
1090,937245e3-10c3-446d-ab02-f916fb556395,0f688fb0-8858-4b50-9582-67d5e84baf3f,2023-08-18,538.73,Health & Beauty,Credit Card
3142,937245e3-10c3-446d-ab02-f916fb556395,0f688fb0-8858-4b50-9582-67d5e84baf3f,2023-08-18,538.73,Health & Beauty,Credit Card
65,a0db86bf-0c2d-4c9e-8d3b-f5b33ac37cee,1048e98c-90fd-4cef-ba62-eb4b16816596,2023-09-08,596.73,Clothing,Credit Card
3122,a0db86bf-0c2d-4c9e-8d3b-f5b33ac37cee,1048e98c-90fd-4cef-ba62-eb4b16816596,2023-09-08,596.73,Clothing,Credit Card
2002,779e8498-ec27-4741-86f0-1f0d696c7ea8,12d80278-2d5f-42f1-9bad-a693f60021ca,2022-11-14,818.52,Automotive,Debit Card
3090,779e8498-ec27-4741-86f0-1f0d696c7ea8,12d80278-2d5f-42f1-9bad-a693f60021ca,2022-11-14,818.52,Automotive,Debit Card
3138,cb92abec-3e14-4c2d-b8a7-265082126081,13b8346a-73ab-4000-8874-0d6d42673779,2024-01-05,458.74,Automotive,Bank Transfer
2920,cb92abec-3e14-4c2d-b8a7-265082126081,13b8346a-73ab-4000-8874-0d6d42673779,2024-01-05,458.74,Automotive,Bank Transfer
2049,3961c9cd-9e5c-45b4-9d85-7614fd1b8323,14835627-7769-4c4c-81fc-21555e24662b,2023-05-04,182.33,Automotive,Credit Card
3155,3961c9cd-9e5c-45b4-9d85-7614fd1b8323,14835627-7769-4c4c-81fc-21555e24662b,2023-05-04,182.33,Automotive,Credit Card
3185,c98edfc3-4819-4b2b-9af8-281ada990517,1567faf6-33bd-4cf8-b9e7-29030d0f62b5,2022-10-19,950.76,Electronics,Debit Card
1617,c98edfc3-4819-4b2b-9af8-281ada990517,1567faf6-33bd-4cf8-b9e7-29030d0f62b5,2022-10-19,950.76,Electronics,Debit Card
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal
1029,88c11bb5-495a-4fa4-9dca-ba16c044b52f,186b48d2-9ec6-4df1-a0ca-0dd1b42a0906,2024-05-16,320.91,Home & Garden,PayPal
3137,88c11bb5-495a-4fa4-9dca-ba16c044b52f,186b48d2-9ec6-4df1-a0ca-0dd1b42a0906,2024-05-16,320.91,Home & Garden,PayPal
278,6bc3aaad-57cc-4fae-b57f-18faa88ce95b,191af024-d4d3-4144-86f7-11e09e4e9df8,2023-02-14,185.97,NaN,Debit Card
3129,6bc3aaad-57cc-4fae-b57f-18faa88ce95b,191af024-d4d3-4144-86f7-11e09e4e9df8,2023-02-14,185.97,NaN,Debit Card
3178,3d8408ab-60f2-465f-a112-d6b7747c4a4a,196808c5-fda0-4ede-ae6d-05d2a717a9cc,2023-10-19,745.76,Electronics,PayPal
611,3d8408ab-60f2-465f-a112-d6b7747c4a4a,196808c5-fda0-4ede-ae6d-05d2a717a9cc,2023-10-19,745.76,Electronics,PayPal
3027,df8efbc2-afb8-4036-b764-ec5d26891ca3,1a48c38d-43c7-4db8-a3a0-29f6ce5a46d2,2022-09-06,970.59,Clothing,Credit Card
663,df8efbc2-afb8-4036-b764-ec5d26891ca3,1a48c38d-43c7-4db8-a3a0-29f6ce5a46d2,2022-09-06,970.59,Clothing,Credit Card
2486,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1ba56db2-dfa9-4689-b5fa-256edb792769,2023-11-08,185.14,Electronics,Credit Card
3165,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1ba56db2-dfa9-4689-b5fa-256edb792769,2023-11-08,185.14,Electronics,Credit Card
2029,28c29c18-0cbe-40ea-b218-a96430cc4409,1c2f49aa-1e1c-4ada-b021-699f68190652,2023-10-19,NaN,NaN,PayPal
3190,28c29c18-0cbe-40ea-b218-a96430cc4409,1c2f49aa-1e1c-4ada-b021-699f68190652,2023-10-19,NaN,NaN,PayPal

Duplicate InteractionID Records

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
2511,5db2e5ed-d30c-45db-b5f1-9db8008e178b,012dbb2a-3fbe-4b98-aa69-0304704db3c2,2024-05-26,NaN,Comment,Neutral
3176,5db2e5ed-d30c-45db-b5f1-9db8008e178b,012dbb2a-3fbe-4b98-aa69-0304704db3c2,2024-05-26,NaN,Comment,Neutral
1820,2ad7dcee-ed9c-4a7f-b631-377268bc623b,019fe9c3-83c6-49e4-b827-5ddd614c72df,2024-03-14,Instagram,Comment,Positive
3088,2ad7dcee-ed9c-4a7f-b631-377268bc623b,019fe9c3-83c6-49e4-b827-5ddd614c72df,2024-03-14,Instagram,Comment,Positive
3005,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,2024-03-20,Instagram,Like,Positive
374,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,29/04/2024,Instagram,Like,Positive
3118,0c298fc3-6e30-4478-bc30-f1b56b2e655d,020837db-5783-4ac9-9955-1ace5175a1a0,2023-07-05,Facebook,Share,Positive
1051,0c298fc3-6e30-4478-bc30-f1b56b2e655d,020837db-5783-4ac9-9955-1ace5175a1a0,2023-07-05,Facebook,Share,Positive
2604,4a75d71b-1263-43c3-9533-a0b94f50fee0,02fe2369-cc53-4053-b8c3-5c29f98087dc,2023-09-19,Twitter,Comment,Neutral
3079,4a75d71b-1263-43c3-9533-a0b94f50fee0,02fe2369-cc53-4053-b8c3-5c29f98087dc,2023-09-19,Twitter,Comment,Neutral
3057,fe4eace1-a485-45b5-827f-d8a3dfe9d92d,03be50b0-ca8f-4e86-8c12-eb8b184ef3db,2023-08-24,Instagram,Like,Positive
138,fe4eace1-a485-45b5-827f-d8a3dfe9d92d,03be50b0-ca8f-4e86-8c12-eb8b184ef3db,2023-08-24,Instagram,Like,Positive
3093,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Very Positive
2183,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Negative
1036,e36847ec-fbf2-4270-937c-a010c528fba4,045907ef-9e87-463e-aeb0-0945389a9aed,2023-12-08,Twitter,Comment,Negative
3145,e36847ec-fbf2-4270-937c-a010c528fba4,045907ef-9e87-463e-aeb0-0945389a9aed,2023-12-08,Twitter,Comment,Negative
3161,9207fa75-5758-48d1-94ad-19c041e0520f,0626cfe9-8e7f-4b19-ba9b-21330cd007c8,2024-01-11,Instagram,Comment,Negative
1495,9207fa75-5758-48d1-94ad-19c041e0520f,0626cfe9-8e7f-4b19-ba9b-21330cd007c8,2024-01-11,Instagram,Comment,Negative
2532,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Very Positive
3166,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
2276,407c3e47-8309-4423-a2bb-e025b3239745,07d509dd-d0bf-4f26-942a-704bada6c5f2,2024-06-18,Instagram,Share,Negative
3006,407c3e47-8309-4423-a2bb-e025b3239745,07d509dd-d0bf-4f26-942a-704bada6c5f2,2024-06-18,Instagram,Share,Negative
3077,c448b2f5-80a5-4fde-8144-8bea32bc3618,08c54ea6-22b6-4d42-940e-feffcc4789f5,2023-10-06,Instagram,Comment,Negative
2102,c448b2f5-80a5-4fde-8144-8bea32bc3618,08c54ea6-22b6-4d42-940e-feffcc4789f5,2023-10-06,Instagram,Comment,Negative
2490,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,2024-06-14,Twitter,Comment,Negative
3084,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,24/01/2024,Twitter,Comment,Negative
3083,b77c0398-2ff6-41e6-9ebf-410290baadc8,09d5cb02-7504-4c49-8a1e-c98870703b4a,2023-08-14,Twitter,Comment,Negative
2012,b77c0398-2ff6-41e6-9ebf-410290baadc8,09d5cb02-7504-4c49-8a1e-c98870703b4a,2023-08-14,Twitter,Comment,Negative
3015,4e2d8d82-8597-4dcb-85b6-c530f56d708a,0bff96d5-5986-415c-818f-db7d237cb055,2024-06-14,Twitter,Like,Negative
1009,4e2d8d82-8597-4dcb-85b6-c530f56d708a,0bff96d5-5986-415c-818f-db7d237cb055,2024-06-14,Twitter,Like,Negative
3039,36656b2c-c7ad-4c3e-b2f3-c9d7beb78aec,0f41d074-2cac-45be-8e7e-0b673770fadd,2023-11-04,Instagram,Share,Positive
2207,36656b2c-c7ad-4c3e-b2f3-c9d7beb78aec,0f41d074-2cac-45be-8e7e-0b673770fadd,2023-11-04,Instagram,Share,Positive
1958,1e061351-11f3-470c-905f-60f244516c43,11cd820a-55b0-4b04-aa37-12867aaf8b30,2024-05-23,Twitter,Share,Neutral
3140,1e061351-11f3-470c-905f-60f244516c43,11cd820a-55b0-4b04-aa37-12867aaf8b30,2024-05-23,Twitter,Share,Neutral
3108,eaa372ee-4574-43db-adb8-8bb3e92226e1,1320e6eb-ee34-404e-be28-46d006491dd3,2023-12-18,Facebook,Share,Negative
2971,eaa372ee-4574-43db-adb8-8bb3e92226e1,1320e6eb-ee34-404e-be28-46d006491dd3,2023-12-18,Facebook,Share,Negative
3062,243a5ccd-31c3-440d-a3ad-73d3972dd39d,13afaba5-234a-484d-adb7-a56992e76497,2023-10-31,NaN,Comment,Negative
1225,243a5ccd-31c3-440d-a3ad-73d3972dd39d,13afaba5-234a-484d-adb7-a56992e76497,2023-10-31,NaN,Comment,Negative
2135,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,2023-07-28,Instagram,Like,Positive
3017,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,04/06/2024,Instagram,Like,Positive
3131,e8621a96-7c59-4079-88b1-b6ebd790f1b6,1507787c-51d8-48eb-a9ab-0c2395268bd1,2023-09-27,NaN,Comment,Neutral
2806,e8621a96-7c59-4079-88b1-b6ebd790f1b6,1507787c-51d8-48eb-a9ab-0c2395268bd1,2023-09-27,NaN,Comment,Neutral
1298,decfbb11-2324-4a91-b4a4-da3011046f88,1508cbeb-ec4f-4ea2-84d3-023e511395e7,2024-06-28,Facebook,Like,Positive
3010,decfbb11-2324-4a91-b4a4-da3011046f88,1508cbeb-ec4f-4ea2-84d3-023e511395e7,2024-06-28,Facebook,Like,Positive
3011,1904daec-e2bf-4b0b-854c-baaf9e4df3b7,17c5788c-38c1-4744-ad8f-1ab1670e8d46,2024-04-15,Facebook,Comment,Negative
2091,1904daec-e2bf-4b0b-854c-baaf9e4df3b7,17c5788c-38c1-4744-ad8f-1ab1670e8d46,2024-04-15,Facebook,Comment,Negative
406,56f11a95-76f1-4a97-b38f-db1dc95da1ed,193c2897-e674-46da-a389-c68e45b6a68b,2024-01-13,Facebook,Comment,Negative
3001,56f11a95-76f1-4a97-b38f-db1dc95da1ed,193c2897-e674-46da-a389-c68e45b6a68b,2024-01-13,Facebook,Comment,Negative
1487,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Negative
3130,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Very Negative

In [ ]:
print(
    "Unique customers in Customer Demographics:",
    demographics_raw["CustomerID"].nunique()
)

print(
    "Unique customers in Customer Transactions:",
    transactions_raw["CustomerID"].nunique()
)

print(
    "Unique customers in Social Media Interactions:",
    social_raw["CustomerID"].nunique()
)

Unique customers in Customer Demographics: 3000
Unique customers in Customer Transactions: 1871
Unique customers in Social Media Interactions: 1893

In [ ]:
from IPython.display import Markdown, display

demo_exact_duplicates = demographics_raw.duplicated().sum()
transaction_exact_duplicates = transactions_raw.duplicated().sum()
social_exact_duplicates = social_raw.duplicated().sum()

demo_customer_duplicates = demographics_raw["CustomerID"].duplicated().sum()
transaction_id_duplicates = transactions_raw["TransactionID"].duplicated().sum()
interaction_id_duplicates = social_raw["InteractionID"].duplicated().sum()

display(Markdown(f"""
### Duplicate Verification Observation

The duplicate verification produced the following results:

#### Customer Demographics
- Exact duplicate rows: **{demo_exact_duplicates}**
- Duplicate CustomerID values: **{demo_customer_duplicates}**

#### Customer Transactions
- Exact duplicate rows: **{transaction_exact_duplicates}**
- Duplicate TransactionID values: **{transaction_id_duplicates}**

#### Social Media Interactions
- Exact duplicate rows: **{social_exact_duplicates}**
- Duplicate InteractionID values: **{interaction_id_duplicates}**

Repeated CustomerID values in the transaction and social media datasets are
not treated as duplicate errors by themselves because one customer may
legitimately have multiple transactions or social media interactions.

No duplicate records have been removed at this stage.
"""))

### Duplicate Verification Observation

The duplicate verification produced the following results:

#### Customer Demographics
- Exact duplicate rows: **177**
- Duplicate CustomerID values: **200**

#### Customer Transactions
- Exact duplicate rows: **185**
- Duplicate TransactionID values: **200**

#### Social Media Interactions
- Exact duplicate rows: **180**
- Duplicate InteractionID values: **200**

Repeated CustomerID values in the transaction and social media datasets are
not treated as duplicate errors by themselves because one customer may
legitimately have multiple transactions or social media interactions.

No duplicate records have been removed at this stage.

### Numeric Value Verification

Variables that are expected to contain numeric information are reviewed
before data type conversion.

The FinMark datasets contain two primary numeric variables:

- `Age` in the Customer Demographics dataset
- `Amount` in the Customer Transactions dataset

Because these columns were initially imported as `object`, their values
must first be checked for non-numeric entries, negative values, zero values,
and potentially unrealistic values.

Temporary numeric versions of the columns will be created for verification.
The original raw datasets will not be modified during this step.

In [ ]:
# Create a temporary numeric version of Age

age_numeric = pd.to_numeric(
    demographics_raw["Age"],
    errors="coerce"
)

# Identify original non-null values that failed numeric conversion

invalid_age_mask = (
    demographics_raw["Age"].notna()
    & age_numeric.isna()
)

invalid_age_values = demographics_raw.loc[
    invalid_age_mask,
    ["CustomerID", "Age"]
]

print("Non-numeric Age records:", len(invalid_age_values))

display(invalid_age_values.head(20))

Non-numeric Age records: 34

                                CustomerID      Age
85    9bd23b55-cbc0-4082-ae18-916ea8895c07  Unknown
233   c1805670-0d42-4583-bfda-646f85252829  Unknown
240   e9c58327-25a1-4148-8c41-f0f37fc0c75d  Unknown
261   a3efade0-9841-40a8-9c00-0968581d608a  Unknown
312   2cbc0b12-8048-4624-8149-0c9cd0920e35  Unknown
338   48313b18-ccdb-4946-b958-1ebfc92dcc2a  Unknown
458   f7f5463e-6069-4ee0-8168-d3ebd6142553  Unknown
525   658c09ee-ffab-4a46-b971-af23b5b5da0e  Unknown
554   684e0f75-2c90-424b-ae2a-0a669b799215  Unknown
625   70bc6d41-b25a-4041-a3ca-9215f887359b  Unknown
681   5819025b-3df7-4da6-a8bd-5d980e61c5a4  Unknown
828   db354959-55a3-4dbd-aa69-2c0885adb268  Unknown
1266  2f736c67-3ae7-404c-9ea3-bda4b6662844  Unknown
1355  76c1d696-0f1c-44b5-b749-8859545658eb  Unknown
1377  3341628f-8548-4ae7-9000-ec20c5973e5a  Unknown
1496  823ace47-e265-4808-b0c3-f40fb41bf5de  Unknown
1544  e1f9dff8-fef5-49c4-b14b-c31bc3d61cc6  Unknown
1593  841fc557-ff70-4d45-8b0d-5be6f58d794d  Unknown
1674  fcf17e99-1608-4711-bad6-fb435f8aa621  Unknown
1726  6ee69819-b275-4409-93d0-b62be6a7146a  Unknown

#### Non-Numeric Age Values

The distinct values that failed numeric conversion are reviewed to determine
whether the issue results from inconsistent text entries, formatting
problems, or unusable values.

No replacement or removal decision is made at this stage.

In [ ]:
print("Invalid Age Values")

display(
    demographics_raw.loc[
        invalid_age_mask,
        "Age"
    ].value_counts(dropna=False)
)

Invalid Age Values

Age
Unknown    34
Name: count, dtype: int64

#### Age Range Review

Successfully converted age values are summarized to identify their minimum,
maximum, and overall distribution.

Extreme values are investigated because successful numeric conversion does
not automatically mean that a value is logically valid.

In [ ]:
display(
    age_numeric.describe()
)

count    2875.000000
mean       45.325565
std        19.503218
min        -1.000000
25%        31.000000
50%        45.000000
75%        58.000000
max       150.000000
Name: Age, dtype: float64

#### Questionable Age Values

Age values below 0 or above 120 are flagged for investigation.

These boundaries are used only as a practical data-quality check to identify
potentially unrealistic values. Records are not removed automatically based
on this condition during verification.

In [ ]:
questionable_age_mask = (
    (age_numeric < 0)
    | (age_numeric > 120)
)

questionable_age_records = demographics_raw.loc[
    questionable_age_mask,
    ["CustomerID", "Age"]
]

print(
    "Questionable numeric Age records:",
    len(questionable_age_records)
)

display(questionable_age_records.head(20))

Questionable numeric Age records: 63

                               CustomerID   Age
10   c96a5ee9-f1a6-416a-adc6-1c8b128c7399   150
48   b1d6a46b-214c-4592-9688-82d0fd977bb2   150
64   52303d17-9d24-4c20-89e3-7bcfa92140c9   150
72   7a461a97-18fd-4686-ab3f-adaded72069d   150
99   5ba7a03b-0d2f-4fc3-bd36-7a675c1ac61e   150
190  0dd7e84b-0aa4-4883-8bda-447e31b595d5   150
219  89432125-8fd0-4b2a-a3c6-4f2e6f8ddc64   150
291  6cd7a734-a51d-4a11-ba1c-00c49d9a4490    -1
308  c0d8e0be-02a4-45c0-89c3-3ff31e60b4f7  -1.0
314  4584583e-9825-4aa4-81ac-d6879195853f   150
348  8880506d-dbb6-42ea-98c3-c0b7454c04bb   150
400  aaca0879-8a14-41a4-8385-b1bfd3f97653    -1
539  50465bde-6a9a-466d-804a-a8f046809a23    -1
690  52f2132d-b2bf-4c09-9bdf-2d634ea7ebca    -1
745  999ad741-dfd2-46fe-afcb-7d1a3347c5c1   150
750  f1f5c413-2160-4dac-97e1-be254637d804   150
772  57dbd7f5-3428-4452-82f8-0c140234a864   150
783  e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e    -1
798  b07eb18e-8b83-4ec1-b0cf-ec3e5cfbd799   150
806  a4a6c9aa-bbbf-4155-9100-4f770078551d    -1

#### Age Validation Summary

The results of the Age verification are summarized to distinguish between
missing values, non-numeric values, and questionable numeric values.

These categories may require different cleaning decisions later.

In [ ]:
age_validation_summary = pd.DataFrame({
    "Check": [
        "Total Records",
        "Missing Age",
        "Non-Numeric Age",
        "Questionable Numeric Age"
    ],
    "Count": [
        len(demographics_raw),
        demographics_raw["Age"].isnull().sum(),
        invalid_age_mask.sum(),
        questionable_age_mask.sum()
    ]
})

display(age_validation_summary)

                      Check  Count
0             Total Records   3200
1               Missing Age    291
2           Non-Numeric Age     34
3  Questionable Numeric Age     63

#### Transaction Amount Validation

The `Amount` variable is expected to contain numeric transaction values.

A temporary numeric conversion is used to identify entries that cannot be
interpreted as numbers while preserving the original raw transaction data.

In [ ]:
# Create a temporary numeric version of Amount

amount_numeric = pd.to_numeric(
    transactions_raw["Amount"],
    errors="coerce"
)

# Identify original non-null values that failed conversion

invalid_amount_mask = (
    transactions_raw["Amount"].notna()
    & amount_numeric.isna()
)

invalid_amount_values = transactions_raw.loc[
    invalid_amount_mask,
    ["TransactionID", "CustomerID", "Amount"]
]

print(
    "Non-numeric Amount records:",
    len(invalid_amount_values)
)

display(invalid_amount_values.head(20))

Non-numeric Amount records: 30

,TransactionID,CustomerID,Amount
5,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,Free
59,611876da-a85d-4969-8d84-7a9cf8ddbf59,04b0cd53-29ca-48ef-b4b7-9520a2939288,Free
161,b7e042d1-7ad0-430d-8984-82dfa9048a64,56058449-276a-417e-b6c6-f8853b1d2659,Free
250,cd29e076-8de9-416b-bc0e-fecb61c8baff,7e3256b2-49d1-419e-a30c-8504f446e64e,Free
432,36d14454-fb95-4b19-a574-e137ddb55528,ccf4d58b-5087-45c8-a8f8-bb99be9a13d1,Free
755,a7e2384a-9efb-4519-aa01-683daa01d6e9,1fbbc3ad-d48f-4e64-9ef7-4e58277af29a,Free
764,983162b4-b06e-41d3-956c-2c3eed3cf6c4,e06f0e16-8e48-483b-b103-9f105b139ca8,Free
786,f9cdb10b-2e40-4df2-a7c4-3614151587b6,481bcc62-9dcb-4766-bbdd-79f5554d73f8,Free
853,519f279a-5e5d-4a98-8a28-6c04e66c62b7,77280a9d-3fc9-4140-bc4e-b85cd5c7a8b1,Free
854,87459f1a-8873-450f-8b7d-ac4c7b41ba90,68afa4cc-e2d5-4150-b358-2e14e7508721,Free
1008,49fd3057-88b4-4896-bf5b-2e501b76df5b,8f440758-f8ac-44ee-9f83-51d9bde6d101,Free
1041,8b7c550f-4acc-4333-a144-cc4d75aa8d1a,2de49c7c-32ae-4ba8-b058-622a090d7094,Free
1179,a6ea336a-46dd-480a-9dff-232bc67e956c,9f9f72a5-0ec8-4847-ab9c-d7694d86f53a,Free
1214,46dbc70f-3b20-4e27-8af2-a58801d78774,13b1dad8-724d-45e8-9ecd-912d09e4931c,Free
1215,66f81587-2823-40f4-9f67-a51c4fb3b603,4231fa1b-073c-4bf2-94d6-22dd9dd33929,Free
1267,200d7d2e-ec9e-4152-865e-0e4099006397,b791d365-bf14-43ae-9939-aabd2c982866,Free
1310,8c8b85f2-5e6e-457a-899d-6c4b392d2239,321adc94-8a35-4998-bc17-0cacc00988f4,Free
1460,3e221ee0-a001-4fa5-ba4e-c3ca8f381ee8,ee802844-8070-4699-b60d-3568a7d306b6,Free
1534,fc58b548-8913-4fb9-a952-9f6edee9d011,99462720-beca-4890-852e-79d16990f055,Free
1748,00816003-b5ea-4564-a8f6-d25b9e44bbcf,69c0971b-1c85-429a-aa61-496f9c0a4410,Free

#### Non-Numeric Transaction Amounts

Distinct transaction amount values that fail numeric conversion are reviewed.

These values must be examined before cleaning because a non-numeric entry
may represent invalid data, a special transaction condition, or an
inconsistent data-entry format.

No assumptions are made about their intended monetary value during
verification.

In [ ]:
print("Invalid Amount Values")

display(
    transactions_raw.loc[
        invalid_amount_mask,
        "Amount"
    ].value_counts(dropna=False)
)

Invalid Amount Values

Amount
Free    30
Name: count, dtype: int64

#### Transaction Amount Range Review

Successfully converted transaction amounts are summarized to identify their
range and distribution.

Negative and zero transaction amounts are reviewed separately because they
may represent errors or special transaction conditions that cannot be
determined from numeric conversion alone.

In [ ]:
display(
    amount_numeric.describe()
)

count    2866.000000
mean      490.916479
std       298.737439
min      -100.000000
25%       228.240000
50%       497.285000
75%       746.935000
max       999.860000
Name: Amount, dtype: float64

#### Negative and Zero Amount Review

Negative and zero transaction amounts are counted and reviewed separately.

These values are not automatically removed because their meaning must first
be evaluated before a cleaning decision is made.

In [ ]:
negative_amount_mask = amount_numeric < 0
zero_amount_mask = amount_numeric == 0

print(
    "Negative Amount records:",
    negative_amount_mask.sum()
)

print(
    "Zero Amount records:",
    zero_amount_mask.sum()
)

Negative Amount records: 40
Zero Amount records: 30

In [ ]:
print("Negative Transaction Amounts")

display(
    transactions_raw.loc[
        negative_amount_mask,
        [
            "TransactionID",
            "CustomerID",
            "Amount",
            "ProductCategory",
            "PaymentMethod"
        ]
    ].head(20)
)

print("\nZero Transaction Amounts")

display(
    transactions_raw.loc[
        zero_amount_mask,
        [
            "TransactionID",
            "CustomerID",
            "Amount",
            "ProductCategory",
            "PaymentMethod"
        ]
    ].head(20)
)

Negative Transaction Amounts

,TransactionID,CustomerID,Amount,ProductCategory,PaymentMethod
274,814d25d8-690b-45bb-96c9-b7a3e92a61db,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,-100,NaN,PayPal
319,fb908e24-4c1e-4e24-a1b0-62465fa0515c,b91999f9-b7ed-4da4-a285-1dafae98e21d,-100,Health & Beauty,Debit Card
334,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,a800ccba-e1ca-4f52-ad9f-14f3432699c9,-100,Clothing,Bank Transfer
381,f53b16b4-d042-44ca-a073-4acdd546b519,a94e3f55-2f0e-432e-8706-9815c4371376,-100,Home & Garden,PayPal
447,f35cadbe-6ae1-427d-8b41-5749cc1173e6,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,-100,Electronics,Bank Transfer
449,77954a26-9a04-4806-b525-7f33f554d255,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,-100,Home & Garden,Credit Card
476,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,ac6b4d61-3d14-4362-b226-8c0c5786d6df,-100,Health & Beauty,Credit Card
500,c59819cc-cf92-4929-ad22-ef3435187be9,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,-100,Automotive,Bank Transfer
563,f39c8b1d-595a-4656-8108-25981bf3fa14,f05ec030-ac96-417d-a73c-e3ca3adc1a30,-100,Electronics,Debit Card
652,f99eba1f-0092-4487-b753-9fce61e0ca26,f56e56b7-bbde-455c-b570-61cd2005b4e4,-100,Automotive,PayPal
702,64138a25-3a63-41fd-aa81-f74231597191,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,-100,Home & Garden,Debit Card
727,adbe44db-78ec-408b-80ad-e119e0f58123,db10c135-1080-4fce-b653-d5a5fb572fa8,-100,Home & Garden,Credit Card
1129,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,6b6cd86a-d0af-48ab-ada5-e596f726cffa,-100,Clothing,Credit Card
1240,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,-100,Home & Garden,Debit Card
1241,09b0508b-a705-48d0-8594-5b7d85d024eb,799943c7-3b71-4f24-9b16-c2fcaf9b3871,-100,Automotive,PayPal
1263,db154379-42a3-4ae0-a4d3-29c53226f8a1,38d746bd-c227-416a-aa28-610ffd379e58,-100,Electronics,Bank Transfer
1298,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,8375d38f-88e2-4c33-9647-f8b8b55b1426,-100.0,Health & Beauty,Bank Transfer
1577,6cfe5871-8524-4d81-abaa-a54fdd3c873d,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,-100,Automotive,PayPal
1705,084e56a5-99eb-48df-801e-bda9cd5ff591,f102f93b-f32c-41d3-adcc-25e02a67c34f,-100,Electronics,PayPal
1808,ab723d41-abdc-412b-b3b9-68796b746a8e,28097c07-e810-4e64-8eae-bff2abd81bc1,-100,Automotive,Credit Card

Zero Transaction Amounts

,TransactionID,CustomerID,Amount,ProductCategory,PaymentMethod
134,793af848-8138-40e7-929c-67254ea56ca7,b94a126b-755e-4ee1-91f6-c5f86ceef780,0,Home & Garden,PayPal
196,a6b7182d-6c74-4fa5-9491-035e49e5eb87,89480374-82ec-44e5-ae61-bbed82bfd5b1,0,Electronics,Bank Transfer
308,c0ea759c-a09f-4989-bc3b-f56a0c0400d8,343ef45e-c257-47f1-bbd2-5683734d2fcd,0,Home & Garden,PayPal
378,962df48f-faf1-4849-9779-0415f10cb9f3,88efac91-e005-417f-bc9e-57a5deb7f746,0,Home & Garden,Credit Card
468,8e88d564-a18a-448b-9e5d-add5fef8017d,ac6b4d61-3d14-4362-b226-8c0c5786d6df,0,Health & Beauty,PayPal
542,36db923e-7db3-4df0-b9c2-574410d62bba,667b0a6e-53b8-476d-be5b-215bfe49f60b,0,Electronics,Bank Transfer
580,88b6ba3b-5490-4374-ad90-cd45b1c94d4b,ebccb59b-1792-4a64-a43e-ac942685ec77,0,Clothing,Debit Card
591,0525dc48-b90b-4100-952a-fb163c51901c,2130fd89-6ba4-4f36-bb90-2327cf27d0d6,0,Automotive,Debit Card
629,652636b6-5c72-44e1-aefb-6adce412ee75,086370e7-8884-47d7-89b0-776401a43e1c,0,Electronics,Debit Card
931,35edcb11-2d5e-48ba-a1c2-8c16bbd3952a,b0180e7a-16e4-45bf-a417-0f2f5ca442bd,0,Clothing,Credit Card
1116,4044222b-4470-4e79-8f53-5bdba7066c44,013c4cd9-1d0f-4004-8772-065ab426d105,0,Electronics,PayPal
1228,721db31f-2972-4ff5-af51-87c8bb6360a3,34878e84-afed-4cb1-a969-08a070c6be85,0,Clothing,Debit Card
1484,b6d45beb-65a6-468e-a9d2-9d29deaff58d,a420497a-653c-4a0f-bdfa-32543a7a94f6,0,Automotive,Debit Card
1853,e31033dc-6e31-479f-bb56-e3e392b128d5,5713cca9-0ee4-45ef-a550-5edba478b94c,0,Home & Garden,Debit Card
1886,30bb2661-984e-4949-b821-923d76483d82,1d29565d-2123-4b85-b499-92a928a5fd2e,0,Automotive,Debit Card
2056,71b15f40-92c8-4acd-8c45-4a6f86e11665,b82ee981-f4ba-49e3-95de-49084a33db20,0.0,Clothing,Credit Card
2070,4281591f-d839-4c2a-aea2-5cec07eee005,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,0,Health & Beauty,PayPal
2109,2532b466-9d3e-4724-a5f4-b3295b4b8530,78002a64-8a6e-4d61-80a9-1bbf4c41ae76,0,Health & Beauty,PayPal
2166,287c98cd-4c3c-4c01-bc3f-fd2cdfb01d78,b8f3474f-d05d-4aca-982b-6af4a856305a,0,Clothing,PayPal
2256,b302b5d0-a182-48cd-bc3c-6afbbf4c72c2,cdd71e46-7539-41af-b9d5-6758abdfa2e6,0,Health & Beauty,Bank Transfer

#### Transaction Amount Validation Summary

The transaction amount review separates missing values, non-numeric entries,
negative amounts, and zero amounts.

These conditions are documented separately because they may require
different treatment during the cleaning phase.

In [ ]:
amount_validation_summary = pd.DataFrame({
    "Check": [
        "Total Records",
        "Missing Amount",
        "Non-Numeric Amount",
        "Negative Amount",
        "Zero Amount"
    ],
    "Count": [
        len(transactions_raw),
        transactions_raw["Amount"].isnull().sum(),
        invalid_amount_mask.sum(),
        negative_amount_mask.sum(),
        zero_amount_mask.sum()
    ]
})

display(amount_validation_summary)

                Check  Count
0       Total Records   3200
1      Missing Amount    304
2  Non-Numeric Amount     30
3     Negative Amount     40
4         Zero Amount     30

In [ ]:
from IPython.display import Markdown, display

age_missing = demographics_raw["Age"].isnull().sum()
age_non_numeric = invalid_age_mask.sum()
age_questionable = questionable_age_mask.sum()

amount_missing = transactions_raw["Amount"].isnull().sum()
amount_non_numeric = invalid_amount_mask.sum()
amount_negative = negative_amount_mask.sum()
amount_zero = zero_amount_mask.sum()

display(Markdown(f"""
### Numeric Verification Observation

The numeric verification identified several conditions that require
consideration before cleaning.

#### Customer Age

- Missing values: **{age_missing}**
- Non-numeric values: **{age_non_numeric}**
- Questionable numeric values below 0 or above 120: **{age_questionable}**

#### Transaction Amount

- Missing values: **{amount_missing}**
- Non-numeric values: **{amount_non_numeric}**
- Negative values: **{amount_negative}**
- Zero values: **{amount_zero}**

These findings demonstrate that successful CSV loading does not guarantee
that values are analytically valid.

No numeric values have been corrected, replaced, or removed at this stage.
The identified records will be reviewed before treatment decisions are
applied.
"""))

### Numeric Verification Observation

The numeric verification identified several conditions that require
consideration before cleaning.

#### Customer Age

- Missing values: **291**
- Non-numeric values: **34**
- Questionable numeric values below 0 or above 120: **63**

#### Transaction Amount

- Missing values: **304**
- Non-numeric values: **30**
- Negative values: **40**
- Zero values: **30**

These findings demonstrate that successful CSV loading does not guarantee
that values are analytically valid.

No numeric values have been corrected, replaced, or removed at this stage.
The identified records will be reviewed before treatment decisions are
applied.

### Date Format Verification

Date variables are reviewed before conversion because the raw CSV files
may contain more than one date format.

The FinMark datasets contain three primary date variables:

- `SignupDate` in Customer Demographics
- `TransactionDate` in Customer Transactions
- `InteractionDate` in Social Media Interactions

The goal of this step is to identify the date formats currently present,
test whether the values can be parsed successfully, and detect records that
may require normalization during cleaning.

The original raw datasets will not be modified during this verification step.

#### Review Raw Date Values

A sample of the original date values is displayed first to identify visible
differences in formatting before any date conversion is attempted.

In [ ]:
print("SignupDate Sample")
display(
    demographics_raw["SignupDate"]
    .dropna()
    .sample(min(20, demographics_raw["SignupDate"].dropna().shape[0]),
            random_state=42)
)

print("\nTransactionDate Sample")
display(
    transactions_raw["TransactionDate"]
    .dropna()
    .sample(min(20, transactions_raw["TransactionDate"].dropna().shape[0]),
            random_state=42)
)

print("\nInteractionDate Sample")
display(
    social_raw["InteractionDate"]
    .dropna()
    .sample(min(20, social_raw["InteractionDate"].dropna().shape[0]),
            random_state=42)
)

SignupDate Sample

2384    2020-07-11
2538    2022-01-26
2176    2020-11-29
897     2021-09-14
214     2023-07-07
2380    2021-09-06
2714    2021-05-03
2576    2024-05-26
102     2024-02-17
192     2020-05-03
1447    2022-03-08
229     2021-02-21
776     2023-01-16
1236    2024-02-10
2582    2019-10-03
17      2023-07-09
1127    2020-12-19
170     2023-02-18
2247    2019-11-25
1091    2023-03-04
Name: SignupDate, dtype: object

TransactionDate Sample

2384    2022-12-02
2538    2023-01-12
2176    2023-09-08
897     2024-06-15
214     2024-06-22
2380    2024-01-23
2714    2023-09-05
2576    2022-07-29
102     2023-01-25
192     2022-12-25
1447    10/05/2023
229     2023-08-19
776     2022-11-28
1236    2024-05-11
2582    2024-05-07
17      2024-04-17
1127    2023-06-12
170     2023-05-16
2247    2023-09-21
1091    2024-02-20
Name: TransactionDate, dtype: object

InteractionDate Sample

2384    2024-01-21
2538    2024-03-30
2176    2024-06-28
897     2023-10-06
214     2024-01-05
2380    2023-08-08
2714    2024-06-15
2576    2023-12-06
102     2023-07-04
192     2023-08-03
1447    2024-02-16
229     2023-07-22
776     2024-02-12
1236    2024-02-04
2582    2023-08-13
17      2023-08-17
1127    2023-08-05
170     2024-01-30
2247    2023-11-24
1091    2023-12-29
Name: InteractionDate, dtype: object

#### Date Format Pattern Review

The date strings are reviewed by general pattern so that different
representations can be identified before parsing.

This helps distinguish formatting inconsistency from invalid date values.

In [ ]:
import re

def detect_date_pattern(value):
    if pd.isna(value):
        return "Missing"

    value = str(value).strip()

    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", value):
        return "YYYY-MM-DD"

    if re.fullmatch(r"\d{2}/\d{2}/\d{4}", value):
        return "DD/MM/YYYY or MM/DD/YYYY"

    return "Other"


signup_patterns = demographics_raw["SignupDate"].apply(detect_date_pattern)
transaction_patterns = transactions_raw["TransactionDate"].apply(detect_date_pattern)
interaction_patterns = social_raw["InteractionDate"].apply(detect_date_pattern)

print("SignupDate Patterns")
display(signup_patterns.value_counts(dropna=False))

print("\nTransactionDate Patterns")
display(transaction_patterns.value_counts(dropna=False))

print("\nInteractionDate Patterns")
display(interaction_patterns.value_counts(dropna=False))

SignupDate Patterns

SignupDate
YYYY-MM-DD                  3102
DD/MM/YYYY or MM/DD/YYYY      98
Name: count, dtype: int64

TransactionDate Patterns

TransactionDate
YYYY-MM-DD                  3102
DD/MM/YYYY or MM/DD/YYYY      98
Name: count, dtype: int64

InteractionDate Patterns

InteractionDate
YYYY-MM-DD                  3100
DD/MM/YYYY or MM/DD/YYYY     100
Name: count, dtype: int64

#### Temporary Date Parsing

Temporary parsed date variables are created to test whether the raw date
values can be converted successfully.

The parsing results are used only for verification. The original date
columns remain unchanged.

In [ ]:
signup_date_test = pd.to_datetime(
    demographics_raw["SignupDate"],
    errors="coerce",
    dayfirst=True
)

transaction_date_test = pd.to_datetime(
    transactions_raw["TransactionDate"],
    errors="coerce",
    dayfirst=True
)

interaction_date_test = pd.to_datetime(
    social_raw["InteractionDate"],
    errors="coerce",
    dayfirst=True
)

/tmp/ipykernel_13287/2595720227.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  signup_date_test = pd.to_datetime(
/tmp/ipykernel_13287/2595720227.py:7: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  transaction_date_test = pd.to_datetime(

#### Unparsable Date Records

Records whose original date values are present but fail temporary date
conversion are identified for review.

These values may represent invalid dates, unsupported formats, or other
formatting inconsistencies.

In [ ]:
invalid_signup_mask = (
    demographics_raw["SignupDate"].notna()
    & signup_date_test.isna()
)

invalid_transaction_date_mask = (
    transactions_raw["TransactionDate"].notna()
    & transaction_date_test.isna()
)

invalid_interaction_date_mask = (
    social_raw["InteractionDate"].notna()
    & interaction_date_test.isna()
)

print(
    "Invalid SignupDate records:",
    invalid_signup_mask.sum()
)

display(
    demographics_raw.loc[
        invalid_signup_mask,
        ["CustomerID", "SignupDate"]
    ].head(20)
)

print(
    "\nInvalid TransactionDate records:",
    invalid_transaction_date_mask.sum()
)

display(
    transactions_raw.loc[
        invalid_transaction_date_mask,
        ["TransactionID", "CustomerID", "TransactionDate"]
    ].head(20)
)

print(
    "\nInvalid InteractionDate records:",
    invalid_interaction_date_mask.sum()
)

display(
    social_raw.loc[
        invalid_interaction_date_mask,
        ["InteractionID", "CustomerID", "InteractionDate"]
    ].head(20)
)

Invalid SignupDate records: 98

                               CustomerID  SignupDate
27   23b3aa96-cec0-4964-8176-98ce984158a8  30/01/2020
96   cc5da89b-c295-41c3-b27d-c759cca78ba8  12/01/2024
127  febc5ef6-d9f5-459d-b7ef-40fdb9c2588b  10/01/2022
158  ae075979-b98f-46bf-bd3b-cc75f7216c3c  14/01/2024
160  bbf7c36f-3745-4d3a-9e33-f927c2755f65  07/07/2019
183  1eea3d52-fd1a-403e-8e70-7919dca848ee  25/11/2020
225  b72f2a59-aab0-447d-bb31-9bdc1405cc72  10/06/2024
250  e5d3b19d-e899-4694-aac3-705696a235e3  18/03/2021
292  7c40da22-ee52-4381-b501-c5fc91248472  27/06/2023
348  8880506d-dbb6-42ea-98c3-c0b7454c04bb  24/04/2020
352  9f6b9ab6-1055-4a20-912e-23adb444695c  03/04/2020
436  f9edc899-39cf-4227-9b37-c40003bc28af  04/02/2024
438  c82f4cc5-e3e9-4919-ad14-bc9ad485fd45  22/04/2023
440  46c6bd4d-5902-44cc-b3b2-fb82f6ab2cb6  06/06/2020
446  9aa1e60e-df4c-4987-9ee8-70b4e6edbca6  16/02/2023
470  1d4e578b-738c-4913-84f4-b008488eab48  11/09/2020
502  f2fa85fd-89ce-488e-bbdf-4535ae78da25  20/05/2021
523  e4ce98e6-81ec-48c3-a198-813996dfdf1b  12/11/2019
572  9107778f-48e1-4ecd-9511-10e549305477  26/10/2021
594  5a8b6207-27b9-4ad1-9157-cfac7d2abd4d  08/10/2022

Invalid TransactionDate records: 98

,TransactionID,CustomerID,TransactionDate
31,434a98c5-5b2d-4f93-92fa-edf8b0fd3d6e,36d99323-1a8b-45ed-bd7d-30b948e29684,01/04/2024
94,05d6d53f-92d1-4be7-9346-2d142470f849,dc72a8be-9df4-4223-83ee-50131b249bd3,13/12/2022
106,22da76bb-b240-4e90-8efe-de5e07061c51,13c73f2c-056e-40c6-a61f-97d5790c504a,26/10/2022
121,fb09f753-0b5d-4612-9d6a-3fe220f0f3aa,6a4fcf07-d4f6-44cf-9d47-ddae1917f808,25/02/2023
124,c5c4ab32-3a2a-4748-96b7-f5ebbba384f2,7a7ebefe-7936-4e6f-9cf2-6e80c7d2d849,23/03/2023
238,e3a950b7-a993-4b3e-ac84-20d3e292833a,9d6c7c0d-70eb-45cc-ac6d-bbdd88aabeee,24/05/2023
252,04dbec3d-c8ae-45c4-b2c4-b705d6dc6cc3,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,16/09/2023
258,81ecc5aa-a0e6-4aab-a600-cc7137bc16a1,6d9b7c15-f813-4be6-8071-815990189894,11/09/2023
356,ea7f4d30-45c8-4e24-8f37-c30527a1d6a3,3c0eae54-dde8-4291-95d3-f8dfb98c475a,28/10/2022
389,a9272080-cc7f-4f82-9977-857549f2c895,348c5ab5-992d-4780-ba71-d1a5e3818191,12/10/2023
402,dc1ba702-8720-4582-9749-5bd14b886420,1ed01bef-384d-4c8b-a672-7c292860d7c1,13/04/2023
431,27fb25aa-f148-423f-967c-4d1764e26b29,b94b3531-591d-445c-b282-dcacb0baca5b,30/07/2022
437,f078102e-7e35-4371-b48e-2989ff4cec4f,3d24b8d6-68b7-46bd-ad7b-5cd8b8c6f8fd,29/12/2023
469,0aba7275-6bd4-404d-894a-cf695bcc2b67,dff72d74-6b17-4e1e-a904-6b8823b94a06,04/03/2023
506,a42657eb-b99d-4b66-b0e7-96a9cd6def89,728bcba7-868f-4f7d-9a79-1af48913bb93,06/07/2022
531,34d137e4-b03b-4ad4-8fc4-b1d964d5cc26,1e149041-13ca-4147-890c-3dee10c249e8,12/07/2023
563,f39c8b1d-595a-4656-8108-25981bf3fa14,f05ec030-ac96-417d-a73c-e3ca3adc1a30,03/04/2023
606,64f3ee25-c285-41ee-92b6-f70b006554ae,948ad644-2c83-4eb1-af0c-c16e76afccfb,12/06/2024
626,65520cc1-c798-4024-9caf-e1f893ef9cac,ec58ff99-ede4-4b51-8b0c-efdbb61275a7,18/11/2022
668,952adac7-c15e-47f0-ad86-aeb2205bea77,a19141a4-b574-4bdc-a9b4-c05e8b2519f7,01/01/2023

Invalid InteractionDate records: 1986

,InteractionID,CustomerID,InteractionDate
2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,2024-05-24
5,0c409883-8396-48e4-83fb-887329848696,3e44871b-f56c-4576-b1ca-d1dc999e2166,2023-12-18
6,4034dadf-6541-40d6-a7f0-16b20a009c04,aa5eea4b-c948-41f4-9285-229a470002aa,2023-11-15
7,bcfc43e7-c5aa-4dbd-9961-0e108784b199,7d83304d-2501-4c9f-ba63-a1a14343e51f,2024-03-29
9,67cdfb0b-3da6-46b8-a1f4-03b2abc81f58,63ee220c-19ae-4113-b45c-276b22b068e1,2023-11-18
10,785b7854-4548-4251-83f2-a25da78bfe40,481bcc62-9dcb-4766-bbdd-79f5554d73f8,2024-05-28
11,be6a0be7-84a8-428e-8526-13c3500e35e9,9c16dd71-a1f0-4801-8f00-860c2ee154a1,2024-06-27
12,26e650e5-a8af-45ea-9c49-3569a7d1a2fe,e8d8dccc-96b4-4451-ac1b-c4de6d18c3dd,2023-08-31
13,753ff148-793b-4db5-a3e1-16f6e470dd0a,f0c55dc8-d7f6-481d-8992-af3ce9453a51,2023-08-27
16,5e71bb25-c9ed-4362-a9f8-6802cebfc670,0305625f-6264-4666-ad6c-ae34df05d0d8,2023-08-18
17,9edcf60c-599e-4a2f-a723-1fb6776b8cf4,b8e6ad59-8b84-405d-af66-b0c1bebf7578,2023-08-17
18,7cdba85b-17cc-4d72-b4aa-14f718a50be6,616e2347-91b4-4a50-8a15-4c65aff20788,2024-03-28
20,f4e35835-e3a6-4dee-a9fd-848603a322e4,851911c8-6d3f-4a7f-b70c-9b93057d9f94,26/01/2024
21,6ae1f833-cd5d-4513-8675-81cc41ecd28f,6cd5d668-396c-4e82-97ae-a8bb7fa1d010,2024-01-14
22,a3b06362-9ff0-433b-be2f-477c452259c2,348c5ab5-992d-4780-ba71-d1a5e3818191,2023-08-29
23,ef15ee00-2882-4ef5-b1f3-2a004a265d77,81d213e6-e289-482d-b2a9-326144b84d2c,01/10/2023
24,acc05b0c-b63b-4f76-b256-8af404f1f9b7,3e9cc599-ba23-4de3-9c18-19a2ce4764e0,2023-08-19
25,b8c326c7-3b35-4cea-875a-013600d7bd64,2d1c8d1a-be1f-45a9-82d8-036f5e17d809,28/03/2024
26,4b1394bb-49e0-4182-8649-67bb090b995b,013c4cd9-1d0f-4004-8772-065ab426d105,15/08/2023
28,d59378e6-8b0e-49f9-9d32-f035a850bc37,6fa9f01c-09f8-44fd-8e18-51ca4f3921bf,2023-12-31

#### Parsed Date Range Review

Successfully parsed date values are summarized by their earliest and latest
dates.

This provides a basic logical check for dates that may fall outside the
expected project period.

In [ ]:
date_range_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Earliest Date": [
        signup_date_test.min(),
        transaction_date_test.min(),
        interaction_date_test.min()
    ],
    "Latest Date": [
        signup_date_test.max(),
        transaction_date_test.max(),
        interaction_date_test.max()
    ]
})

display(date_range_summary)

                     Dataset Earliest Date Latest Date
0      Customer Demographics    2019-07-01  2024-06-30
1      Customer Transactions    2022-07-01  2024-06-30
2  Social Media Interactions    2023-01-07  2024-12-06

#### Date Verification Summary

The date verification results are summarized to distinguish between
missing date values and date values that cannot be parsed successfully.

In [ ]:
date_validation_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Missing Dates": [
        demographics_raw["SignupDate"].isnull().sum(),
        transactions_raw["TransactionDate"].isnull().sum(),
        social_raw["InteractionDate"].isnull().sum()
    ],
    "Unparsable Dates": [
        invalid_signup_mask.sum(),
        invalid_transaction_date_mask.sum(),
        invalid_interaction_date_mask.sum()
    ]
})

display(date_validation_summary)

                     Dataset  Missing Dates  Unparsable Dates
0      Customer Demographics              0                98
1      Customer Transactions              0                98
2  Social Media Interactions              0              1986

In [ ]:
signup_missing = demographics_raw["SignupDate"].isnull().sum()
transaction_date_missing = transactions_raw["TransactionDate"].isnull().sum()
interaction_date_missing = social_raw["InteractionDate"].isnull().sum()

signup_invalid = invalid_signup_mask.sum()
transaction_date_invalid = invalid_transaction_date_mask.sum()
interaction_date_invalid = invalid_interaction_date_mask.sum()

display(Markdown(f"""
### Date Verification Observation

The date verification produced the following results:

#### Customer Demographics
- Missing SignupDate values: **{signup_missing}**
- Unparsable SignupDate values: **{signup_invalid}**

#### Customer Transactions
- Missing TransactionDate values: **{transaction_date_missing}**
- Unparsable TransactionDate values: **{transaction_date_invalid}**

#### Social Media Interactions
- Missing InteractionDate values: **{interaction_date_missing}**
- Unparsable InteractionDate values: **{interaction_date_invalid}**

The raw datasets may contain multiple date representations. These format
differences will be standardized during the cleaning phase after all
data-quality issues have been documented.

No date values have been permanently converted or modified at this stage.
"""))

### Date Verification Observation

The date verification produced the following results:

#### Customer Demographics
- Missing SignupDate values: **0**
- Unparsable SignupDate values: **98**

#### Customer Transactions
- Missing TransactionDate values: **0**
- Unparsable TransactionDate values: **98**

#### Social Media Interactions
- Missing InteractionDate values: **0**
- Unparsable InteractionDate values: **1986**

The raw datasets may contain multiple date representations. These format
differences will be standardized during the cleaning phase after all
data-quality issues have been documented.

No date values have been permanently converted or modified at this stage.

#### Unparsable Date Format Investigation

The temporary parsing process identified date values that could not be
converted successfully.

Before treating these records as invalid, the affected values are examined
to determine whether the failures are caused by alternative but valid date
formats.

This prevents valid date information from being incorrectly removed during
cleaning.

In [ ]:
print("SignupDate values that failed parsing")
display(
    demographics_raw.loc[
        invalid_signup_mask,
        "SignupDate"
    ].value_counts().head(30)
)

print("\nTransactionDate values that failed parsing")
display(
    transactions_raw.loc[
        invalid_transaction_date_mask,
        "TransactionDate"
    ].value_counts().head(30)
)

print("\nInteractionDate values that failed parsing")
display(
    social_raw.loc[
        invalid_interaction_date_mask,
        "InteractionDate"
    ].value_counts().head(30)
)

SignupDate values that failed parsing

SignupDate
18/01/2024    2
12/01/2024    1
10/01/2022    1
14/01/2024    1
07/07/2019    1
25/11/2020    1
10/06/2024    1
18/03/2021    1
27/06/2023    1
24/04/2020    1
03/04/2020    1
04/02/2024    1
22/04/2023    1
06/06/2020    1
16/02/2023    1
11/09/2020    1
20/05/2021    1
12/11/2019    1
26/10/2021    1
08/10/2022    1
16/03/2020    1
22/06/2022    1
26/01/2022    1
29/07/2021    1
25/05/2024    1
20/06/2020    1
24/04/2022    1
01/07/2019    1
13/11/2023    1
13/05/2021    1
Name: count, dtype: int64

TransactionDate values that failed parsing

TransactionDate
30/05/2023    3
24/05/2023    2
12/06/2024    2
17/10/2023    2
27/03/2024    2
23/03/2023    1
25/02/2023    1
11/09/2023    1
28/10/2022    1
12/10/2023    1
16/09/2023    1
01/04/2024    1
30/07/2022    1
13/04/2023    1
06/07/2022    1
29/12/2023    1
12/07/2023    1
03/04/2023    1
18/11/2022    1
04/03/2023    1
01/01/2023    1
05/06/2023    1
20/09/2022    1
13/10/2022    1
05/07/2022    1
19/11/2023    1
26/10/2022    1
13/12/2022    1
01/08/2022    1
17/03/2023    1
Name: count, dtype: int64

InteractionDate values that failed parsing

InteractionDate
2024-01-30    16
2023-09-15    16
2024-06-29    16
2023-12-27    16
2023-12-18    15
2024-01-13    15
2024-02-26    15
2023-09-30    14
2023-07-26    14
2023-11-30    14
2023-09-20    14
2024-02-16    14
2024-01-15    13
2024-03-15    13
2024-04-15    13
2023-08-13    13
2023-11-14    13
2023-09-19    13
2024-04-30    13
2024-05-25    13
2023-10-22    12
2023-08-29    12
2024-01-22    12
2023-08-14    12
2024-03-14    12
2023-12-16    12
2024-05-19    12
2023-12-24    12
2024-04-13    12
2023-10-21    12
Name: count, dtype: int64

#### Explicit Mixed-Date Parsing Test

The date fields may contain multiple valid representations.

To avoid interpreting valid formatting differences as invalid dates, a
temporary parsing function is used to test recognized date formats
separately.

The raw datasets remain unchanged.

In [ ]:
def parse_finmark_date(series):
    # Work with a temporary string copy
    date_strings = series.astype("string").str.strip()

    # Create an empty datetime Series
    parsed_dates = pd.Series(
        pd.NaT,
        index=series.index,
        dtype="datetime64[ns]"
    )

    # Format 1: YYYY-MM-DD
    iso_mask = date_strings.str.match(
        r"^\d{4}-\d{2}-\d{2}$",
        na=False
    )

    parsed_dates.loc[iso_mask] = pd.to_datetime(
        date_strings.loc[iso_mask],
        format="%Y-%m-%d",
        errors="coerce"
    )

    # Format 2: DD/MM/YYYY
    day_first_mask = date_strings.str.match(
        r"^\d{2}/\d{2}/\d{4}$",
        na=False
    )

    parsed_dates.loc[day_first_mask] = pd.to_datetime(
        date_strings.loc[day_first_mask],
        format="%d/%m/%Y",
        errors="coerce"
    )

    return parsed_dates

In [ ]:
signup_date_verified = parse_finmark_date(
    demographics_raw["SignupDate"]
)

transaction_date_verified = parse_finmark_date(
    transactions_raw["TransactionDate"]
)

interaction_date_verified = parse_finmark_date(
    social_raw["InteractionDate"]
)

In [ ]:
signup_still_invalid = (
    demographics_raw["SignupDate"].notna()
    & signup_date_verified.isna()
)

transaction_still_invalid = (
    transactions_raw["TransactionDate"].notna()
    & transaction_date_verified.isna()
)

interaction_still_invalid = (
    social_raw["InteractionDate"].notna()
    & interaction_date_verified.isna()
)

date_revalidation_summary = pd.DataFrame({
    "Date Field": [
        "SignupDate",
        "TransactionDate",
        "InteractionDate"
    ],
    "Original Temporary Failures": [
        invalid_signup_mask.sum(),
        invalid_transaction_date_mask.sum(),
        invalid_interaction_date_mask.sum()
    ],
    "Failures After Explicit Parsing": [
        signup_still_invalid.sum(),
        transaction_still_invalid.sum(),
        interaction_still_invalid.sum()
    ]
})

display(date_revalidation_summary)

,Date Field,Original Temporary Failures,Failures After Explicit Parsing
0,SignupDate,98,0
1,TransactionDate,98,0
2,InteractionDate,1986,0

In [ ]:
from IPython.display import Markdown, display

signup_original_failures = invalid_signup_mask.sum()
transaction_original_failures = invalid_transaction_date_mask.sum()
interaction_original_failures = invalid_interaction_date_mask.sum()

signup_final_failures = signup_still_invalid.sum()
transaction_final_failures = transaction_still_invalid.sum()
interaction_final_failures = interaction_still_invalid.sum()

display(Markdown(f"""
### Date Revalidation Observation

The initial temporary date conversion reported parsing failures because
the raw datasets contain more than one valid date representation.

After explicitly testing the recognized `YYYY-MM-DD` and `DD/MM/YYYY`
formats, the results were:

#### Customer Demographics
- Initial temporary parsing failures: **{signup_original_failures}**
- Remaining failures after explicit parsing: **{signup_final_failures}**

#### Customer Transactions
- Initial temporary parsing failures: **{transaction_original_failures}**
- Remaining failures after explicit parsing: **{transaction_final_failures}**

#### Social Media Interactions
- Initial temporary parsing failures: **{interaction_original_failures}**
- Remaining failures after explicit parsing: **{interaction_final_failures}**

All previously identified parsing failures were successfully interpreted
using the verified date formats.

Therefore, these records are treated as **date-format inconsistencies rather
than invalid date values**.

No records will be removed because of these formatting differences.
During the cleaning phase, the valid date values will be normalized to a
consistent `YYYY-MM-DD` representation.
"""))

### Date Revalidation Observation

The initial temporary date conversion reported parsing failures because
the raw datasets contain more than one valid date representation.

After explicitly testing the recognized `YYYY-MM-DD` and `DD/MM/YYYY`
formats, the results were:

#### Customer Demographics
- Initial temporary parsing failures: **98**
- Remaining failures after explicit parsing: **0**

#### Customer Transactions
- Initial temporary parsing failures: **98**
- Remaining failures after explicit parsing: **0**

#### Social Media Interactions
- Initial temporary parsing failures: **1986**
- Remaining failures after explicit parsing: **0**

All previously identified parsing failures were successfully interpreted
using the verified date formats.

Therefore, these records are treated as **date-format inconsistencies rather
than invalid date values**.

No records will be removed because of these formatting differences.
During the cleaning phase, the valid date values will be normalized to a
consistent `YYYY-MM-DD` representation.

### Categorical Consistency Verification

Categorical variables are reviewed to identify inconsistent capitalization,
spacing, spelling, or naming conventions.

The goal is to distinguish legitimate categories from formatting differences
that may represent the same value.

No categorical values are modified during this verification step.

In [ ]:
categorical_columns = {
    "Customer Demographics": {
        "Gender": demographics_raw["Gender"],
        "IncomeLevel": demographics_raw["IncomeLevel"],
        "Location": demographics_raw["Location"]
    },
    "Customer Transactions": {
        "ProductCategory": transactions_raw["ProductCategory"],
        "PaymentMethod": transactions_raw["PaymentMethod"]
    },
    "Social Media Interactions": {
        "Platform": social_raw["Platform"],
        "InteractionType": social_raw["InteractionType"],
        "Sentiment": social_raw["Sentiment"]
    }
}

for dataset_name, columns in categorical_columns.items():

    print(f"\n{dataset_name.upper()}")

    for column_name, series in columns.items():

        print(f"\n{column_name}")

        display(
            series.value_counts(
                dropna=False
            )
        )

CUSTOMER DEMOGRAPHICS

Gender

Gender
Female    1610
Male      1590
Name: count, dtype: int64

IncomeLevel

IncomeLevel
High      1004
Low        985
Medium     908
NaN        303
Name: count, dtype: int64

Location

Location
Port Michael        6
Michaelton          5
West Michael        4
Michaelville        4
Port Adam           4
                   ..
Castillotown        1
Danielfurt          1
Jessicaland         1
Port Natashaview    1
Lake Ashley         1
Name: count, Length: 2696, dtype: int64

CUSTOMER TRANSACTIONS

ProductCategory

ProductCategory
Clothing           598
Electronics        595
Automotive         576
Health & Beauty    570
Home & Garden      562
NaN                299
Name: count, dtype: int64

PaymentMethod

PaymentMethod
Debit Card       809
Credit Card      804
PayPal           794
Bank Transfer    793
Name: count, dtype: int64

SOCIAL MEDIA INTERACTIONS

Platform

Platform
Instagram    976
Twitter      967
Facebook     946
NaN          311
Name: count, dtype: int64

InteractionType

InteractionType
Comment    1079
Share      1067
Like       1054
Name: count, dtype: int64

Sentiment

Sentiment
Positive         962
Negative         925
Neutral          918
NaN              329
Very Negative     34
Very Positive     32
Name: count, dtype: int64

#### Normalized Category Comparison

Temporary normalized versions of the categorical values are created using
trimmed whitespace and lowercase text.

This comparison helps identify values that differ only because of
capitalization or spacing.

The raw datasets remain unchanged.

In [ ]:
def compare_category_formatting(series):

    raw_unique = series.dropna().nunique()

    normalized = (
        series
        .astype("string")
        .str.strip()
        .str.lower()
    )

    normalized_unique = normalized.dropna().nunique()

    return raw_unique, normalized_unique


category_format_summary = []

for dataset_name, columns in categorical_columns.items():

    for column_name, series in columns.items():

        raw_unique, normalized_unique = compare_category_formatting(series)

        category_format_summary.append({
            "Dataset": dataset_name,
            "Column": column_name,
            "Raw Unique Values": raw_unique,
            "Normalized Unique Values": normalized_unique,
            "Possible Formatting Differences": (
                raw_unique - normalized_unique
            )
        })


category_format_summary = pd.DataFrame(
    category_format_summary
)

display(category_format_summary)

,Dataset,Column,Raw Unique Values,Normalized Unique Values,Possible Formatting Differences
0,Customer Demographics,Gender,2,2,0
1,Customer Demographics,IncomeLevel,3,3,0
2,Customer Demographics,Location,2696,2696,0
3,Customer Transactions,ProductCategory,5,5,0
4,Customer Transactions,PaymentMethod,4,4,0
5,Social Media Interactions,Platform,3,3,0
6,Social Media Interactions,InteractionType,3,3,0
7,Social Media Interactions,Sentiment,5,5,0

In [ ]:
from IPython.display import Markdown, display

income_missing = demographics_raw["IncomeLevel"].isnull().sum()
product_missing = transactions_raw["ProductCategory"].isnull().sum()
platform_missing = social_raw["Platform"].isnull().sum()
sentiment_missing = social_raw["Sentiment"].isnull().sum()

formatting_issues = (
    category_format_summary[
        "Possible Formatting Differences"
    ].sum()
)

location_unique = demographics_raw["Location"].nunique()
sentiment_unique = social_raw["Sentiment"].nunique()

display(Markdown(f"""
### Categorical Consistency Observation

The categorical consistency verification produced the following findings:

#### Formatting Consistency

- Total possible capitalization or whitespace-based category differences:
  **{formatting_issues}**

No categorical variables showed a reduction in unique values after temporary
lowercase and whitespace normalization. This indicates that the existing
category labels are already consistently formatted.

#### Missing Categorical Values

- IncomeLevel: **{income_missing}**
- ProductCategory: **{product_missing}**
- Platform: **{platform_missing}**
- Sentiment: **{sentiment_missing}**

These records were previously identified as missing-data issues and will
be handled according to the documented missing-value cleaning policy.

#### Additional Observations

- Location contains **{location_unique}** distinct values.
- Sentiment contains **{sentiment_unique}** non-missing categories.

The five sentiment categories will remain distinct because the current
verification provides no evidence that categories such as Positive and
Very Positive, or Negative and Very Negative, represent duplicate values.

No categorical values are modified during this verification step.
"""))

### Categorical Consistency Observation

The categorical consistency verification produced the following findings:

#### Formatting Consistency

- Total possible capitalization or whitespace-based category differences:
  **0**

No categorical variables showed a reduction in unique values after temporary
lowercase and whitespace normalization. This indicates that the existing
category labels are already consistently formatted.

#### Missing Categorical Values

- IncomeLevel: **303**
- ProductCategory: **299**
- Platform: **311**
- Sentiment: **329**

These records were previously identified as missing-data issues and will
be handled according to the documented missing-value cleaning policy.

#### Additional Observations

- Location contains **2696** distinct values.
- Sentiment contains **5** non-missing categories.

The five sentiment categories will remain distinct because the current
verification provides no evidence that categories such as Positive and
Very Positive, or Negative and Very Negative, represent duplicate values.

No categorical values are modified during this verification step.

### Cross-Dataset Identifier Integrity Verification

CustomerID is the common identifier used to relate customer demographics,
transactions, and social media interactions.

Before cleaning or combining the datasets, the CustomerID values are checked
across datasets to determine whether transaction or social media records
reference customers that are not represented in the Customer Demographics
dataset.

This verification supports data integrity and helps identify possible
orphan records before later analysis or dataset integration.

No records are modified during this verification step.

In [ ]:
demographic_customers = set(
    demographics_raw["CustomerID"].dropna().unique()
)

transaction_customers = set(
    transactions_raw["CustomerID"].dropna().unique()
)

social_customers = set(
    social_raw["CustomerID"].dropna().unique()
)

print(
    "Unique CustomerIDs in Customer Demographics:",
    len(demographic_customers)
)

print(
    "Unique CustomerIDs in Customer Transactions:",
    len(transaction_customers)
)

print(
    "Unique CustomerIDs in Social Media Interactions:",
    len(social_customers)
)

Unique CustomerIDs in Customer Demographics: 3000
Unique CustomerIDs in Customer Transactions: 1871
Unique CustomerIDs in Social Media Interactions: 1893

#### Orphan CustomerID Review

CustomerIDs appearing in the transaction or social media datasets are
compared with the Customer Demographics dataset.

A CustomerID found in an activity dataset but not in Customer Demographics
is treated as a potential orphan identifier because its corresponding
customer-level demographic record is unavailable.

In [ ]:
transaction_orphan_customers = (
    transaction_customers - demographic_customers
)

social_orphan_customers = (
    social_customers - demographic_customers
)

print(
    "Transaction CustomerIDs not found in demographics:",
    len(transaction_orphan_customers)
)

print(
    "Social Media CustomerIDs not found in demographics:",
    len(social_orphan_customers)
)

Transaction CustomerIDs not found in demographics: 0
Social Media CustomerIDs not found in demographics: 0

In [ ]:
print("Transaction Records with CustomerIDs Missing from Demographics")

display(
    transactions_raw[
        transactions_raw["CustomerID"].isin(
            transaction_orphan_customers
        )
    ].head(20)
)

print(
    "\nSocial Media Records with CustomerIDs Missing from Demographics"
)

display(
    social_raw[
        social_raw["CustomerID"].isin(
            social_orphan_customers
        )
    ].head(20)
)

Transaction Records with CustomerIDs Missing from Demographics

Empty DataFrame
Columns: [CustomerID, TransactionID, TransactionDate, Amount, ProductCategory, PaymentMethod]
Index: []

Social Media Records with CustomerIDs Missing from Demographics

Empty DataFrame
Columns: [CustomerID, InteractionID, InteractionDate, Platform, InteractionType, Sentiment]
Index: []

#### Customer Coverage Review

CustomerIDs in the demographics dataset are also compared with the activity
datasets to identify customers without recorded transactions or social media
interactions.

The absence of activity does not automatically represent a data-quality
error because a valid customer may have no recorded transaction or social
media interaction during the available observation period.

In [ ]:
customers_without_transactions = (
    demographic_customers - transaction_customers
)

customers_without_social = (
    demographic_customers - social_customers
)

print(
    "Demographic CustomerIDs without transactions:",
    len(customers_without_transactions)
)

print(
    "Demographic CustomerIDs without social interactions:",
    len(customers_without_social)
)

Demographic CustomerIDs without transactions: 1129
Demographic CustomerIDs without social interactions: 1107

#### Identifier Integrity Summary

The cross-dataset CustomerID relationships are summarized below to separate
potential orphan records from customers who simply have no recorded activity.

In [ ]:
identifier_integrity_summary = pd.DataFrame({
    "Check": [
        "Unique CustomerIDs in Demographics",
        "Unique CustomerIDs in Transactions",
        "Unique CustomerIDs in Social Media",
        "Transaction CustomerIDs Missing from Demographics",
        "Social CustomerIDs Missing from Demographics",
        "Demographic Customers without Transactions",
        "Demographic Customers without Social Interactions"
    ],
    "Count": [
        len(demographic_customers),
        len(transaction_customers),
        len(social_customers),
        len(transaction_orphan_customers),
        len(social_orphan_customers),
        len(customers_without_transactions),
        len(customers_without_social)
    ]
})

display(identifier_integrity_summary)

                                               Check  Count
0                 Unique CustomerIDs in Demographics   3000
1                 Unique CustomerIDs in Transactions   1871
2                 Unique CustomerIDs in Social Media   1893
3  Transaction CustomerIDs Missing from Demographics      0
4       Social CustomerIDs Missing from Demographics      0
5         Demographic Customers without Transactions   1129
6  Demographic Customers without Social Interactions   1107

In [ ]:
display(Markdown(f"""
### Identifier Integrity Observation

The cross-dataset CustomerID verification produced the following results:

#### Customer Coverage

- Unique CustomerIDs in Customer Demographics:
  **{len(demographic_customers)}**

- Unique CustomerIDs in Customer Transactions:
  **{len(transaction_customers)}**

- Unique CustomerIDs in Social Media Interactions:
  **{len(social_customers)}**

#### Potential Orphan Identifiers

- Transaction CustomerIDs not found in demographics:
  **{len(transaction_orphan_customers)}**

- Social Media CustomerIDs not found in demographics:
  **{len(social_orphan_customers)}**

#### Customers without Recorded Activity

- Demographic customers without transactions:
  **{len(customers_without_transactions)}**

- Demographic customers without social media interactions:
  **{len(customers_without_social)}**

CustomerIDs appearing in transactions or social media but not in the
demographics dataset are treated as potential integrity issues because the
corresponding customer-level record is unavailable.

Customers present in demographics but without transaction or social media
activity are not automatically treated as errors because valid customers
may have no recorded activity during the available observation period.

No records are modified during this verification step.
"""))

### Identifier Integrity Observation

The cross-dataset CustomerID verification produced the following results:

#### Customer Coverage

- Unique CustomerIDs in Customer Demographics:
  **3000**

- Unique CustomerIDs in Customer Transactions:
  **1871**

- Unique CustomerIDs in Social Media Interactions:
  **1893**

#### Potential Orphan Identifiers

- Transaction CustomerIDs not found in demographics:
  **0**

- Social Media CustomerIDs not found in demographics:
  **0**

#### Customers without Recorded Activity

- Demographic customers without transactions:
  **1129**

- Demographic customers without social media interactions:
  **1107**

CustomerIDs appearing in transactions or social media but not in the
demographics dataset are treated as potential integrity issues because the
corresponding customer-level record is unavailable.

Customers present in demographics but without transaction or social media
activity are not automatically treated as errors because valid customers
may have no recorded activity during the available observation period.

No records are modified during this verification step.

### Data Relevance Review

The available variables are reviewed to confirm that they are relevant to
the FinMark business problem and suitable for later exploratory analysis.

This review distinguishes identifier fields, descriptive customer
attributes, transaction measures, activity variables, and date variables.

Identifier fields are retained for record integrity, relationships,
grouping, and traceability but will not be treated as ordinary machine
learning features.

No columns are removed during this verification step.

In [ ]:
data_relevance_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Demographics",
        "Customer Demographics",
        "Customer Demographics",
        "Customer Demographics",
        "Customer Demographics",
        "Customer Transactions",
        "Customer Transactions",
        "Customer Transactions",
        "Customer Transactions",
        "Customer Transactions",
        "Customer Transactions",
        "Social Media Interactions",
        "Social Media Interactions",
        "Social Media Interactions",
        "Social Media Interactions",
        "Social Media Interactions",
        "Social Media Interactions"
    ],

    "Variable": [
        "CustomerID",
        "Age",
        "Gender",
        "Location",
        "IncomeLevel",
        "SignupDate",
        "CustomerID",
        "TransactionID",
        "TransactionDate",
        "Amount",
        "ProductCategory",
        "PaymentMethod",
        "CustomerID",
        "InteractionID",
        "InteractionDate",
        "Platform",
        "InteractionType",
        "Sentiment"
    ],

    "Role": [
        "Identifier",
        "Customer Attribute",
        "Customer Attribute",
        "Customer Attribute",
        "Customer Attribute",
        "Date",
        "Identifier",
        "Identifier",
        "Date",
        "Numeric Measure",
        "Transaction Attribute",
        "Transaction Attribute",
        "Identifier",
        "Identifier",
        "Date",
        "Interaction Attribute",
        "Interaction Attribute",
        "Interaction Attribute"
    ],

    "Relevance": [
        "Links customer records across datasets",
        "Supports customer profile and segmentation analysis",
        "Supports customer profile and segmentation analysis",
        "Supports geographic customer analysis",
        "Supports socioeconomic and segmentation analysis",
        "Supports customer registration and time-based analysis",
        "Links transactions to customers",
        "Uniquely identifies transaction records",
        "Supports transaction timing and trend analysis",
        "Measures transaction value and spending behavior",
        "Supports product preference analysis",
        "Supports payment behavior analysis",
        "Links interactions to customers",
        "Uniquely identifies interaction records",
        "Supports interaction timing and trend analysis",
        "Supports channel engagement analysis",
        "Supports engagement behavior analysis",
        "Supports customer sentiment analysis"
    ]
})

display(data_relevance_summary)

,Dataset,Variable,Role,Relevance
0,Customer Demographics,CustomerID,Identifier,Links customer records across datasets
1,Customer Demographics,Age,Customer Attribute,Supports customer profile and segmentation ana...
2,Customer Demographics,Gender,Customer Attribute,Supports customer profile and segmentation ana...
3,Customer Demographics,Location,Customer Attribute,Supports geographic customer analysis
4,Customer Demographics,IncomeLevel,Customer Attribute,Supports socioeconomic and segmentation analysis
5,Customer Demographics,SignupDate,Date,Supports customer registration and time-based ...
6,Customer Transactions,CustomerID,Identifier,Links transactions to customers
7,Customer Transactions,TransactionID,Identifier,Uniquely identifies transaction records
8,Customer Transactions,TransactionDate,Date,Supports transaction timing and trend analysis
9,Customer Transactions,Amount,Numeric Measure,Measures transaction value and spending behavior
10,Customer Transactions,ProductCategory,Transaction Attribute,Supports product preference analysis
11,Customer Transactions,PaymentMethod,Transaction Attribute,Supports payment behavior analysis
12,Social Media Interactions,CustomerID,Identifier,Links interactions to customers
13,Social Media Interactions,InteractionID,Identifier,Uniquely identifies interaction records
14,Social Media Interactions,InteractionDate,Date,Supports interaction timing and trend analysis
15,Social Media Interactions,Platform,Interaction Attribute,Supports channel engagement analysis
16,Social Media Interactions,InteractionType,Interaction Attribute,Supports engagement behavior analysis
17,Social Media Interactions,Sentiment,Interaction Attribute,Supports customer sentiment analysis

In [ ]:
identifier_variables = data_relevance_summary[
    data_relevance_summary["Role"] == "Identifier"
]["Variable"].nunique()

total_variables = len(data_relevance_summary)

display(Markdown(f"""
### Data Relevance Observation

The data relevance review examined **{total_variables} dataset fields**
across the three FinMark datasets.

The available variables provide complementary information about:

- customer characteristics;
- customer registration timing;
- purchasing activity;
- transaction value and product preferences;
- payment behavior;
- social media engagement; and
- customer sentiment.

The identifier variables support record traceability and relationships
between datasets. They will be retained in the cleaned analytical datasets
but will not be treated as ordinary predictive or descriptive features.

No variables are removed at this stage because each available field has a
defensible role in the planned FinMark exploratory analysis.
"""))

### Data Relevance Observation

The data relevance review examined **18 dataset fields**
across the three FinMark datasets.

The available variables provide complementary information about:

- customer characteristics;
- customer registration timing;
- purchasing activity;
- transaction value and product preferences;
- payment behavior;
- social media engagement; and
- customer sentiment.

The identifier variables support record traceability and relationships
between datasets. They will be retained in the cleaned analytical datasets
but will not be treated as ordinary predictive or descriptive features.

No variables are removed at this stage because each available field has a
defensible role in the planned FinMark exploratory analysis.

## Pre-Cleaning Findings Summary

The previous verification steps identified the data-quality conditions
present in the raw FinMark datasets before any cleaning was performed.

The findings below consolidate the evidence from missing-value,
duplicate, numeric, date, categorical, identifier-integrity, and relevance
checks.

Planned treatments are documented before modifying the data so that each
cleaning decision remains transparent and reproducible.

In [ ]:
precleaning_findings = pd.DataFrame([
    {
        "Dataset": "Customer Demographics",
        "Issue": "Missing values",
        "Evidence": (
            f"Age: {demographics_raw['Age'].isnull().sum()} missing; "
            f"IncomeLevel: {demographics_raw['IncomeLevel'].isnull().sum()} missing"
        ),
        "Planned Treatment": "Omit records containing missing values",
        "Reason": "Missing values cannot be reliably reconstructed from the supplied data"
    },
    {
        "Dataset": "Customer Demographics",
        "Issue": "Exact duplicate rows",
        "Evidence": f"{demographics_raw.duplicated().sum()} exact duplicate rows",
        "Planned Treatment": "Remove confirmed exact duplicate rows",
        "Reason": "Exact duplicates may otherwise overrepresent identical records"
    },
    {
        "Dataset": "Customer Demographics",
        "Issue": "Non-numeric Age values",
        "Evidence": f"{invalid_age_mask.sum()} records",
        "Planned Treatment": "Review before treatment",
        "Reason": "Values cannot be treated as valid numeric ages without verification"
    },
    {
        "Dataset": "Customer Demographics",
        "Issue": "Questionable Age values",
        "Evidence": f"{questionable_age_mask.sum()} values below 0 or above 120",
        "Planned Treatment": "Review before treatment",
        "Reason": "Numeric values may still be logically invalid"
    },
    {
        "Dataset": "Customer Demographics",
        "Issue": "Mixed SignupDate formats",
        "Evidence": (
            f"{invalid_signup_mask.sum()} initial parsing failures; "
            f"{signup_still_invalid.sum()} remaining after explicit parsing"
        ),
        "Planned Treatment": "Normalize valid dates to YYYY-MM-DD",
        "Reason": "Explicit format parsing confirmed the values are valid but inconsistently formatted"
    },

    {
        "Dataset": "Customer Transactions",
        "Issue": "Missing values",
        "Evidence": (
            f"Amount: {transactions_raw['Amount'].isnull().sum()} missing; "
            f"ProductCategory: {transactions_raw['ProductCategory'].isnull().sum()} missing"
        ),
        "Planned Treatment": "Omit records containing missing values",
        "Reason": "Missing values cannot be reliably reconstructed from the supplied data"
    },
    {
        "Dataset": "Customer Transactions",
        "Issue": "Exact duplicate rows",
        "Evidence": f"{transactions_raw.duplicated().sum()} exact duplicate rows",
        "Planned Treatment": "Remove confirmed exact duplicate rows",
        "Reason": "Exact duplicates may otherwise overrepresent identical transactions"
    },
    {
        "Dataset": "Customer Transactions",
        "Issue": "Non-numeric Amount values",
        "Evidence": f"{invalid_amount_mask.sum()} records",
        "Planned Treatment": "Review before treatment",
        "Reason": "Non-numeric values cannot be used directly as transaction amounts"
    },
    {
        "Dataset": "Customer Transactions",
        "Issue": "Negative transaction amounts",
        "Evidence": f"{negative_amount_mask.sum()} records",
        "Planned Treatment": "Review before treatment",
        "Reason": "Negative values may represent invalid entries or legitimate business events"
    },
    {
        "Dataset": "Customer Transactions",
        "Issue": "Zero transaction amounts",
        "Evidence": f"{zero_amount_mask.sum()} records",
        "Planned Treatment": "Review before treatment",
        "Reason": "Zero values require interpretation before being classified as invalid"
    },
    {
        "Dataset": "Customer Transactions",
        "Issue": "Mixed TransactionDate formats",
        "Evidence": (
            f"{invalid_transaction_date_mask.sum()} initial parsing failures; "
            f"{transaction_still_invalid.sum()} remaining after explicit parsing"
        ),
        "Planned Treatment": "Normalize valid dates to YYYY-MM-DD",
        "Reason": "Explicit format parsing confirmed the values are valid but inconsistently formatted"
    },

    {
        "Dataset": "Social Media Interactions",
        "Issue": "Missing values",
        "Evidence": (
            f"Platform: {social_raw['Platform'].isnull().sum()} missing; "
            f"Sentiment: {social_raw['Sentiment'].isnull().sum()} missing"
        ),
        "Planned Treatment": "Omit records containing missing values",
        "Reason": "Missing values cannot be reliably reconstructed from the supplied data"
    },
    {
        "Dataset": "Social Media Interactions",
        "Issue": "Exact duplicate rows",
        "Evidence": f"{social_raw.duplicated().sum()} exact duplicate rows",
        "Planned Treatment": "Remove confirmed exact duplicate rows",
        "Reason": "Exact duplicates may otherwise overrepresent identical interactions"
    },
    {
        "Dataset": "Social Media Interactions",
        "Issue": "Mixed InteractionDate formats",
        "Evidence": (
            f"{invalid_interaction_date_mask.sum()} initial parsing failures; "
            f"{interaction_still_invalid.sum()} remaining after explicit parsing"
        ),
        "Planned Treatment": "Normalize valid dates to YYYY-MM-DD",
        "Reason": "Explicit format parsing confirmed the values are valid but inconsistently formatted"
    },

    {
        "Dataset": "All Datasets",
        "Issue": "Categorical formatting",
        "Evidence": (
            f"{category_format_summary['Possible Formatting Differences'].sum()} "
            "possible capitalization or whitespace differences"
        ),
        "Planned Treatment": "No category normalization required",
        "Reason": "No formatting-based duplicate categories were detected"
    },
    {
        "Dataset": "Cross-Dataset",
        "Issue": "Orphan CustomerIDs",
        "Evidence": (
            f"{len(transaction_orphan_customers)} transaction orphan IDs; "
            f"{len(social_orphan_customers)} social-media orphan IDs"
        ),
        "Planned Treatment": "No integrity correction required",
        "Reason": "All activity CustomerIDs are represented in Customer Demographics"
    }
])

display(precleaning_findings)

,Dataset,Issue,Evidence,Planned Treatment,Reason
0,Customer Demographics,Missing values,Age: 291 missing; IncomeLevel: 303 missing,Omit records containing missing values,Missing values cannot be reliably reconstructe...
1,Customer Demographics,Exact duplicate rows,177 exact duplicate rows,Remove confirmed exact duplicate rows,Exact duplicates may otherwise overrepresent i...
2,Customer Demographics,Non-numeric Age values,34 records,Review before treatment,Values cannot be treated as valid numeric ages...
3,Customer Demographics,Questionable Age values,63 values below 0 or above 120,Review before treatment,Numeric values may still be logically invalid
4,Customer Demographics,Mixed SignupDate formats,98 initial parsing failures; 0 remaining after...,Normalize valid dates to YYYY-MM-DD,Explicit format parsing confirmed the values a...
5,Customer Transactions,Missing values,Amount: 304 missing; ProductCategory: 299 missing,Omit records containing missing values,Missing values cannot be reliably reconstructe...
6,Customer Transactions,Exact duplicate rows,185 exact duplicate rows,Remove confirmed exact duplicate rows,Exact duplicates may otherwise overrepresent i...
7,Customer Transactions,Non-numeric Amount values,30 records,Review before treatment,Non-numeric values cannot be used directly as ...
8,Customer Transactions,Negative transaction amounts,40 records,Review before treatment,Negative values may represent invalid entries ...
9,Customer Transactions,Zero transaction amounts,30 records,Review before treatment,Zero values require interpretation before bein...
10,Customer Transactions,Mixed TransactionDate formats,98 initial parsing failures; 0 remaining after...,Normalize valid dates to YYYY-MM-DD,Explicit format parsing confirmed the values a...
11,Social Media Interactions,Missing values,Platform: 311 missing; Sentiment: 329 missing,Omit records containing missing values,Missing values cannot be reliably reconstructe...
12,Social Media Interactions,Exact duplicate rows,180 exact duplicate rows,Remove confirmed exact duplicate rows,Exact duplicates may otherwise overrepresent i...
13,Social Media Interactions,Mixed InteractionDate formats,1986 initial parsing failures; 0 remaining aft...,Normalize valid dates to YYYY-MM-DD,Explicit format parsing confirmed the values a...
14,All Datasets,Categorical formatting,0 possible capitalization or whitespace differ...,No category normalization required,No formatting-based duplicate categories were ...
15,Cross-Dataset,Orphan CustomerIDs,0 transaction orphan IDs; 0 social-media orpha...,No integrity correction required,All activity CustomerIDs are represented in Cu...

### Numeric Cleaning Decision Review

The pre-cleaning findings identified several numeric conditions that still
require evaluation before treatment can be finalized.

These include:

- non-numeric Age values;
- questionable numeric Age values;
- non-numeric transaction Amount values;
- negative transaction Amount values; and
- zero transaction Amount values.

The affected values are reviewed in their original form and, where useful,
together with related record information.

No records are removed during this investigation.

#### Non-Numeric Age Review

Non-numeric Age values are examined to determine whether they contain
recoverable numeric information or represent values that cannot be used as
valid customer ages.

In [ ]:
print("Non-Numeric Age Values")

display(
    demographics_raw.loc[
        invalid_age_mask,
        "Age"
    ].value_counts(dropna=False)
)

print("\nAffected Records")

display(
    demographics_raw.loc[
        invalid_age_mask,
        [
            "CustomerID",
            "Age",
            "Gender",
            "Location",
            "IncomeLevel"
        ]
    ].head(50)
)

Non-Numeric Age Values

Age
Unknown    34
Name: count, dtype: int64

Affected Records

,CustomerID,Age,Gender,Location,IncomeLevel
85,9bd23b55-cbc0-4082-ae18-916ea8895c07,Unknown,Male,Kimberlyview,Low
233,c1805670-0d42-4583-bfda-646f85252829,Unknown,Male,South Eric,High
240,e9c58327-25a1-4148-8c41-f0f37fc0c75d,Unknown,Female,Port Brittany,NaN
261,a3efade0-9841-40a8-9c00-0968581d608a,Unknown,Female,North Danielle,High
312,2cbc0b12-8048-4624-8149-0c9cd0920e35,Unknown,Female,North William,High
338,48313b18-ccdb-4946-b958-1ebfc92dcc2a,Unknown,Male,South Andrea,High
458,f7f5463e-6069-4ee0-8168-d3ebd6142553,Unknown,Female,Brendaborough,Medium
525,658c09ee-ffab-4a46-b971-af23b5b5da0e,Unknown,Female,Johnsonborough,High
554,684e0f75-2c90-424b-ae2a-0a669b799215,Unknown,Female,Jasonville,Low
625,70bc6d41-b25a-4041-a3ca-9215f887359b,Unknown,Female,North Stacey,Medium
681,5819025b-3df7-4da6-a8bd-5d980e61c5a4,Unknown,Female,Lake Miguelchester,High
828,db354959-55a3-4dbd-aa69-2c0885adb268,Unknown,Female,Youngville,Medium
1266,2f736c67-3ae7-404c-9ea3-bda4b6662844,Unknown,Female,Ariasport,Medium
1355,76c1d696-0f1c-44b5-b749-8859545658eb,Unknown,Female,South Frankside,High
1377,3341628f-8548-4ae7-9000-ec20c5973e5a,Unknown,Female,Stacybury,Medium
1496,823ace47-e265-4808-b0c3-f40fb41bf5de,Unknown,Male,Lisashire,Low
1544,e1f9dff8-fef5-49c4-b14b-c31bc3d61cc6,Unknown,Male,Christopherbury,Medium
1593,841fc557-ff70-4d45-8b0d-5be6f58d794d,Unknown,Male,North Traciville,Medium
1674,fcf17e99-1608-4711-bad6-fb435f8aa621,Unknown,Male,Port Nicholas,Low
1726,6ee69819-b275-4409-93d0-b62be6a7146a,Unknown,Male,Melodybury,Low
1766,e8236c55-bd04-44e1-a12c-e3b4bb747ec3,Unknown,Male,Lake Ryanstad,High
1794,11b2ebb2-7479-4c10-872d-353000075218,Unknown,Male,Jamesborough,Low
1799,0f50645d-c511-4df0-8020-43d5f17639f9,Unknown,Male,Christopherville,NaN
2021,51668fb4-bf4c-4030-8df0-ddc2263ec6ad,Unknown,Male,Tanyaton,Medium
2106,2cd16dfc-d7b0-47ec-9999-b018daea7f8d,Unknown,Female,Lake Carloshaven,Medium
2203,1542b18a-2c55-461f-ac68-bde74f09dd06,Unknown,Female,West Matthew,Medium
2219,681e49cc-3cf1-4eff-8139-5926f7e9ec8b,Unknown,Female,North Carmen,NaN
2230,af7e73a2-6c53-4483-aaba-8b6c9074e1ea,Unknown,Male,Steventon,Low
2235,fabacef8-5d27-4028-bec6-ab116a3219ae,Unknown,Female,East Michelle,High
2528,243a5ccd-31c3-440d-a3ad-73d3972dd39d,Unknown,Female,New Larry,NaN
2773,9612ee49-09dd-4f55-9524-9eb341efa2b9,Unknown,Male,North Breanna,High
2775,c2db166f-c1ac-4c34-a6aa-0c22721171e2,Unknown,Female,New Allisonborough,NaN
2965,0ade20e2-a4ff-40d2-b1b2-b8a04ee94c35,Unknown,Female,South Michael,Medium
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,Unknown,Male,Gregoryfurt,High

#### Questionable Age Review

Numeric Age values below 0 or above 120 are reviewed separately from
non-numeric values.

Although these entries can be converted to numbers, successful numeric
conversion does not guarantee that the values are logically suitable for
customer analysis.

In [ ]:
questionable_age_review = demographics_raw.loc[
    questionable_age_mask,
    [
        "CustomerID",
        "Age",
        "Gender",
        "Location",
        "IncomeLevel",
        "SignupDate"
    ]
].copy()

questionable_age_review["AgeNumeric"] = age_numeric.loc[
    questionable_age_mask
]

print("Questionable Age Value Counts")

display(
    questionable_age_review[
        "AgeNumeric"
    ].value_counts().sort_index()
)

print("\nAffected Records")

display(
    questionable_age_review.head(50)
)

Questionable Age Value Counts

AgeNumeric
-1.0      30
 150.0    33
Name: count, dtype: int64

Affected Records

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate,AgeNumeric
10,c96a5ee9-f1a6-416a-adc6-1c8b128c7399,150,Male,Hansontown,High,2020-09-17,150.0
48,b1d6a46b-214c-4592-9688-82d0fd977bb2,150,Female,North Cindyhaven,Low,2020-06-28,150.0
64,52303d17-9d24-4c20-89e3-7bcfa92140c9,150,Male,Spencermouth,NaN,2022-06-25,150.0
72,7a461a97-18fd-4686-ab3f-adaded72069d,150,Male,Pageside,High,2024-04-16,150.0
99,5ba7a03b-0d2f-4fc3-bd36-7a675c1ac61e,150,Female,East Ryanchester,High,2021-02-18,150.0
190,0dd7e84b-0aa4-4883-8bda-447e31b595d5,150,Female,Andreaburgh,Medium,2023-10-31,150.0
219,89432125-8fd0-4b2a-a3c6-4f2e6f8ddc64,150,Male,Vancestad,Low,2023-05-21,150.0
291,6cd7a734-a51d-4a11-ba1c-00c49d9a4490,-1,Male,West Connie,High,2022-11-05,-1.0
308,c0d8e0be-02a4-45c0-89c3-3ff31e60b4f7,-1.0,Male,South Rachel,NaN,2020-05-21,-1.0
314,4584583e-9825-4aa4-81ac-d6879195853f,150,Female,South Richardside,NaN,2023-09-08,150.0
348,8880506d-dbb6-42ea-98c3-c0b7454c04bb,150,Male,South Traciland,High,24/04/2020,150.0
400,aaca0879-8a14-41a4-8385-b1bfd3f97653,-1,Male,Laurahaven,NaN,2023-07-06,-1.0
539,50465bde-6a9a-466d-804a-a8f046809a23,-1,Male,Harrismouth,High,2023-08-02,-1.0
690,52f2132d-b2bf-4c09-9bdf-2d634ea7ebca,-1,Male,New Douglaschester,High,2021-08-14,-1.0
745,999ad741-dfd2-46fe-afcb-7d1a3347c5c1,150,Female,Barbarafurt,Medium,2020-07-08,150.0
750,f1f5c413-2160-4dac-97e1-be254637d804,150,Female,Joshuahaven,High,2021-07-24,150.0
772,57dbd7f5-3428-4452-82f8-0c140234a864,150,Female,Jacobshire,Medium,2022-10-20,150.0
783,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,-1,Female,Christinaburgh,Medium,2023-02-26,-1.0
798,b07eb18e-8b83-4ec1-b0cf-ec3e5cfbd799,150,Male,Tinaland,Low,2023-08-21,150.0
806,a4a6c9aa-bbbf-4155-9100-4f770078551d,-1,Male,Curtistown,High,2020-01-19,-1.0
823,cb57520c-e9f2-42e1-927e-facd8e57c1a4,150,Female,East Michelletown,High,2023-06-07,150.0
1021,0c67f7ad-06a0-4f16-a1ca-f8e5fb659fa2,150,Male,Port Eric,NaN,2020-07-15,150.0
1136,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,-1,Female,Adrianhaven,Low,2024-01-10,-1.0
1138,63a65dd1-0453-4bbf-b80d-70eada1d7075,-1,Male,North Rhonda,Medium,2023-09-20,-1.0
1273,63e0ea43-1c66-4d4d-9e5a-7eab3f40c858,150,Female,Bennettshire,Low,2021-11-18,150.0
1315,10b5f508-60ed-4894-9d2d-f0150493849f,150,Male,Mcguireville,Low,2023-05-13,150.0
1420,081df560-dc5f-45d3-87ac-9992b5050133,150,Male,Langchester,High,2022-12-02,150.0
1458,87c6dfbe-82fa-4ca2-a49b-717454462841,-1,Female,Sarahburgh,Low,2024-06-20,-1.0
1505,b990c65a-3491-4687-bf14-4613e85e5b4a,150,Male,Martinburgh,High,2022-05-16,150.0
1521,284f932d-040d-41f2-8915-578af3bf7a98,-1,Male,Shepherdport,NaN,2024-05-02,-1.0
1611,630c9919-341b-4dea-95a8-4956754d623c,-1,Female,Martinezbury,Low,2020-07-16,-1.0
1711,7c1ced6e-c1ff-4cc8-ad63-480b951db4e7,-1,Female,Lake Joseph,Low,2023-08-18,-1.0
1730,b5045ac9-31cb-45e4-b43e-73581751c807,150,Male,Port Julie,Medium,2023-01-20,150.0
1768,5050eefe-2392-4d18-b4b6-913d42b9f62b,-1,Female,Alexanderstad,High,2021-02-20,-1.0
1800,df5cdd30-cd21-4e24-850a-c77ef1aceeaf,-1,Male,North Stephanie,NaN,2022-08-05,-1.0
1813,4482342c-d241-457d-9ab9-7f6d86f88f35,150,Male,Lake Amberport,High,2019-12-04,150.0
1846,490e8d72-d72c-4e00-b790-d91b98299c68,-1,Female,North Jeffreystad,Medium,2019-12-07,-1.0
1860,edc655e1-174f-455f-8ae3-f12ff758a281,150,Female,New Lonnie,Medium,2023-09-24,150.0
1890,0463c692-67ef-4503-a150-fcc91f1bc488,-1,Female,Lake Brianna,Low,2023-04-17,-1.0
1962,d24275e1-2bd3-49f8-9596-9f962be5127c,-1,Female,North Mariahbury,High,2024-04-03,-1.0
1990,8f913b3f-65fa-4fff-b402-bff340ad86c8,150,Male,Patriciafort,Low,2021-12-19,150.0
2036,e3d2d960-e591-4007-b0b4-2748a6ae0963,150,Male,West Jessicaview,NaN,2020-01-22,150.0
2123,3992dc40-20ac-47a9-b735-ea72c8ae772b,150,Female,North Ernest,Medium,2023-07-02,150.0
2132,ff6d25c2-baeb-46ab-8ce4-4c39bde83c5a,-1,Male,Port Elizabeth,Medium,2024-05-15,-1.0
2204,f0b50780-920a-4030-b0ef-b9789bb689d3,-1,Female,Javierside,NaN,2020-11-03,-1.0
2210,f98e8c9e-20c4-4410-b99b-f3ae2938e950,150.0,Male,Morrisonberg,High,2024-03-23,150.0
2248,c849d8b0-2b3a-414b-842f-3f4c8bd24004,-1,Male,South Sarahberg,Medium,2024-05-02,-1.0
2275,506d313d-3e4e-4d80-8761-3b375852ffef,-1.0,Male,Port Vanessaburgh,Medium,2022-05-10,-1.0
2426,3ff07f9f-8d50-442d-b5b7-0d84510af6be,-1,Female,Lake Lindseychester,Medium,2023-10-12,-1.0
2440,9da7e2c1-6a6f-4930-bf58-24fb85191670,-1,Female,Ramirezberg,Medium,2021-01-22,-1.0

#### Non-Numeric Transaction Amount Review

Transaction Amount values that could not be converted to numeric form are
examined before determining treatment.

The review checks whether the values contain recoverable transaction
amounts or represent non-numeric information that cannot be used as a
monetary measure.

In [ ]:
print("Non-Numeric Amount Values")

display(
    transactions_raw.loc[
        invalid_amount_mask,
        "Amount"
    ].value_counts(dropna=False)
)

print("\nAffected Transaction Records")

display(
    transactions_raw.loc[
        invalid_amount_mask,
        [
            "TransactionID",
            "CustomerID",
            "TransactionDate",
            "Amount",
            "ProductCategory",
            "PaymentMethod"
        ]
    ].head(50)
)

Non-Numeric Amount Values

Amount
Free    30
Name: count, dtype: int64

Affected Transaction Records

,TransactionID,CustomerID,TransactionDate,Amount,ProductCategory,PaymentMethod
5,78dfb45e-16e0-4ecc-8f67-f2e210c31c3e,3eccdcf9-e8ce-4e44-9f62-8bef88e70672,2024-04-07,Free,NaN,Credit Card
59,611876da-a85d-4969-8d84-7a9cf8ddbf59,04b0cd53-29ca-48ef-b4b7-9520a2939288,2023-09-02,Free,Automotive,PayPal
161,b7e042d1-7ad0-430d-8984-82dfa9048a64,56058449-276a-417e-b6c6-f8853b1d2659,2024-05-29,Free,NaN,Credit Card
250,cd29e076-8de9-416b-bc0e-fecb61c8baff,7e3256b2-49d1-419e-a30c-8504f446e64e,2023-10-27,Free,Home & Garden,Credit Card
432,36d14454-fb95-4b19-a574-e137ddb55528,ccf4d58b-5087-45c8-a8f8-bb99be9a13d1,2024-02-09,Free,Electronics,Credit Card
755,a7e2384a-9efb-4519-aa01-683daa01d6e9,1fbbc3ad-d48f-4e64-9ef7-4e58277af29a,2024-04-14,Free,Electronics,Debit Card
764,983162b4-b06e-41d3-956c-2c3eed3cf6c4,e06f0e16-8e48-483b-b103-9f105b139ca8,2023-08-18,Free,Home & Garden,Debit Card
786,f9cdb10b-2e40-4df2-a7c4-3614151587b6,481bcc62-9dcb-4766-bbdd-79f5554d73f8,2024-04-11,Free,Electronics,PayPal
853,519f279a-5e5d-4a98-8a28-6c04e66c62b7,77280a9d-3fc9-4140-bc4e-b85cd5c7a8b1,2022-09-26,Free,Electronics,PayPal
854,87459f1a-8873-450f-8b7d-ac4c7b41ba90,68afa4cc-e2d5-4150-b358-2e14e7508721,2023-07-20,Free,Electronics,Bank Transfer
1008,49fd3057-88b4-4896-bf5b-2e501b76df5b,8f440758-f8ac-44ee-9f83-51d9bde6d101,2022-07-02,Free,Electronics,Credit Card
1041,8b7c550f-4acc-4333-a144-cc4d75aa8d1a,2de49c7c-32ae-4ba8-b058-622a090d7094,2024-01-24,Free,Home & Garden,PayPal
1179,a6ea336a-46dd-480a-9dff-232bc67e956c,9f9f72a5-0ec8-4847-ab9c-d7694d86f53a,2024-02-11,Free,Home & Garden,Credit Card
1214,46dbc70f-3b20-4e27-8af2-a58801d78774,13b1dad8-724d-45e8-9ecd-912d09e4931c,2023-02-06,Free,Health & Beauty,Credit Card
1215,66f81587-2823-40f4-9f67-a51c4fb3b603,4231fa1b-073c-4bf2-94d6-22dd9dd33929,2023-09-25,Free,Clothing,Debit Card
1267,200d7d2e-ec9e-4152-865e-0e4099006397,b791d365-bf14-43ae-9939-aabd2c982866,2023-08-21,Free,Home & Garden,Debit Card
1310,8c8b85f2-5e6e-457a-899d-6c4b392d2239,321adc94-8a35-4998-bc17-0cacc00988f4,2023-08-22,Free,Home & Garden,Credit Card
1460,3e221ee0-a001-4fa5-ba4e-c3ca8f381ee8,ee802844-8070-4699-b60d-3568a7d306b6,2022-07-20,Free,Home & Garden,Bank Transfer
1534,fc58b548-8913-4fb9-a952-9f6edee9d011,99462720-beca-4890-852e-79d16990f055,2023-10-07,Free,Automotive,PayPal
1748,00816003-b5ea-4564-a8f6-d25b9e44bbcf,69c0971b-1c85-429a-aa61-496f9c0a4410,2023-04-02,Free,Clothing,PayPal
1777,5f18cb21-0ca3-451c-ac1d-4c1dfef1a9a4,f3dc5fd3-b7ab-4996-ad89-1954cc27849e,2022-07-29,Free,Clothing,Debit Card
1882,635c8590-2515-4c9b-97d9-8bfd0e909d8c,c5dfebb9-5891-4a1d-a50c-a6851dad85cf,2023-10-13,Free,Electronics,Bank Transfer
2121,3044af7d-d422-474b-9b9b-687880505ffe,28a886bd-0c98-4532-bbb3-4ba77a9ee275,2023-05-09,Free,Clothing,Credit Card
2556,542e0ad1-07e0-4e9e-aa47-927c93ec08ae,8f7a9b25-42c2-4cdd-8b0c-b66e1ca3e78a,2022-07-09,Free,Electronics,Bank Transfer
2608,5cb46da7-d495-45ba-8a58-23944fca1c31,309a0ae4-8bd2-4440-935a-44f504c66431,2024-04-11,Free,Clothing,Credit Card
2630,cd82917c-279f-4cc0-9763-caf8589afba1,32cef811-93ec-48b4-9fa5-e1174156e8cc,2024-02-21,Free,Clothing,Bank Transfer
2632,aa210434-2df7-48e6-acc6-c83c8cc05425,80afb9fd-6751-40b6-b4ff-f3c08e12d4c9,2023-01-17,Free,Health & Beauty,PayPal
2707,bbb31735-10e0-405a-8f39-c47df3cb5310,a7b667f7-d6c7-4fc6-b6d9-bcdeea32297c,2022-12-12,Free,Clothing,PayPal
2794,de784b38-50b9-4cc0-b919-395195cae216,7d0dffb7-45b1-456f-b4fa-512b3d1ba9ce,2022-11-08,Free,Health & Beauty,Debit Card
3005,022cfd97-a8e8-4e50-8700-2720d52bfd75,778da54b-8f96-4609-a21b-bba3d7f071ea,2022-08-23,Free,Health & Beauty,PayPal

#### Negative Transaction Amount Review

Negative transaction amounts are reviewed before being classified as
invalid.

A negative value could represent a data-entry problem, but it could also
have a specific business meaning such as a refund or reversal.

Because the supplied dataset does not include an explicit transaction-type
field, the available related variables are examined before determining
treatment.

In [ ]:
negative_amount_review = transactions_raw.loc[
    negative_amount_mask,
    [
        "TransactionID",
        "CustomerID",
        "TransactionDate",
        "Amount",
        "ProductCategory",
        "PaymentMethod"
    ]
].copy()

negative_amount_review["AmountNumeric"] = amount_numeric.loc[
    negative_amount_mask
]

print("Negative Amount Summary")

display(
    negative_amount_review["AmountNumeric"].describe()
)

print("\nNegative Amount Values")

display(
    negative_amount_review[
        "AmountNumeric"
    ].value_counts().sort_index()
)

print("\nAffected Transaction Records")

display(
    negative_amount_review.head(50)
)

Negative Amount Summary

count     40.0
mean    -100.0
std        0.0
min     -100.0
25%     -100.0
50%     -100.0
75%     -100.0
max     -100.0
Name: AmountNumeric, dtype: float64

Negative Amount Values

AmountNumeric
-100.0    40
Name: count, dtype: int64

Affected Transaction Records

,TransactionID,CustomerID,TransactionDate,Amount,ProductCategory,PaymentMethod,AmountNumeric
274,814d25d8-690b-45bb-96c9-b7a3e92a61db,e6f4ae74-d58d-4770-8ebc-89c1f8778a6d,2023-01-25,-100,NaN,PayPal,-100.0
319,fb908e24-4c1e-4e24-a1b0-62465fa0515c,b91999f9-b7ed-4da4-a285-1dafae98e21d,2024-03-22,-100,Health & Beauty,Debit Card,-100.0
334,487ecd9b-57c8-447c-a2a8-e55477ba0d6d,a800ccba-e1ca-4f52-ad9f-14f3432699c9,2023-09-25,-100,Clothing,Bank Transfer,-100.0
381,f53b16b4-d042-44ca-a073-4acdd546b519,a94e3f55-2f0e-432e-8706-9815c4371376,2024-01-06,-100,Home & Garden,PayPal,-100.0
447,f35cadbe-6ae1-427d-8b41-5749cc1173e6,ca645b4d-28a4-42ec-99a7-8000d38bf2e0,2023-06-18,-100,Electronics,Bank Transfer,-100.0
449,77954a26-9a04-4806-b525-7f33f554d255,a7c29c33-e968-4d84-82cd-1269ed1e7c1e,2022-09-11,-100,Home & Garden,Credit Card,-100.0
476,1074d2cf-a7d5-4ebd-baa9-4660b2df5ec8,ac6b4d61-3d14-4362-b226-8c0c5786d6df,2023-07-17,-100,Health & Beauty,Credit Card,-100.0
500,c59819cc-cf92-4929-ad22-ef3435187be9,ffe9a403-ac25-4aad-a809-ac9687ff3fcd,2023-04-01,-100,Automotive,Bank Transfer,-100.0
563,f39c8b1d-595a-4656-8108-25981bf3fa14,f05ec030-ac96-417d-a73c-e3ca3adc1a30,03/04/2023,-100,Electronics,Debit Card,-100.0
652,f99eba1f-0092-4487-b753-9fce61e0ca26,f56e56b7-bbde-455c-b570-61cd2005b4e4,2023-02-05,-100,Automotive,PayPal,-100.0
702,64138a25-3a63-41fd-aa81-f74231597191,ab87ecef-f7ea-49b0-8c50-c31442ad5c46,2022-12-04,-100,Home & Garden,Debit Card,-100.0
727,adbe44db-78ec-408b-80ad-e119e0f58123,db10c135-1080-4fce-b653-d5a5fb572fa8,2024-05-13,-100,Home & Garden,Credit Card,-100.0
1129,eed1a5a0-4a6b-40b1-9c43-abfeff1a7735,6b6cd86a-d0af-48ab-ada5-e596f726cffa,2024-06-02,-100,Clothing,Credit Card,-100.0
1240,6f57c9c3-0c11-4d34-9392-08eb6b91fd0e,03fac2e6-f130-4cf6-b8b8-2f147c2fe60a,2024-05-21,-100,Home & Garden,Debit Card,-100.0
1241,09b0508b-a705-48d0-8594-5b7d85d024eb,799943c7-3b71-4f24-9b16-c2fcaf9b3871,2022-11-08,-100,Automotive,PayPal,-100.0
1263,db154379-42a3-4ae0-a4d3-29c53226f8a1,38d746bd-c227-416a-aa28-610ffd379e58,2024-06-22,-100,Electronics,Bank Transfer,-100.0
1298,f01412a4-6d1c-46ce-a912-7b0a8c2a7596,8375d38f-88e2-4c33-9647-f8b8b55b1426,2023-02-23,-100.0,Health & Beauty,Bank Transfer,-100.0
1577,6cfe5871-8524-4d81-abaa-a54fdd3c873d,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,2023-06-11,-100,Automotive,PayPal,-100.0
1705,084e56a5-99eb-48df-801e-bda9cd5ff591,f102f93b-f32c-41d3-adcc-25e02a67c34f,2023-11-03,-100,Electronics,PayPal,-100.0
1808,ab723d41-abdc-412b-b3b9-68796b746a8e,28097c07-e810-4e64-8eae-bff2abd81bc1,2023-07-11,-100,Automotive,Credit Card,-100.0
1907,d7740397-087b-49bb-bf31-2a50ca0e70f6,b7b84b81-c61b-4f23-b3db-b18010484122,2023-03-14,-100,Clothing,PayPal,-100.0
1942,5b6352cf-da83-46ab-a0ff-79da90691392,e7e5e8fe-5fdd-43e6-92e1-5ea3e399486e,2023-12-25,-100,Electronics,PayPal,-100.0
1994,0705d2f0-ab60-4664-b65e-971e3e2c27d5,d968cee0-3524-42d4-a0f7-5fe6e8284890,2023-10-09,-100,Clothing,Debit Card,-100.0
2191,4b4ddbb6-36cf-44eb-8e7a-b27c529f1cff,1f5c50db-9c55-4bbc-8a93-c7994a7bb3d3,2022-12-20,-100,Automotive,Bank Transfer,-100.0
2239,ddebc095-ed7c-4c6e-87d8-e7f00c0b50c6,448245da-3a0b-4f52-a40f-a25ca0a2fb6b,2023-01-24,-100,Home & Garden,Credit Card,-100.0
2319,c100f59f-61aa-4c82-825e-dedfde73917b,21098ed8-fac6-4727-8f0c-953365b6c837,2023-02-14,-100,Home & Garden,PayPal,-100.0
2443,0e5b9cc6-9b94-45fc-8bf8-b8031cd987a7,ce3f403f-b955-4364-ae22-bf351381e01f,2023-04-21,-100,Home & Garden,Bank Transfer,-100.0
2467,33ce68ea-42c4-48eb-8631-c8f611d2a330,0e678ba1-7b5f-46aa-8b5a-6dc1190373be,2023-03-01,-100,Clothing,Debit Card,-100.0
2480,341e25ef-3062-484d-8d07-cc4e0ddb996f,eca27290-1c40-48c6-b0a5-8afedd9be099,2022-08-02,-100,Clothing,Credit Card,-100.0
2516,35faff4a-1bf8-4b42-a7ac-847b4970f4b8,7e280186-770e-4c4a-b330-73dd471f956a,2023-09-19,-100,Home & Garden,Bank Transfer,-100.0
2522,52bb2a8d-acab-45f9-9817-6e9fe7567824,bfe55c3b-668e-485d-9476-670acd50b12b,2024-05-03,-100,Health & Beauty,Debit Card,-100.0
2621,c0d0ae2b-eb99-49e5-89ad-0624ad136056,8d435ee0-fa33-4553-880a-e26511ac3921,2023-03-27,-100,Home & Garden,Bank Transfer,-100.0
2737,b401a1e8-6cc3-4ab6-bff4-c41a3847329a,c56a1423-e1b0-45c1-974a-55f5fa029c88,2024-05-31,-100,Electronics,PayPal,-100.0
2910,e2d7a068-e92e-407a-8d48-4cf8da4a4c2c,f35c6e3f-2fac-4b7a-b713-863a0a37160c,2024-03-12,-100,Health & Beauty,PayPal,-100.0
3012,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,24b043e8-6fca-4d86-95a8-837e0ca09072,2023-06-01,-100,Health & Beauty,Debit Card,-100.0
3038,27fb25aa-f148-423f-967c-4d1764e26b29,b94b3531-591d-445c-b282-dcacb0baca5b,2024-04-18,-100,Automotive,Credit Card,-100.0
3050,5f93f1dc-0363-4e69-979b-f5d58fd42658,a9af986b-d677-421a-81df-3d289ce9e38f,2023-09-30,-100,NaN,Bank Transfer,-100.0
3073,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2023-05-10,-100,Electronics,Bank Transfer,-100.0
3123,5fca256b-cd5a-48fa-8b07-37f39adde8c9,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,2023-05-17,-100,Clothing,Bank Transfer,-100.0
3177,c751a808-ed8d-44d0-8c52-8253ad564c9a,3ea377e6-1156-457e-8b4e-71fa6663e6bf,2023-09-22,-100,Health & Beauty,Credit Card,-100.0

#### Zero Transaction Amount Review

Transactions with an Amount of zero are reviewed separately.

A zero value is numerically valid but may not represent an ordinary purchase.
The available transaction information is inspected before deciding whether
these records should remain in the analytical dataset.

In [ ]:
zero_amount_review = transactions_raw.loc[
    zero_amount_mask,
    [
        "TransactionID",
        "CustomerID",
        "TransactionDate",
        "Amount",
        "ProductCategory",
        "PaymentMethod"
    ]
].copy()

print("Zero Amount Records:", len(zero_amount_review))

display(
    zero_amount_review.head(50)
)

Zero Amount Records: 30

,TransactionID,CustomerID,TransactionDate,Amount,ProductCategory,PaymentMethod
134,793af848-8138-40e7-929c-67254ea56ca7,b94a126b-755e-4ee1-91f6-c5f86ceef780,2023-07-22,0,Home & Garden,PayPal
196,a6b7182d-6c74-4fa5-9491-035e49e5eb87,89480374-82ec-44e5-ae61-bbed82bfd5b1,2023-11-09,0,Electronics,Bank Transfer
308,c0ea759c-a09f-4989-bc3b-f56a0c0400d8,343ef45e-c257-47f1-bbd2-5683734d2fcd,2022-08-13,0,Home & Garden,PayPal
378,962df48f-faf1-4849-9779-0415f10cb9f3,88efac91-e005-417f-bc9e-57a5deb7f746,2023-02-08,0,Home & Garden,Credit Card
468,8e88d564-a18a-448b-9e5d-add5fef8017d,ac6b4d61-3d14-4362-b226-8c0c5786d6df,2024-05-22,0,Health & Beauty,PayPal
542,36db923e-7db3-4df0-b9c2-574410d62bba,667b0a6e-53b8-476d-be5b-215bfe49f60b,2023-09-17,0,Electronics,Bank Transfer
580,88b6ba3b-5490-4374-ad90-cd45b1c94d4b,ebccb59b-1792-4a64-a43e-ac942685ec77,2023-12-31,0,Clothing,Debit Card
591,0525dc48-b90b-4100-952a-fb163c51901c,2130fd89-6ba4-4f36-bb90-2327cf27d0d6,2022-11-12,0,Automotive,Debit Card
629,652636b6-5c72-44e1-aefb-6adce412ee75,086370e7-8884-47d7-89b0-776401a43e1c,2023-12-05,0,Electronics,Debit Card
931,35edcb11-2d5e-48ba-a1c2-8c16bbd3952a,b0180e7a-16e4-45bf-a417-0f2f5ca442bd,2023-08-31,0,Clothing,Credit Card
1116,4044222b-4470-4e79-8f53-5bdba7066c44,013c4cd9-1d0f-4004-8772-065ab426d105,2023-05-28,0,Electronics,PayPal
1228,721db31f-2972-4ff5-af51-87c8bb6360a3,34878e84-afed-4cb1-a969-08a070c6be85,2023-02-10,0,Clothing,Debit Card
1484,b6d45beb-65a6-468e-a9d2-9d29deaff58d,a420497a-653c-4a0f-bdfa-32543a7a94f6,2022-09-07,0,Automotive,Debit Card
1853,e31033dc-6e31-479f-bb56-e3e392b128d5,5713cca9-0ee4-45ef-a550-5edba478b94c,2023-09-16,0,Home & Garden,Debit Card
1886,30bb2661-984e-4949-b821-923d76483d82,1d29565d-2123-4b85-b499-92a928a5fd2e,2023-10-14,0,Automotive,Debit Card
2056,71b15f40-92c8-4acd-8c45-4a6f86e11665,b82ee981-f4ba-49e3-95de-49084a33db20,2023-06-21,0.0,Clothing,Credit Card
2070,4281591f-d839-4c2a-aea2-5cec07eee005,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,2023-04-06,0,Health & Beauty,PayPal
2109,2532b466-9d3e-4724-a5f4-b3295b4b8530,78002a64-8a6e-4d61-80a9-1bbf4c41ae76,2022-11-01,0,Health & Beauty,PayPal
2166,287c98cd-4c3c-4c01-bc3f-fd2cdfb01d78,b8f3474f-d05d-4aca-982b-6af4a856305a,2022-11-17,0,Clothing,PayPal
2256,b302b5d0-a182-48cd-bc3c-6afbbf4c72c2,cdd71e46-7539-41af-b9d5-6758abdfa2e6,2023-04-17,0,Health & Beauty,Bank Transfer
2348,83ef29d9-c82a-4138-b8c5-599af75c3d35,2fb8e79a-8243-460a-ac89-27524c8debb3,2024-01-08,0,Automotive,Credit Card
2528,af93165e-0c42-4c91-bb29-a09ad16f0dab,ea8aa9a1-7a06-4c9d-be6d-e8f856d49e1f,2024-01-25,0,NaN,Debit Card
2634,d16c6727-c72f-463e-af55-0008ae1d6975,fa7d31de-04f7-4c22-a723-2cdb144c55d7,05/11/2023,0,Home & Garden,Credit Card
2662,44750adc-cb9d-4afe-a028-ffeb07e0fbcb,651a6712-d1db-4d03-9bd0-36d9c17e1b86,2023-06-08,0,Health & Beauty,Debit Card
2712,e896f88a-9035-4f79-9b7b-ba65b0fd5285,9423d7e7-2239-478f-9a2a-5ce386882aa2,2022-08-31,0,Clothing,Credit Card
2726,3fb495d6-17d8-4d06-a679-fc0cf1b8bca3,d3b37301-dfba-4182-a0be-1da6f2186393,2022-11-29,0,Automotive,Credit Card
2727,29ba8b6d-c22c-4335-b621-250d38b06acf,4add70a0-9c64-41d8-b32e-f7f1ea06706b,2023-06-29,0,Home & Garden,Debit Card
2915,b0cd6206-3611-4b1b-b4fd-eed3849cc6bd,d60227d4-2d7b-48dd-9d91-44365360dd82,2024-03-24,0,Health & Beauty,PayPal
2994,2d2b7edf-d53d-41e4-bd8b-b7a546002e95,7fa1d4e1-e465-4d23-82c8-c096f58fb5ed,2022-07-09,0,Home & Garden,Bank Transfer
3174,185ee140-348a-4461-bd40-07a7e8535815,6a84f1a7-f636-4300-bd8d-c7f888460829,2023-10-09,0,Health & Beauty,PayPal

In [ ]:
numeric_decision_summary = pd.DataFrame({
    "Condition": [
        "Non-Numeric Age",
        "Questionable Numeric Age",
        "Non-Numeric Amount",
        "Negative Amount",
        "Zero Amount"
    ],
    "Affected Records": [
        invalid_age_mask.sum(),
        questionable_age_mask.sum(),
        invalid_amount_mask.sum(),
        negative_amount_mask.sum(),
        zero_amount_mask.sum()
    ],
    "Decision Status": [
        "Pending review",
        "Pending review",
        "Pending review",
        "Pending review",
        "Pending review"
    ]
})

display(numeric_decision_summary)

                  Condition  Affected Records Decision Status
0           Non-Numeric Age                34  Pending review
1  Questionable Numeric Age                63  Pending review
2        Non-Numeric Amount                30  Pending review
3           Negative Amount                40  Pending review
4               Zero Amount                30  Pending review

#### Final Numeric Cleaning Decisions

The numeric investigation provides sufficient evidence to establish
treatment rules before cleaning.

The decisions prioritize preservation of recoverable information while
avoiding unsupported estimation or correction.

- Non-numeric Age values recorded as `Unknown` cannot be reliably
  reconstructed and will be omitted.
- Numeric Age values below 0 or above 120 are treated as logically invalid
  for this analysis and will be omitted.
- Transaction Amount values recorded as `Free` will be converted to `0.0`
  because the value directly indicates that no monetary charge was made.
  This is treated as semantic normalization rather than imputation.
- Negative transaction amounts will be omitted because the available
  dataset does not contain a transaction-type variable that would support
  interpreting them as refunds, reversals, or other legitimate negative
  transactions.
- Zero transaction amounts will be retained because they are valid numeric
  values and there is insufficient evidence to classify them as erroneous.

These decisions are applied only to the cleaned working datasets. The raw
FinMark datasets remain unchanged.

In [ ]:
numeric_cleaning_decisions = pd.DataFrame({
    "Condition": [
        "Non-Numeric Age",
        "Questionable Numeric Age",
        "Non-Numeric Amount",
        "Negative Amount",
        "Zero Amount"
    ],

    "Affected Records": [
        invalid_age_mask.sum(),
        questionable_age_mask.sum(),
        invalid_amount_mask.sum(),
        negative_amount_mask.sum(),
        zero_amount_mask.sum()
    ],

    "Observed Values": [
        "Unknown",
        "-1 and 150",
        "Free",
        "-100",
        "0"
    ],

    "Cleaning Decision": [
        "Omit affected records",
        "Omit affected records",
        "Convert Free to 0.0",
        "Omit affected records",
        "Retain records"
    ],

    "Reason": [
        "No valid numeric age can be reconstructed without unsupported estimation",
        "Values fall outside the documented valid Age range of 0 to 120",
        "Free directly represents no monetary charge and can be represented numerically as 0.0",
        "No transaction-type field supports interpreting negative values as legitimate refunds or reversals",
        "Zero is numerically valid and there is insufficient evidence that these transactions are erroneous"
    ]
})

display(numeric_cleaning_decisions)

,Condition,Affected Records,Observed Values,Cleaning Decision,Reason
0,Non-Numeric Age,34,Unknown,Omit affected records,No valid numeric age can be reconstructed with...
1,Questionable Numeric Age,63,-1 and 150,Omit affected records,Values fall outside the documented valid Age r...
2,Non-Numeric Amount,30,Free,Convert Free to 0.0,Free directly represents no monetary charge an...
3,Negative Amount,40,-100,Omit affected records,No transaction-type field supports interpretin...
4,Zero Amount,30,0,Retain records,Zero is numerically valid and there is insuffi...

In [ ]:
display(Markdown(f"""
### Numeric Cleaning Decision Observation

The numeric investigation established the following cleaning rules:

#### Customer Age

- **{invalid_age_mask.sum()}** records contain the non-numeric value
  `Unknown` and will be omitted because no valid age can be reconstructed.

- **{questionable_age_mask.sum()}** records contain numeric Age values
  outside the accepted range of 0 to 120 and will be omitted.

#### Transaction Amount

- **{invalid_amount_mask.sum()}** records contain `Free` instead of a numeric
  Amount. These values will be normalized to **0.0** because `Free`
  explicitly represents no monetary charge.

- **{negative_amount_mask.sum()}** records contain negative transaction
  amounts. These records will be omitted because the available dataset
  does not contain information establishing a legitimate negative
  transaction type.

- **{zero_amount_mask.sum()}** records already contain numeric zero values.
  These records will be retained because there is insufficient evidence
  that a zero-value transaction is invalid.

No changes have yet been applied to the raw datasets.
"""))

### Numeric Cleaning Decision Observation

The numeric investigation established the following cleaning rules:

#### Customer Age

- **34** records contain the non-numeric value
  `Unknown` and will be omitted because no valid age can be reconstructed.

- **63** records contain numeric Age values
  outside the accepted range of 0 to 120 and will be omitted.

#### Transaction Amount

- **30** records contain `Free` instead of a numeric
  Amount. These values will be normalized to **0.0** because `Free`
  explicitly represents no monetary charge.

- **40** records contain negative transaction
  amounts. These records will be omitted because the available dataset
  does not contain information establishing a legitimate negative
  transaction type.

- **30** records already contain numeric zero values.
  These records will be retained because there is insufficient evidence
  that a zero-value transaction is invalid.

No changes have yet been applied to the raw datasets.

Final guides for clean up:

Missing values          → omit
Exact duplicates        → remove

Age = Unknown           → omit
Age < 0 or > 120        → omit

Amount = Free           → convert to 0.0
Amount < 0              → omit
Amount = 0              → retain

Mixed valid dates       → normalize YYYY-MM-DD

Category formatting     → no change
Sentiment categories    → preserve

Orphan CustomerIDs      → none found

Identifiers             → retain for integrity/joins
                          not ordinary ML features

### Conflicting Identifier Review

Exact duplicate rows have already been identified. However, record-level
identifiers that are expected to be unique must also be checked after exact
duplicates are removed.

The following identifiers are expected to represent one record:

- `CustomerID` in Customer Demographics
- `TransactionID` in Customer Transactions
- `InteractionID` in Social Media Interactions

If the same identifier appears in multiple non-identical records, the
records are treated as conflicting because the available data does not
provide sufficient evidence to determine which version is authoritative.

No conflicting record is automatically retained based only on row order.

In [ ]:
def find_conflicting_identifiers(df, id_column):
    deduplicated = df.drop_duplicates()

    conflict_mask = deduplicated.duplicated(
        subset=id_column,
        keep=False
    )

    return (
        deduplicated.loc[conflict_mask]
        .sort_values(id_column)
    )


demographic_conflicts = find_conflicting_identifiers(
    demographics_raw,
    "CustomerID"
)

transaction_conflicts = find_conflicting_identifiers(
    transactions_raw,
    "TransactionID"
)

social_conflicts = find_conflicting_identifiers(
    social_raw,
    "InteractionID"
)


conflict_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Conflicting Identifiers": [
        demographic_conflicts["CustomerID"].nunique(),
        transaction_conflicts["TransactionID"].nunique(),
        social_conflicts["InteractionID"].nunique()
    ],
    "Affected Rows": [
        len(demographic_conflicts),
        len(transaction_conflicts),
        len(social_conflicts)
    ]
})

display(conflict_summary)

                     Dataset  Conflicting Identifiers  Affected Rows
0      Customer Demographics                       23             46
1      Customer Transactions                       15             30
2  Social Media Interactions                       20             40

In [ ]:
print("Customer Demographic Conflicts")
display(demographic_conflicts.head(50))

print("\nTransaction Conflicts")
display(transaction_conflicts.head(50))

print("\nSocial Media Interaction Conflicts")
display(social_conflicts.head(50))

Customer Demographic Conflicts

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
3024,08995799-8d0f-40d6-986b-452074709b5f,61.0,Male,New Lukeville,Medium,2020-03-28
1536,08995799-8d0f-40d6-986b-452074709b5f,61.0,Male,New Lukeville,Medium,15/11/2019
3085,1e9e7dcb-e612-46d3-bae6-0c2f47fa0220,44.0,Female,Brianmouth,Medium,07/11/2019
304,1e9e7dcb-e612-46d3-bae6-0c2f47fa0220,44.0,Female,Brianmouth,Medium,2022-07-28
3083,29436bcf-d6f8-44d1-a856-0794abb562ab,68.0,Female,New Fred,Low,12/03/2020
754,29436bcf-d6f8-44d1-a856-0794abb562ab,68.0,Female,New Fred,Low,2021-09-01
3051,2cd16dfc-d7b0-47ec-9999-b018daea7f8d,52.0,Female,Lake Carloshaven,Medium,2024-05-02
2106,2cd16dfc-d7b0-47ec-9999-b018daea7f8d,Unknown,Female,Lake Carloshaven,Medium,2024-05-02
1238,3814b8e4-cade-4665-86af-dda3e3628f17,32.0,Female,Port Bonnieshire,Medium,2021-06-25
3004,3814b8e4-cade-4665-86af-dda3e3628f17,150,Female,Port Bonnieshire,Medium,2021-06-25
3165,48313b18-ccdb-4946-b958-1ebfc92dcc2a,59.0,Male,South Andrea,High,2020-02-26
338,48313b18-ccdb-4946-b958-1ebfc92dcc2a,Unknown,Male,South Andrea,High,2020-02-26
539,50465bde-6a9a-466d-804a-a8f046809a23,-1,Male,Harrismouth,High,2023-08-02
3041,50465bde-6a9a-466d-804a-a8f046809a23,35.0,Male,Harrismouth,High,2023-08-02
3145,5050eefe-2392-4d18-b4b6-913d42b9f62b,20.0,Female,Alexanderstad,High,2021-02-20
1768,5050eefe-2392-4d18-b4b6-913d42b9f62b,-1,Female,Alexanderstad,High,2021-02-20
3132,6b2f8f03-ab9e-48a6-a07e-10e794b04fe0,-1,Male,Lake Karen,Low,2023-04-04
174,6b2f8f03-ab9e-48a6-a07e-10e794b04fe0,65.0,Male,Lake Karen,Low,2023-04-04
3138,7544489f-ec7e-48af-bec6-b6eab94a6e5c,150,Male,South Jared,High,2024-03-02
2339,7544489f-ec7e-48af-bec6-b6eab94a6e5c,64.0,Male,South Jared,High,2024-03-02
3150,76c1d696-0f1c-44b5-b749-8859545658eb,34.0,Female,South Frankside,High,2020-05-14
1355,76c1d696-0f1c-44b5-b749-8859545658eb,Unknown,Female,South Frankside,High,2020-05-14
1581,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.0,Male,New Anthonyland,High,07/01/2021
3183,7eb7f7df-9b0a-416a-829e-bcf4d8bd57dc,55.0,Male,New Anthonyland,High,2022-07-23
2082,83355281-fda3-4776-9f9d-a812243c3b56,31.0,Female,Ashleychester,Medium,23/02/2022
3062,83355281-fda3-4776-9f9d-a812243c3b56,31.0,Female,Ashleychester,Medium,2024-04-15
911,835384f5-c976-481d-8961-cc827dc62c6b,60.0,Male,Stricklandport,High,01/07/2019
3087,835384f5-c976-481d-8961-cc827dc62c6b,60.0,Male,Stricklandport,High,2023-09-30
999,890f10ce-36f6-4993-9a2e-a00dfdf01609,33.0,Female,Denisehaven,Low,2022-09-04
3149,890f10ce-36f6-4993-9a2e-a00dfdf01609,33.0,Female,Denisehaven,Low,27/05/2021
1684,89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2,55.0,Female,New Michael,Low,2022-03-03
3119,89ca5faa-aba9-4b14-b3cd-cc6bf7fd95a2,55.0,Female,New Michael,Low,18/01/2024
2773,9612ee49-09dd-4f55-9524-9eb341efa2b9,Unknown,Male,North Breanna,High,2020-07-30
3043,9612ee49-09dd-4f55-9524-9eb341efa2b9,28.0,Male,North Breanna,High,2020-07-30
225,b72f2a59-aab0-447d-bb31-9bdc1405cc72,34.0,Female,West Jason,High,10/06/2024
3162,b72f2a59-aab0-447d-bb31-9bdc1405cc72,34.0,Female,West Jason,High,2021-09-19
1383,bb07fa4a-8680-4b77-b1ad-5d2f67570252,52.0,Male,Port Davidtown,High,06/08/2019
3078,bb07fa4a-8680-4b77-b1ad-5d2f67570252,52.0,Male,Port Davidtown,High,2020-11-06
1542,bbe76a26-234f-4a70-b71f-fa9b183f6353,57.0,Male,Gregoryfurt,High,2020-06-23
3178,bbe76a26-234f-4a70-b71f-fa9b183f6353,Unknown,Male,Gregoryfurt,High,2020-06-23
160,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,07/07/2019
3195,bbf7c36f-3745-4d3a-9e33-f927c2755f65,45.0,Female,Roberttown,Medium,2023-02-17
2551,c2351d11-59fe-4630-a6df-e01bc343de33,68.0,Female,East Pamela,NaN,15/06/2022
3079,c2351d11-59fe-4630-a6df-e01bc343de33,68.0,Female,East Pamela,NaN,2022-02-04
3186,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,41.0,Female,Adrianhaven,Low,2024-01-10
1136,ce5cf079-859b-43fa-9609-c6bb7e12c6b7,-1,Female,Adrianhaven,Low,2024-01-10

Transaction Conflicts

,CustomerID,TransactionID,TransactionDate,Amount,ProductCategory,PaymentMethod
2118,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,586.87,Health & Beauty,PayPal
3005,778da54b-8f96-4609-a21b-bba3d7f071ea,022cfd97-a8e8-4e50-8700-2720d52bfd75,2022-08-23,Free,Health & Beauty,PayPal
3174,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,0,Health & Beauty,PayPal
413,6a84f1a7-f636-4300-bd8d-c7f888460829,185ee140-348a-4461-bd40-07a7e8535815,2023-10-09,953.86,Health & Beauty,PayPal
3038,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,2024-04-18,-100,Automotive,Credit Card
431,b94b3531-591d-445c-b282-dcacb0baca5b,27fb25aa-f148-423f-967c-4d1764e26b29,30/07/2022,506.96,Automotive,Credit Card
2081,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,504.42,Electronics,Bank Transfer
3073,e7cf6999-b4ec-4ce4-bb09-bfd18d61d933,2e0b66a9-af5d-4cf9-bb60-55ab2932edee,2023-05-10,-100,Electronics,Bank Transfer
3050,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,-100,NaN,Bank Transfer
220,a9af986b-d677-421a-81df-3d289ce9e38f,5f93f1dc-0363-4e69-979b-f5d58fd42658,2023-09-30,125.77,NaN,Bank Transfer
3123,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,-100,Clothing,Bank Transfer
1093,8de3d5b9-1f1a-4bd7-b242-6cb09d7f3609,5fca256b-cd5a-48fa-8b07-37f39adde8c9,2023-05-17,764.92,Clothing,Bank Transfer
2371,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,05/04/2023,NaN,Home & Garden,Bank Transfer
3094,321acf6c-c401-4f7b-9835-bfb7cd5e48ff,62186b07-9cda-44c5-bf76-bdb0f97aaf39,2023-02-04,NaN,Home & Garden,Bank Transfer
629,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,0,Electronics,Debit Card
3153,086370e7-8884-47d7-89b0-776401a43e1c,652636b6-5c72-44e1-aefb-6adce412ee75,2023-12-05,974.25,Electronics,Debit Card
3048,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,2023-05-10,591.61,Clothing,Debit Card
2690,1ffded5f-b38d-45b7-943d-4100779c3599,6c2c5c2b-7601-41dc-9f56-4009de6f3cea,10/06/2024,591.61,Clothing,Debit Card
3105,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,27/03/2024,634.41,NaN,PayPal
283,4aab54a1-b555-48ec-9b0f-0e87abdcc45b,7202af3a-448f-4970-9674-40f736cfdfde,2023-02-26,634.41,NaN,PayPal
940,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,2022-07-14,272.68,Clothing,Debit Card
3164,79fc606a-c02c-4c39-b065-3e88a59b366c,7fbe5cc4-a35e-4e8e-89d7-7b439659b9f6,20/07/2022,272.68,Clothing,Debit Card
2610,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,766.97,Health & Beauty,Credit Card
3177,3ea377e6-1156-457e-8b4e-71fa6663e6bf,c751a808-ed8d-44d0-8c52-8253ad564c9a,2023-09-22,-100,Health & Beauty,Credit Card
1639,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,446.84,Health & Beauty,Debit Card
3012,24b043e8-6fca-4d86-95a8-837e0ca09072,dc9453eb-3922-4a5f-91c0-ccb226ca91f7,2023-06-01,-100,Health & Beauty,Debit Card
807,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,2023-03-23,50.07,Automotive,Bank Transfer
3157,7c7df909-aa25-48c7-af9d-6ebe714b28b6,eb26a4f4-5af2-4e25-b1f2-fd0de5583f7b,10/08/2022,50.07,Automotive,Bank Transfer
3113,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,2024-03-05,252.7,Electronics,Debit Card
563,f05ec030-ac96-417d-a73c-e3ca3adc1a30,f39c8b1d-595a-4656-8108-25981bf3fa14,03/04/2023,-100,Electronics,Debit Card

Social Media Interaction Conflicts

,CustomerID,InteractionID,InteractionDate,Platform,InteractionType,Sentiment
374,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,29/04/2024,Instagram,Like,Positive
3005,11b046f0-b091-4bfb-b0f4-df58bfea039a,01f1c8c8-df21-4d75-adbb-feb6d4c84317,2024-03-20,Instagram,Like,Positive
3093,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Very Positive
2183,2ddc8052-fbbe-471c-a43e-54b81467423d,04391eb2-8391-44d8-9f45-29edcde96e5d,2023-11-30,Twitter,Share,Negative
2532,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Very Positive
3166,e06f0e16-8e48-483b-b103-9f105b139ca8,071a2657-12a8-4216-9c64-baf9ab5c9420,2024-04-30,Twitter,Share,Neutral
3084,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,24/01/2024,Twitter,Comment,Negative
2490,68afa4cc-e2d5-4150-b358-2e14e7508721,0942889b-a3a9-4039-b4b0-12fb8714c95f,2024-06-14,Twitter,Comment,Negative
3017,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,04/06/2024,Instagram,Like,Positive
2135,a44b6ca5-c73e-4f7a-919c-617931e33a29,13b59881-5aaf-4510-9dcf-4f9d116bf645,2023-07-28,Instagram,Like,Positive
1487,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Negative
3130,ef10b8a1-1014-4edf-a80e-207b7790e894,1966cdba-7e47-48b6-ae29-dd8fbead8527,2023-07-19,Twitter,Comment,Very Negative
3141,54c10762-4c2c-4b9a-a602-d0069520ab2b,1c28fcb7-81fc-462c-a0a3-785f00070cd7,2024-03-14,Facebook,Like,Positive
186,54c10762-4c2c-4b9a-a602-d0069520ab2b,1c28fcb7-81fc-462c-a0a3-785f00070cd7,03/05/2024,Facebook,Like,Positive
2672,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,NaN
3194,5711d1af-71f2-4b99-a965-3ffdc39d32c8,1c2f510a-5ab5-4575-8f62-8ba8decf1302,2024-06-29,Twitter,Share,Negative
2603,fd7e416c-1740-490d-b816-d909294eaa21,1d1c2f54-2b21-4004-a2ca-2983b01b0242,2023-11-30,Instagram,Share,Neutral
3021,fd7e416c-1740-490d-b816-d909294eaa21,1d1c2f54-2b21-4004-a2ca-2983b01b0242,17/07/2023,Instagram,Share,Neutral
946,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Very Negative
3042,a60e0cb6-7b43-44f2-956a-16caae372e9f,37ce93d2-27b5-478f-808c-3095cae7fae1,2023-10-22,Twitter,Comment,Positive
2881,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,2023-11-30,Instagram,Share,Positive
3146,ce2ece8f-91c3-420a-9d80-8b1f5051dc77,3a30bab5-53a0-4169-8244-419e2459dcd9,17/06/2024,Instagram,Share,Positive
3040,c0c0ce5a-4539-4013-abca-d0a3e41b4e2a,4639a6fd-3d89-4e1d-b783-f226eb92f14f,23/07/2023,Twitter,Comment,Negative
1294,c0c0ce5a-4539-4013-abca-d0a3e41b4e2a,4639a6fd-3d89-4e1d-b783-f226eb92f14f,2023-11-24,Twitter,Comment,Negative
3126,9b8179f4-f187-4cfd-b12a-0c182539f178,8570854d-62ce-4c74-8a2e-0b85ccc5774e,2024-02-22,Instagram,Comment,Neutral
2701,9b8179f4-f187-4cfd-b12a-0c182539f178,8570854d-62ce-4c74-8a2e-0b85ccc5774e,15/04/2024,Instagram,Comment,Neutral
3120,c3547dd4-61cc-495c-a7a2-b103bbae3835,85cb819c-9451-4028-9ddd-132c55260a68,2023-10-23,Twitter,Share,Positive
2753,c3547dd4-61cc-495c-a7a2-b103bbae3835,85cb819c-9451-4028-9ddd-132c55260a68,23/08/2023,Twitter,Share,Positive
1635,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,14/05/2024,Twitter,Like,Neutral
3173,b7b84b81-c61b-4f23-b3db-b18010484122,93d2d3e1-841e-4ece-91c1-3b1998a4cab8,2023-12-16,Twitter,Like,Neutral
3061,a56b8bed-1d7a-4cc2-abeb-d847aac0ff74,98cf7859-e4a9-465b-96fe-ed51a1f1aa92,2024-06-04,Facebook,Like,NaN
1240,a56b8bed-1d7a-4cc2-abeb-d847aac0ff74,98cf7859-e4a9-465b-96fe-ed51a1f1aa92,2024-06-04,Facebook,Like,Positive
3034,3ea377e6-1156-457e-8b4e-71fa6663e6bf,9996e3b4-8270-4b04-a675-e00fe91dd835,2023-08-12,Facebook,Like,Positive
2606,3ea377e6-1156-457e-8b4e-71fa6663e6bf,9996e3b4-8270-4b04-a675-e00fe91dd835,07/08/2023,Facebook,Like,Positive
2937,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Very Positive
3091,0831f0ad-bf6b-4023-b1bf-acea2388fcf3,a229e2d8-fd5d-44a1-805e-5281a52badf7,2023-12-27,Twitter,Comment,Negative
3175,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Negative
44,5659a8c6-0397-4396-b561-52ec1c8a760b,d7f6806b-f348-431e-9198-07f0685d8d8e,2024-01-28,Facebook,Share,Very Negative
3170,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,NaN,Like,Very Negative
2662,4d20c2b1-2f8a-4066-902c-bd068c2adccc,e5be1d7a-fdba-4e91-8674-577ac01cddf0,2024-05-16,NaN,Like,Positive

#### Conflicting Identifier Cleaning Decision

Non-identical records sharing the same record-level identifier cannot be
reliably reconciled from the supplied data.

Because there is no authoritative variable that establishes which record
is correct, all records belonging to unresolved conflicting identifiers
will be omitted from the cleaned dataset.

This avoids arbitrarily retaining one conflicting record based only on
its position in the source file.

## Data Cleaning

Separate working copies are created from the verified raw datasets.

All cleaning operations are applied only to these working copies. The
original raw DataFrames remain unchanged so that the preprocessing process
can be audited and reproduced.

In [ ]:
# CREATE CLEANED WORKING COPIES
# Separate copies of the raw datasets are created before cleaning.
# All changes will be applied only to the _clean DataFrames so the
# original raw datasets remain unchanged for comparison and auditing.

demographics_clean = demographics_raw.copy()
transactions_clean = transactions_raw.copy()
social_clean = social_raw.copy()

print("Cleaned working copies created.")

Cleaned working copies created.

In [ ]:
# CREATE CLEANING AUDIT LOG
# This log records the number of rows before and after each cleaning step.
# It provides evidence of how preprocessing affects each dataset and will
# support the final before-versus-after summary.

cleaning_log = []

def log_cleaning_step(dataset, step, before_rows, after_rows):
    cleaning_log.append({
        "Dataset": dataset,
        "Cleaning Step": step,
        "Rows Before": before_rows,
        "Rows After": after_rows,
        "Rows Removed": before_rows - after_rows
    })

print("Cleaning audit log initialized.")

Cleaning audit log initialized.

In [ ]:
# NORMALIZE COLUMN NAMES
# Column names are converted to snake_case for consistent and readable
# Pandas operations. Only column labels are changed. Dataset values remain
# unchanged.

import re

def to_snake_case(column_name):
    first_pass = re.sub(
        r"(.)([A-Z][a-z]+)",
        r"\1_\2",
        column_name.strip()
    )

    return re.sub(
        r"([a-z0-9])([A-Z])",
        r"\1_\2",
        first_pass
    ).lower()


demographics_clean.columns = [
    to_snake_case(column)
    for column in demographics_clean.columns
]

transactions_clean.columns = [
    to_snake_case(column)
    for column in transactions_clean.columns
]

social_clean.columns = [
    to_snake_case(column)
    for column in social_clean.columns
]

print("Customer Demographics:")
print(demographics_clean.columns.tolist())

print("\nCustomer Transactions:")
print(transactions_clean.columns.tolist())

print("\nSocial Media Interactions:")
print(social_clean.columns.tolist())

Customer Demographics:
['customer_id', 'age', 'gender', 'location', 'income_level', 'signup_date']

Customer Transactions:
['customer_id', 'transaction_id', 'transaction_date', 'amount', 'product_category', 'payment_method']

Social Media Interactions:
['customer_id', 'interaction_id', 'interaction_date', 'platform', 'interaction_type', 'sentiment']

In [ ]:
# REMOVE CONFIRMED EXACT DUPLICATES
# Fully identical rows are removed because they repeat the same information
# and may overrepresent observations during later analysis.
# The number of removed records is recorded in the cleaning audit.

before = len(demographics_clean)

demographics_clean = (
    demographics_clean
    .drop_duplicates()
    .copy()
)

log_cleaning_step(
    "Customer Demographics",
    "Remove exact duplicate rows",
    before,
    len(demographics_clean)
)


before = len(transactions_clean)

transactions_clean = (
    transactions_clean
    .drop_duplicates()
    .copy()
)

log_cleaning_step(
    "Customer Transactions",
    "Remove exact duplicate rows",
    before,
    len(transactions_clean)
)


before = len(social_clean)

social_clean = (
    social_clean
    .drop_duplicates()
    .copy()
)

log_cleaning_step(
    "Social Media Interactions",
    "Remove exact duplicate rows",
    before,
    len(social_clean)
)

print("Exact duplicate removal completed.")

Exact duplicate removal completed.

In [ ]:
# REMOVE UNRESOLVED IDENTIFIER CONFLICTS
# Record-level identifiers are expected to represent one unique record.
# When the same identifier belongs to multiple non-identical records and
# there is no evidence showing which record is authoritative, the entire
# conflicting identifier group is omitted rather than arbitrarily keeping
# the first occurrence.

def remove_conflicting_ids(df, id_column):
    conflicting_ids = df.loc[
        df.duplicated(
            subset=id_column,
            keep=False
        ),
        id_column
    ].unique()

    cleaned = df[
        ~df[id_column].isin(conflicting_ids)
    ].copy()

    return cleaned, conflicting_ids


before = len(demographics_clean)

demographics_clean, demographic_conflict_ids = (
    remove_conflicting_ids(
        demographics_clean,
        "customer_id"
    )
)

log_cleaning_step(
    "Customer Demographics",
    "Remove unresolved CustomerID conflicts",
    before,
    len(demographics_clean)
)


before = len(transactions_clean)

transactions_clean, transaction_conflict_ids = (
    remove_conflicting_ids(
        transactions_clean,
        "transaction_id"
    )
)

log_cleaning_step(
    "Customer Transactions",
    "Remove unresolved TransactionID conflicts",
    before,
    len(transactions_clean)
)


before = len(social_clean)

social_clean, social_conflict_ids = (
    remove_conflicting_ids(
        social_clean,
        "interaction_id"
    )
)

log_cleaning_step(
    "Social Media Interactions",
    "Remove unresolved InteractionID conflicts",
    before,
    len(social_clean)
)

print("Identifier conflict treatment completed.")

Identifier conflict treatment completed.

In [ ]:
# OMIT RECORDS CONTAINING MISSING VALUES
# Missing values are not imputed because the supplied FinMark datasets do
# not provide sufficient evidence for reliable replacement values.
# Rows containing missing information are therefore omitted, and the
# resulting reduction in sample size is documented.

before = len(demographics_clean)

demographics_clean = (
    demographics_clean
    .dropna()
    .copy()
)

log_cleaning_step(
    "Customer Demographics",
    "Omit rows containing missing values",
    before,
    len(demographics_clean)
)


before = len(transactions_clean)

transactions_clean = (
    transactions_clean
    .dropna()
    .copy()
)

log_cleaning_step(
    "Customer Transactions",
    "Omit rows containing missing values",
    before,
    len(transactions_clean)
)


before = len(social_clean)

social_clean = (
    social_clean
    .dropna()
    .copy()
)

log_cleaning_step(
    "Social Media Interactions",
    "Omit rows containing missing values",
    before,
    len(social_clean)
)

print("Missing-value treatment completed.")

Missing-value treatment completed.

In [ ]:
# CLEAN CUSTOMER AGE
# Age is converted to numeric form.
# Records are retained only when Age can be converted successfully and
# falls within the documented analytical range of 0 to 120.
# Values such as Unknown, negative ages, and ages above 120 are omitted
# rather than estimated or corrected.

before = len(demographics_clean)

demographics_clean["age"] = pd.to_numeric(
    demographics_clean["age"],
    errors="coerce"
)

valid_age_mask = (
    demographics_clean["age"].notna()
    & demographics_clean["age"].between(
        0,
        120,
        inclusive="both"
    )
)

demographics_clean = (
    demographics_clean.loc[
        valid_age_mask
    ]
    .copy()
)

demographics_clean["age"] = (
    demographics_clean["age"]
    .astype("int64")
)

log_cleaning_step(
    "Customer Demographics",
    "Remove unusable or invalid Age records",
    before,
    len(demographics_clean)
)

print("Age cleaning completed.")

Age cleaning completed.

In [ ]:
# CLEAN TRANSACTION AMOUNT
# Amount is converted to numeric form.
# "Free" is normalized to 0.0 because it explicitly represents no monetary
# charge rather than an unknown amount.
# Negative amounts are omitted because no transaction-type field supports
# interpreting them as refunds or reversals.
# Existing numeric zero values are retained.

before = len(transactions_clean)

amount_text = (
    transactions_clean["amount"]
    .astype("string")
    .str.strip()
)

free_mask = (
    amount_text
    .str.casefold()
    .eq("free")
)

amount_text.loc[free_mask] = "0"

transactions_clean["amount"] = pd.to_numeric(
    amount_text,
    errors="coerce"
)

valid_amount_mask = (
    transactions_clean["amount"].notna()
    & (transactions_clean["amount"] >= 0)
)

transactions_clean = (
    transactions_clean.loc[
        valid_amount_mask
    ]
    .copy()
)

transactions_clean["amount"] = (
    transactions_clean["amount"]
    .astype("float64")
)

log_cleaning_step(
    "Customer Transactions",
    "Normalize Free to 0 and remove unsupported negative Amount records",
    before,
    len(transactions_clean)
)

print("Transaction Amount cleaning completed.")

Transaction Amount cleaning completed.

In [ ]:
# NORMALIZE DATE FIELDS
# The verified mixed date formats are converted using the explicit FinMark
# date parser developed during verification.
# All valid dates are stored as proper datetime values and will later be
# exported consistently in YYYY-MM-DD format.

demographics_clean["signup_date"] = parse_finmark_date(
    demographics_clean["signup_date"]
)

transactions_clean["transaction_date"] = parse_finmark_date(
    transactions_clean["transaction_date"]
)

social_clean["interaction_date"] = parse_finmark_date(
    social_clean["interaction_date"]
)

print(
    "Unparsed SignupDate values:",
    demographics_clean["signup_date"].isna().sum()
)

print(
    "Unparsed TransactionDate values:",
    transactions_clean["transaction_date"].isna().sum()
)

print(
    "Unparsed InteractionDate values:",
    social_clean["interaction_date"].isna().sum()
)

Unparsed SignupDate values: 0
Unparsed TransactionDate values: 0
Unparsed InteractionDate values: 0

In [ ]:
# RESET CLEANED DATASET INDEXES
# Row removal leaves gaps in the original Pandas indexes.
# Resetting creates a continuous zero-based index without modifying the
# actual CustomerID, TransactionID, or InteractionID fields.

demographics_clean = (
    demographics_clean
    .reset_index(drop=True)
)

transactions_clean = (
    transactions_clean
    .reset_index(drop=True)
)

social_clean = (
    social_clean
    .reset_index(drop=True)
)

print("Cleaned dataset indexes reset.")

Cleaned dataset indexes reset.

In [ ]:
# CLEANING AUDIT SUMMARY
# The audit summarizes how many records were present before and after each
# row-removal operation. These results will support the final preprocessing
# summary and README documentation.

cleaning_audit = pd.DataFrame(
    cleaning_log
)

display(cleaning_audit)

,Dataset,Cleaning Step,Rows Before,Rows After,Rows Removed
0,Customer Demographics,Remove exact duplicate rows,3200,3023,177
1,Customer Transactions,Remove exact duplicate rows,3200,3015,185
2,Social Media Interactions,Remove exact duplicate rows,3200,3020,180
3,Customer Demographics,Remove unresolved CustomerID conflicts,3023,2977,46
4,Customer Transactions,Remove unresolved TransactionID conflicts,3015,2985,30
5,Social Media Interactions,Remove unresolved InteractionID conflicts,3020,2980,40
6,Customer Demographics,Omit rows containing missing values,2977,2449,528
7,Customer Transactions,Omit rows containing missing values,2985,2452,533
8,Social Media Interactions,Omit rows containing missing values,2980,2411,569
9,Customer Demographics,Remove unusable or invalid Age records,2449,2378,71
10,Customer Transactions,Normalize Free to 0 and remove unsupported neg...,2452,2420,32

In [ ]:
# POST-CLEANING CROSS-DATASET CUSTOMER COVERAGE
# Cleaning the demographics dataset may remove customer records because of
# missing, conflicting, or invalid demographic information.
#
# Transactions and social media interactions belonging to those customers
# may still be valid activity records. They are therefore not automatically
# deleted.
#
# This check measures how many activity records no longer have a matching
# customer in the cleaned demographics dataset. The result will be documented
# as a limitation for later dataset integration or machine learning.

clean_demographic_customers = set(
    demographics_clean["customer_id"].unique()
)

clean_transaction_customers = set(
    transactions_clean["customer_id"].unique()
)

clean_social_customers = set(
    social_clean["customer_id"].unique()
)

transaction_customer_gaps = (
    clean_transaction_customers
    - clean_demographic_customers
)

social_customer_gaps = (
    clean_social_customers
    - clean_demographic_customers
)

transaction_gap_rows = (
    ~transactions_clean["customer_id"]
    .isin(clean_demographic_customers)
).sum()

social_gap_rows = (
    ~social_clean["customer_id"]
    .isin(clean_demographic_customers)
).sum()


post_clean_coverage = pd.DataFrame({
    "Dataset": [
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "CustomerIDs Without Clean Demographics": [
        len(transaction_customer_gaps),
        len(social_customer_gaps)
    ],
    "Affected Activity Rows": [
        transaction_gap_rows,
        social_gap_rows
    ]
})

display(post_clean_coverage)

,Dataset,CustomerIDs Without Clean Demographics,Affected Activity Rows
0,Customer Transactions,336,492
1,Social Media Interactions,336,486

In [ ]:
# POST-CLEANING VALIDATION
# The cleaned datasets are rechecked after preprocessing.
# The purpose is to verify that the cleaning rules were actually successful
# rather than assuming success simply because the scripts completed.
#
# Checks include:
# - missing values
# - exact duplicates
# - record-level identifier uniqueness
# - valid Age values
# - valid transaction Amount values
# - successful date conversion
#
# CustomerID is expected to be unique only in Customer Demographics.
# It may legitimately repeat in transaction and social activity datasets.

post_clean_validation = pd.DataFrame([
    {
        "Dataset": "Customer Demographics",
        "Check": "No missing values",
        "Passed": demographics_clean.isna().sum().sum() == 0
    },
    {
        "Dataset": "Customer Demographics",
        "Check": "No exact duplicate rows",
        "Passed": demographics_clean.duplicated().sum() == 0
    },
    {
        "Dataset": "Customer Demographics",
        "Check": "CustomerID is unique",
        "Passed": demographics_clean["customer_id"].duplicated().sum() == 0
    },
    {
        "Dataset": "Customer Demographics",
        "Check": "Age is numeric",
        "Passed": pd.api.types.is_numeric_dtype(
            demographics_clean["age"]
        )
    },
    {
        "Dataset": "Customer Demographics",
        "Check": "Age is between 0 and 120",
        "Passed": demographics_clean[
            "age"
        ].between(0, 120).all()
    },
    {
        "Dataset": "Customer Demographics",
        "Check": "SignupDate successfully parsed",
        "Passed": demographics_clean[
            "signup_date"
        ].notna().all()
    },

    {
        "Dataset": "Customer Transactions",
        "Check": "No missing values",
        "Passed": transactions_clean.isna().sum().sum() == 0
    },
    {
        "Dataset": "Customer Transactions",
        "Check": "No exact duplicate rows",
        "Passed": transactions_clean.duplicated().sum() == 0
    },
    {
        "Dataset": "Customer Transactions",
        "Check": "TransactionID is unique",
        "Passed": transactions_clean[
            "transaction_id"
        ].duplicated().sum() == 0
    },
    {
        "Dataset": "Customer Transactions",
        "Check": "Amount is numeric",
        "Passed": pd.api.types.is_numeric_dtype(
            transactions_clean["amount"]
        )
    },
    {
        "Dataset": "Customer Transactions",
        "Check": "Amount is non-negative",
        "Passed": (
            transactions_clean["amount"] >= 0
        ).all()
    },
    {
        "Dataset": "Customer Transactions",
        "Check": "TransactionDate successfully parsed",
        "Passed": transactions_clean[
            "transaction_date"
        ].notna().all()
    },

    {
        "Dataset": "Social Media Interactions",
        "Check": "No missing values",
        "Passed": social_clean.isna().sum().sum() == 0
    },
    {
        "Dataset": "Social Media Interactions",
        "Check": "No exact duplicate rows",
        "Passed": social_clean.duplicated().sum() == 0
    },
    {
        "Dataset": "Social Media Interactions",
        "Check": "InteractionID is unique",
        "Passed": social_clean[
            "interaction_id"
        ].duplicated().sum() == 0
    },
    {
        "Dataset": "Social Media Interactions",
        "Check": "InteractionDate successfully parsed",
        "Passed": social_clean[
            "interaction_date"
        ].notna().all()
    }
])

display(post_clean_validation)

print(
    "\nAll post-cleaning validation checks passed:",
    post_clean_validation["Passed"].all()
)

                      Dataset                                Check  Passed
0       Customer Demographics                    No missing values    True
1       Customer Demographics              No exact duplicate rows    True
2       Customer Demographics                 CustomerID is unique    True
3       Customer Demographics                       Age is numeric    True
4       Customer Demographics             Age is between 0 and 120    True
5       Customer Demographics       SignupDate successfully parsed    True
6       Customer Transactions                    No missing values    True
7       Customer Transactions              No exact duplicate rows    True
8       Customer Transactions              TransactionID is unique    True
9       Customer Transactions                    Amount is numeric    True
10      Customer Transactions               Amount is non-negative    True
11      Customer Transactions  TransactionDate successfully parsed    True
12  Social Media Interactions                    No missing values    True
13  Social Media Interactions              No exact duplicate rows    True
14  Social Media Interactions              InteractionID is unique    True
15  Social Media Interactions  InteractionDate successfully parsed    True

All post-cleaning validation checks passed: True

In [ ]:
# BEFORE-VS-AFTER COMPARISON
# This summary measures how preprocessing changed the size of each dataset.
# It documents the number and percentage of records removed so that the
# impact of cleaning on the available sample is transparent.

before_after_summary = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],
    "Raw Rows": [
        len(demographics_raw),
        len(transactions_raw),
        len(social_raw)
    ],
    "Cleaned Rows": [
        len(demographics_clean),
        len(transactions_clean),
        len(social_clean)
    ]
})

before_after_summary["Rows Removed"] = (
    before_after_summary["Raw Rows"]
    - before_after_summary["Cleaned Rows"]
)

before_after_summary["Percent Removed"] = (
    before_after_summary["Rows Removed"]
    / before_after_summary["Raw Rows"]
    * 100
).round(2)

display(before_after_summary)

,Dataset,Raw Rows,Cleaned Rows,Rows Removed,Percent Removed
0,Customer Demographics,3200,2378,822,25.69
1,Customer Transactions,3200,2420,780,24.38
2,Social Media Interactions,3200,2411,789,24.66

In [ ]:
# FINAL CLEANED DATASET PREVIEW
# A small sample of each finalized cleaned dataset is displayed to confirm
# that the expected columns, normalized values, numeric fields, and dates
# appear correctly before the files are exported.

print("CUSTOMER DEMOGRAPHICS")
display(demographics_clean.head())

print("\nCUSTOMER TRANSACTIONS")
display(transactions_clean.head())

print("\nSOCIAL MEDIA INTERACTIONS")
display(social_clean.head())

CUSTOMER DEMOGRAPHICS

,customer_id,age,gender,location,income_level,signup_date
0,9207fa75-5758-48d1-94ad-19c041e0520f,51,Female,Jensenberg,Low,2022-11-17
1,50118139-7264-428f-81cc-a25fddc5d6dd,44,Male,Port Carl,Medium,2024-06-10
2,7d1f2bbc-8d16-4fbc-9b37-ece3324e8ed4,50,Female,Jessebury,High,2023-08-24
3,2de49c7c-32ae-4ba8-b058-622a090d7094,53,Female,Emilyville,Low,2022-02-13
4,8602d631-457c-49c1-8b59-8efb2a4448d4,51,Male,East Keithville,High,2022-04-17

CUSTOMER TRANSACTIONS

,customer_id,transaction_id,transaction_date,amount,product_category,payment_method
0,60567026-f719-4cd6-849e-137e86d8938f,5ff75116-0a50-4d04-80fb-31e5ccbb0769,2024-05-15,117.64,Clothing,PayPal
1,4090ba85-b111-4f75-a792-c777965f5255,2c39b9fe-ff57-4d39-9321-9f5cdf187aa1,2023-04-26,466.14,Health & Beauty,Bank Transfer
2,9223891b-73ff-4d5c-b8ae-13ece82ee28b,f79588dd-3db9-4ffa-97f8-7de0e64259f1,2022-09-23,563.99,Clothing,Debit Card
3,9243eebc-938f-480c-8564-16d503d250de,401c0fc9-60df-4455-ad78-67c132f9897d,2024-04-15,254.44,Automotive,PayPal
4,6e3e8eb8-bc0f-4ffe-9f74-5d5efec9502f,2034aebc-8280-4254-a667-92bcd1c2be4f,2024-06-03,590.52,Home & Garden,Bank Transfer

SOCIAL MEDIA INTERACTIONS

,customer_id,interaction_id,interaction_date,platform,interaction_type,sentiment
0,08a911a3-65e6-4f5d-a6a1-ae7ddcbe28a2,a83fa04c-f109-4f24-8ce1-2078154f6a1c,2024-05-24,Instagram,Comment,Neutral
1,efdfdfc9-5dbb-4478-911a-101a390a0285,28a69c4b-a2e4-4c74-a130-1132d7733fdf,2023-11-01,Instagram,Like,Neutral
2,3e44871b-f56c-4576-b1ca-d1dc999e2166,0c409883-8396-48e4-83fb-887329848696,2023-12-18,Instagram,Comment,Positive
3,aa5eea4b-c948-41f4-9285-229a470002aa,4034dadf-6541-40d6-a7f0-16b20a009c04,2023-11-15,Instagram,Share,Positive
4,481bcc62-9dcb-4766-bbdd-79f5554d73f8,785b7854-4548-4251-83f2-a25da78bfe40,2024-05-28,Twitter,Like,Positive

In [ ]:
# FINAL DATASET STRUCTURE
# Data types and non-null counts are reviewed one final time before export.

print("CUSTOMER DEMOGRAPHICS")
demographics_clean.info()

print("\nCUSTOMER TRANSACTIONS")
transactions_clean.info()

print("\nSOCIAL MEDIA INTERACTIONS")
social_clean.info()

CUSTOMER DEMOGRAPHICS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2378 entries, 0 to 2377
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   2378 non-null   object
 1   age           2378 non-null   int64
 2   gender        2378 non-null   object
 3   location      2378 non-null   object
 4   income_level  2378 non-null   object
 5   signup_date   2378 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 111.6+ KB

CUSTOMER TRANSACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2420 entries, 0 to 2419
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2420 non-null   object
 1   transaction_id    2420 non-null   object
 2   transaction_date  2420 non-null   datetime64[ns]
 3   amount            2420 non-null   float64
 4   product_category  2420 non-null   object
 5   payment_method    2420 non-null   object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 113.6+ KB

SOCIAL MEDIA INTERACTIONS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2411 entries, 0 to 2410
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       2411 non-null   object
 1   interaction_id    2411 non-null   object
 2   interaction_date  2411 non-null   datetime64[ns]
 3   platform          2411 non-null   object
 4   interaction_type  2411 non-null   object
 5   sentiment         2411 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 113.1+ KB

In [ ]:
# FINAL PREPROCESSING RESULT
# The final results are generated directly from the cleaned DataFrames so
# that the reported figures always match the executed notebook output.

display(Markdown(f"""
## Final Preprocessing Results

The FinMark preprocessing workflow successfully produced validated cleaned
datasets for Week 3 submission and later Milestone 1 exploratory analysis.

### Customer Demographics
- Raw records: **{len(demographics_raw):,}**
- Cleaned records: **{len(demographics_clean):,}**
- Records removed: **{len(demographics_raw) - len(demographics_clean):,}**
- Percentage removed: **{((len(demographics_raw) - len(demographics_clean)) / len(demographics_raw) * 100):.2f}%**
- Remaining missing values: **{demographics_clean.isna().sum().sum()}**
- Remaining exact duplicates: **{demographics_clean.duplicated().sum()}**

### Customer Transactions
- Raw records: **{len(transactions_raw):,}**
- Cleaned records: **{len(transactions_clean):,}**
- Records removed: **{len(transactions_raw) - len(transactions_clean):,}**
- Percentage removed: **{((len(transactions_raw) - len(transactions_clean)) / len(transactions_raw) * 100):.2f}%**
- Remaining missing values: **{transactions_clean.isna().sum().sum()}**
- Remaining exact duplicates: **{transactions_clean.duplicated().sum()}**

### Social Media Interactions
- Raw records: **{len(social_raw):,}**
- Cleaned records: **{len(social_clean):,}**
- Records removed: **{len(social_raw) - len(social_clean):,}**
- Percentage removed: **{((len(social_raw) - len(social_clean)) / len(social_raw) * 100):.2f}%**
- Remaining missing values: **{social_clean.isna().sum().sum()}**
- Remaining exact duplicates: **{social_clean.duplicated().sum()}**

All post-cleaning validation checks passed successfully.

The original raw datasets remain unchanged, while the cleaned datasets are
prepared for Milestone 1 exploratory data analysis.
"""))

## Final Preprocessing Results

The FinMark preprocessing workflow successfully produced validated cleaned
datasets for Week 3 submission and later Milestone 1 exploratory analysis.

### Customer Demographics
- Raw records: **3,200**
- Cleaned records: **2,378**
- Records removed: **822**
- Percentage removed: **25.69%**
- Remaining missing values: **0**
- Remaining exact duplicates: **0**

### Customer Transactions
- Raw records: **3,200**
- Cleaned records: **2,420**
- Records removed: **780**
- Percentage removed: **24.38%**
- Remaining missing values: **0**
- Remaining exact duplicates: **0**

### Social Media Interactions
- Raw records: **3,200**
- Cleaned records: **2,411**
- Records removed: **789**
- Percentage removed: **24.66%**
- Remaining missing values: **0**
- Remaining exact duplicates: **0**

All post-cleaning validation checks passed successfully.

The original raw datasets remain unchanged, while the cleaned datasets are
prepared for Milestone 1 exploratory data analysis.

In [ ]:
# CREATE WEEK 3 OUTPUT FOLDER
# A dedicated folder is created in Google Drive to organize the finalized
# Week 3 submission files before they are manually prepared for GitHub.

WEEK3_OUTPUT_PATH = (
    MS1_PATH
    / "Week3_Preprocessing_Submission"
)

WEEK3_OUTPUT_PATH.mkdir(
    exist_ok=True
)

print(
    "Week 3 submission folder:",
    WEEK3_OUTPUT_PATH
)

Week 3 submission folder: /content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/Week3_Preprocessing_Submission

In [ ]:
# SAVE FINAL CLEANED DATASETS
# The validated cleaned DataFrames are exported as CSV files using clear,
# submission-ready filenames.
#
# Dates are written using the standardized YYYY-MM-DD representation.

demographics_output = (
    WEEK3_OUTPUT_PATH
    / "customer_demographics_cleaned.csv"
)

transactions_output = (
    WEEK3_OUTPUT_PATH
    / "customer_transactions_cleaned.csv"
)

social_output = (
    WEEK3_OUTPUT_PATH
    / "social_media_interactions_cleaned.csv"
)

demographics_clean.to_csv(
    demographics_output,
    index=False,
    date_format="%Y-%m-%d"
)

transactions_clean.to_csv(
    transactions_output,
    index=False,
    date_format="%Y-%m-%d"
)

social_clean.to_csv(
    social_output,
    index=False,
    date_format="%Y-%m-%d"
)

print("Final cleaned datasets saved successfully.")

print("\nCustomer Demographics:")
print(demographics_output)

print("\nCustomer Transactions:")
print(transactions_output)

print("\nSocial Media Interactions:")
print(social_output)

Final cleaned datasets saved successfully.

Customer Demographics:
/content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/Week3_Preprocessing_Submission/customer_demographics_cleaned.csv

Customer Transactions:
/content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/Week3_Preprocessing_Submission/customer_transactions_cleaned.csv

Social Media Interactions:
/content/drive/MyDrive/3rd Year 26-27 | Term 1/MO-IT162 - MMLA/MS1/Week3_Preprocessing_Submission/social_media_interactions_cleaned.csv

In [ ]:
# RELOAD SAVED OUTPUT FILES
# The exported CSV files are loaded again to verify that the actual files
# intended for submission remain complete and usable after serialization.

demographics_final = pd.read_csv(
    demographics_output
)

transactions_final = pd.read_csv(
    transactions_output
)

social_final = pd.read_csv(
    social_output
)

print("Saved cleaned datasets reloaded successfully.")

Saved cleaned datasets reloaded successfully.

In [ ]:
# VALIDATE EXPORTED WEEK 3 FILES
# The reloaded CSV files are checked for row-count consistency, missing
# values, and exact duplicate records.
#
# This ensures that the submitted files match the validated in-memory
# cleaned datasets.

saved_output_validation = pd.DataFrame({
    "Dataset": [
        "Customer Demographics",
        "Customer Transactions",
        "Social Media Interactions"
    ],

    "Expected Rows": [
        len(demographics_clean),
        len(transactions_clean),
        len(social_clean)
    ],

    "Reloaded Rows": [
        len(demographics_final),
        len(transactions_final),
        len(social_final)
    ],

    "Missing Values": [
        demographics_final.isna().sum().sum(),
        transactions_final.isna().sum().sum(),
        social_final.isna().sum().sum()
    ],

    "Exact Duplicates": [
        demographics_final.duplicated().sum(),
        transactions_final.duplicated().sum(),
        social_final.duplicated().sum()
    ]
})

saved_output_validation["Row Count Match"] = (
    saved_output_validation["Expected Rows"]
    ==
    saved_output_validation["Reloaded Rows"]
)

display(saved_output_validation)

,Dataset,Expected Rows,Reloaded Rows,Missing Values,Exact Duplicates,Row Count Match
0,Customer Demographics,2378,2378,0,0,True
1,Customer Transactions,2420,2420,0,0,True
2,Social Media Interactions,2411,2411,0,0,True

In [ ]:
# VERIFY EXPORTED DATE FORMAT
# Date fields in the saved CSV files are checked to confirm that every
# value follows the finalized YYYY-MM-DD format.

def valid_iso_dates(series):
    return (
        series
        .astype("string")
        .str.fullmatch(
            r"\d{4}-\d{2}-\d{2}"
        )
        .all()
    )


date_export_validation = pd.DataFrame({
    "Date Field": [
        "signup_date",
        "transaction_date",
        "interaction_date"
    ],

    "YYYY-MM-DD Format Valid": [
        valid_iso_dates(
            demographics_final["signup_date"]
        ),
        valid_iso_dates(
            transactions_final["transaction_date"]
        ),
        valid_iso_dates(
            social_final["interaction_date"]
        )
    ]
})

display(date_export_validation)

         Date Field  YYYY-MM-DD Format Valid
0       signup_date                     True
1  transaction_date                     True
2  interaction_date                     True

In [ ]:
# FINAL WEEK 3 OUTPUT VALIDATION
# A single final result confirms whether the exported files satisfy the
# core preprocessing output checks required before submission.

week3_outputs_valid = (
    saved_output_validation["Row Count Match"].all()
    and (saved_output_validation["Missing Values"] == 0).all()
    and (saved_output_validation["Exact Duplicates"] == 0).all()
    and date_export_validation[
        "YYYY-MM-DD Format Valid"
    ].all()
)

print(
    "Week 3 finalized output validation passed:",
    week3_outputs_valid
)

Week 3 finalized output validation passed: True